### ISSUE TITLE
NullPointerException when running ./bin/collector  and  ./bin/query 

### ISSUE THREAD

**Issue by zxy12** [openzipkin/zipkin#1040]
$ ./bin/collector --info --stacktrace
:zipkin-common:compileJava UP-TO-DATE
:zipkin-common:compileScala UP-TO-DATE
:zipkin-common:processResources UP-TO-DATE
:zipkin-common:classes UP-TO-DATE
:zipkin-common:jar UP-TO-DATE
:zipkin-scrooge:idlJar UP-TO-DATE
:zipkin-scrooge:copyDependencyIdl UP-TO-DATE
:zipkin-scrooge:copyIncludedIdl UP-TO-DATE
:zipkin-scrooge:generateInterfaces UP-TO-DATE
:zipkin-scrooge:compileJava UP-TO-DATE
:zipkin-scrooge:compileScala UP-TO-DATE
:zipkin-scrooge:processResources UP-TO-DATE
:zipkin-scrooge:classes UP-TO-DATE
:zipkin-scrooge:jar UP-TO-DATE
:zipkin-anormdb:compileJava UP-TO-DATE
:zipkin-anormdb:compileScala UP-TO-DATE
:zipkin-anormdb:processResources UP-TO-DATE
:zipkin-anormdb:classes UP-TO-DATE
:zipkin-anormdb:jar UP-TO-DATE
:zipkin-cassandra-core:compileJava UP-TO-DATE
:zipkin-cassandra-core:compileScala UP-TO-DATE
:zipkin-cassandra-core:processResources UP-TO-DATE
:zipkin-cassandra-core:classes UP-TO-DATE
:zipkin-cassandra-core:jar UP-TO-DATE
:zipkin-cassandra:compileJava UP-TO-DATE
:zipkin-cassandra:compileScala UP-TO-DATE
:zipkin-cassandra:processResources UP-TO-DATE
:zipkin-cassandra:classes UP-TO-DATE
:zipkin-cassandra:jar UP-TO-DATE
:zipkin-collector:compileJava UP-TO-DATE
:zipkin-collector:compileScala UP-TO-DATE
:zipkin-collector:processResources UP-TO-DATE
:zipkin-collector:classes UP-TO-DATE
:zipkin-collector:jar UP-TO-DATE
:zipkin-receiver-kafka:compileJava UP-TO-DATE
:zipkin-receiver-kafka:compileScala UP-TO-DATE
:zipkin-receiver-kafka:processResources UP-TO-DATE
:zipkin-receiver-kafka:classes UP-TO-DATE
:zipkin-receiver-kafka:jar UP-TO-DATE
:zipkin-receiver-scribe:idlJar UP-TO-DATE
:zipkin-receiver-scribe:copyDependencyIdl UP-TO-DATE
:zipkin-receiver-scribe:copyIncludedIdl UP-TO-DATE
:zipkin-receiver-scribe:generateInterfaces UP-TO-DATE
:zipkin-receiver-scribe:compileJava UP-TO-DATE
:zipkin-receiver-scribe:compileScala UP-TO-DATE
:zipkin-receiver-scribe:processResources UP-TO-DATE
:zipkin-receiver-scribe:classes UP-TO-DATE
:zipkin-receiver-scribe:jar UP-TO-DATE
:zipkin-collector-service:compileJava UP-TO-DATE
:zipkin-collector-service:compileScala UP-TO-DATE
:zipkin-collector-service:processResources UP-TO-DATE
:zipkin-collector-service:classes UP-TO-DATE
:zipkin-collector-service:run
三月 16, 2016 6:38:18 下午 com.twitter.zipkin.collector.Main$ main
INFO: Loading configuration
Exception in thread "main" java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
    at com.google.common.io.Resources$UrlByteSource.<init>(Resources.java:82)
    at com.google.common.io.Resources$UrlByteSource.<init>(Resources.java:77)
    at com.google.common.io.Resources.asByteSource(Resources.java:71)
    at com.google.common.io.Resources.asCharSource(Resources.java:120)
    at com.google.common.io.Resources.toString(Resources.java:145)
    at com.twitter.zipkin.collector.Main$.main(Main.scala:39)
    at com.twitter.zipkin.collector.Main.main(Main.scala)
:zipkin-collector-service:run FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':zipkin-collector-service:run'.
  
  > Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':zipkin-collector-service:run'.
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
  at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
  at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
  at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
  at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
  at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
  at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
  at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
  at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
  at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
  at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
  at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
  at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
  at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
  at org.gradle.internal.Factories$1.create(Factories.java:22)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
  at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
  at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
  at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
  at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
  at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
  at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
  at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
  at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
  at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
  at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
  at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
  at org.gradle.util.Swapper.swap(Swapper.java:38)
  at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
  at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
  at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
  at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
  at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
  Caused by: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
  at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
  at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:31)
  at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:75)
  at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
  ... 68 more

**Comment by zxy12** [comment]
$ ./bin/query --info --stacktrace
:zipkin-common:compileJava UP-TO-DATE
:zipkin-common:compileScala UP-TO-DATE
:zipkin-common:processResources UP-TO-DATE
:zipkin-common:classes UP-TO-DATE
:zipkin-common:jar UP-TO-DATE
:zipkin-scrooge:idlJar UP-TO-DATE
:zipkin-scrooge:copyDependencyIdl UP-TO-DATE
:zipkin-scrooge:copyIncludedIdl UP-TO-DATE
:zipkin-scrooge:generateInterfaces UP-TO-DATE
:zipkin-scrooge:compileJava UP-TO-DATE
:zipkin-scrooge:compileScala UP-TO-DATE
:zipkin-scrooge:processResources UP-TO-DATE
:zipkin-scrooge:classes UP-TO-DATE
:zipkin-scrooge:jar UP-TO-DATE
:zipkin-anormdb:compileJava UP-TO-DATE
:zipkin-anormdb:compileScala UP-TO-DATE
:zipkin-anormdb:processResources UP-TO-DATE
:zipkin-anormdb:classes UP-TO-DATE
:zipkin-anormdb:jar UP-TO-DATE
:zipkin-cassandra-core:compileJava UP-TO-DATE
:zipkin-cassandra-core:compileScala UP-TO-DATE
:zipkin-cassandra-core:processResources UP-TO-DATE
:zipkin-cassandra-core:classes UP-TO-DATE
:zipkin-cassandra-core:jar UP-TO-DATE
:zipkin-cassandra:compileJava UP-TO-DATE
:zipkin-cassandra:compileScala UP-TO-DATE
:zipkin-cassandra:processResources UP-TO-DATE
:zipkin-cassandra:classes UP-TO-DATE
:zipkin-cassandra:jar UP-TO-DATE
:zipkin-query:compileJava UP-TO-DATE
:zipkin-query:compileScala UP-TO-DATE
:zipkin-query:processResources UP-TO-DATE
:zipkin-query:classes UP-TO-DATE
:zipkin-query:jar UP-TO-DATE
:zipkin-query-service:compileJava UP-TO-DATE
:zipkin-query-service:compileScala UP-TO-DATE
:zipkin-query-service:processResources UP-TO-DATE
:zipkin-query-service:classes UP-TO-DATE
:zipkin-query-service:run
Exception in thread "main" java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
    at com.google.common.io.Resources$UrlByteSource.<init>(Resources.java:82)
    at com.google.common.io.Resources$UrlByteSource.<init>(Resources.java:77)
    at com.google.common.io.Resources.asByteSource(Resources.java:71)
    at com.google.common.io.Resources.asCharSource(Resources.java:120)
    at com.google.common.io.Resources.toString(Resources.java:145)
    at com.twitter.zipkin.query.Main$.main(Main.scala:36)
    at com.twitter.zipkin.query.Main.main(Main.scala)
:zipkin-query-service:run FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':zipkin-query-service:run'.
  
  > Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.712 secs

**Comment by zxy12** [comment]
my jdk is 1.8, and my os is OSX, i use the step like this:

$git clone https://github.com/openzipkin/zipkin /var/www/zipkin
$cd /var/www/zipkin
$./bin/query

**Comment by codefromthecrypt** [comment]
I think you are trying to pass gradle args to the shell scripts. They
aren't written to do that.

The only arg to pass to collector or query is the storage type. ex
cassandra or mysql (or leave it out to be local).

Ex. bin/query cassandra

you can what's going on by doing "bash -x bin/query cassandra"

underneath, you'll notice it calls gradle internally. You can feel free to
do that as well.

Hope this helps!

**Comment by zxy12** [comment]
@adriancole thanks a lot,now it looks good when  i remove the arg..
