### ISSUE TITLE
run bin/query  npmBuild error on zipkin-ui

### ISSUE THREAD

**Issue by zqhxuyuan** [openzipkin/zipkin#1122]
I follow the official document quickstart by Running from Souce

```
git clone https://github.com/openzipkin/zipkin
cd zipkin
bin/query
```

everything goes fine such as download gradle, build zipkin modules
but when build ui module ,there are some errors: 

```
:zipkin-ui:npmInstall UP-TO-DATE
:zipkin-ui:npmBuild

> zipkin-ui@0.0.0 build /home/qihuang.zheng/zipkin-1.40.1/zipkin-ui
> node node_modules/webpack/bin/webpack.js --bail

ModuleBuildError: Module build failed: Error: /home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/node-sass/vendor/linux-x64-47/binding.node: ELF load command past end of file
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/node-sass/lib/index.js:23:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at DependenciesBlock.loadPitch (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack-core/lib/NormalModuleMixin.js:193:17)
    at DependenciesBlock.loadPitch (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
    at DependenciesBlock.loadPitch (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
    at DependenciesBlock.doBuild (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/Compilation.js:126:9)
    at Compilation.<anonymous> (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/Compilation.js:398:8)
    at /home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/tapable/lib/Tapable.js:75:69)
    at onDoneResolving (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at DependenciesBlock.onModuleBuildFailed (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at DependenciesBlock.<anonymous> (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack-core/lib/NormalModuleMixin.js:228:39)
    at context.callback (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.<anonymous> (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/extract-text-webpack-plugin/loader.js:82:20)
    at Compiler.<anonymous> (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/Compiler.js:204:18)
    at Compiler.<anonymous> (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/Compiler.js:395:18)
    at /home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/tapable/lib/Tapable.js:99:11
    at Compilation.<anonymous> (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/Compilation.js:433:11)
    at errorAndCallback (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/Compilation.js:340:3)
    at Compilation.<anonymous> (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/Compilation.js:400:12)
    at /home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
    at callback (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/Compilation.js:137:11)
    at DependenciesBlock.<anonymous> (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/NormalModule.js:85:18)
    at DependenciesBlock.loadPitch (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack-core/lib/NormalModuleMixin.js:206:13)
    at DependenciesBlock.loadPitch (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
    at DependenciesBlock.loadPitch (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
    at DependenciesBlock.doBuild (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/Compilation.js:126:9)
    at Compilation.<anonymous> (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/Compilation.js:398:8)
    at /home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/tapable/lib/Tapable.js:75:69)
    at onDoneResolving (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/NormalModuleFactory.js:121:6)
    at /home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/webpack/lib/NormalModuleFactory.js:98:13
    at /home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/async/lib/async.js:726:13
    at /home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/node_modules/async/lib/async.js:236:30)
[BABEL] Note: The code generator has deoptimised the styling of "/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/libs/dagre-d3/js/dagre-d3.js" as it exceeds the max of "100KB".

npm ERR! Linux 3.10.97-1.el6.elrepo.x86_64
npm ERR! argv "/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/build/nodejs/node-v5.5.0-linux-x64/bin/node" "/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/build/nodejs/node-v5.5.0-linux-x64/lib/node_modules/npm/bin/npm-cli.js" "run-script" "build"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! zipkin-ui@0.0.0 build: `node node_modules/webpack/bin/webpack.js --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zipkin-ui@0.0.0 build script 'node node_modules/webpack/bin/webpack.js --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zipkin-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/webpack/bin/webpack.js --bail
npm ERR! You can get their info via:
npm ERR!     npm owner ls zipkin-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/npm-debug.log
:zipkin-ui:npmBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':zipkin-ui:npmBuild'.
> Process 'command '/home/qihuang.zheng/zipkin-1.40.1/zipkin-ui/build/nodejs/node-v5.5.0-linux-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 16 mins 53.602 secs
```

and if leave the error alone, then run **bin/web**, also has problem 😭 

```
> Building 90% > :zipkin-web:run
E 0527 08:43:41.629 THREAD41: Exception propagated to the root monitor!
com.twitter.finagle.FailedFastException: Endpoint zipkin-web is marked down. For more details see: https://twitter.github.io/finagle/guide/FAQ.html#why-do-clients-see-com-twitter-finagle-failedfastexception-s. Remote Info: Not Available
    at com.twitter.finagle.NoStacktrace(Unknown Source)
```

anyone meet this problem?

**Comment by eirslett** [comment]
Looks like a problem with node-sass on your computer with your node/npm version, try googling that?

**Comment by codefromthecrypt** [comment]
please re-open if the new codebase has this issue (I think it won't)
