### ISSUE TITLE
com.datastax.driver.core.exceptions.OperationTimedOutException with fresh database when querying with a duration

### ISSUE THREAD

**Issue by devinsba** [openzipkin/zipkin#1133]
I just dropped my cassandra database because this issue had been happening. My searching lead me to believe that the span names we inserted where the problem.

Now that I am running on a fresh cassandra database though I do not believe that was the case

```
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: SCRUB:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [SCRUB] Timed out waiting for server response))
    at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:207) [cassandra-driver-core-3.0.2.jar:na]
    at com.datastax.driver.core.RequestHandler.access$1000(RequestHandler.java:43) [cassandra-driver-core-3.0.2.jar:na]
    at com.datastax.driver.core.RequestHandler$SpeculativeExecution.sendRequest(RequestHandler.java:273) ~[cassandra-driver-core-3.0.2.jar:na]
    at com.datastax.driver.core.RequestHandler$SpeculativeExecution$1.run(RequestHandler.java:396) ~[cassandra-driver-core-3.0.2.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_72]
```

Tested not working with:

Cassandra 3.5 and Zipkin 1.1.4
and Cassandra 3.0 and Zipkin 1.1.4

**Comment by codefromthecrypt** [comment]
duration query needs some major work and was previously tracked in
https://github.com/openzipkin/zipkin-java/issues/200

we should probably migrate some of the issues to the new repo

**Comment by shakuzen** [comment]
I assume this isn't still an issue on the current code base, but could @devinsba or @adriancole confirm? :)

**Comment by jorgheymans** [comment]
Not wanting to play the stale bot here, but i'm closing this as it has not been reported or commented on since pretty much 4 years ago. Feel free to reopen if you feel strongly about this still.
