### ISSUE TITLE
Why did I fail to build the zipkin project?

### ISSUE THREAD

**Issue by liangman** [openzipkin/zipkin#1134]
who can do me a favour please?

./mvnw  -DskipTests --also-make -pl zipkin-server clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Zipkin (Parent)
[INFO] Zipkin
[INFO] Zipkin UI
[INFO] Guava support library
[INFO] Storage
[INFO] Storage: Cassandra
[INFO] Storage: MySQL
[INFO] Storage: Elasticsearch
[INFO] Zipkin Collectors
[INFO] Collector: Scribe
[INFO] Collector: Kafka
[INFO] Auto Configuration
[INFO] Auto Configuration: Ui
[INFO] Auto Configuration: Kafka Collector
[INFO] Auto Configuration: Scribe Collector
[INFO] Auto Configuration: Cassandra Storage
[INFO] Auto Configuration: Elasticsearch Storage
[INFO] Auto Configuration: MySQL Storage
[INFO] Zipkin Server
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Zipkin (Parent) 1.1.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ parent ---
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ parent ---
[INFO] No sources to compile
[INFO] 
[INFO] --- license-maven-plugin:2.11:check (default) @ parent ---
[INFO] Checking licenses...
[WARNING] failure occured while calling class com.mycila.maven.plugin.license.git.CopyrightRangeProvider
[WARNING] failure occured while calling class com.mycila.maven.plugin.license.git.CopyrightRangeProvider
java.lang.RuntimeException: Could not compute the year of the last git commit for file /opt/zipkin-java/travis/publish.sh
    at com.mycila.maven.plugin.license.git.CopyrightRangeProvider.getAdditionalProperties(CopyrightRangeProvider.java:95)
    at com.mycila.maven.plugin.license.AbstractLicenseMojo$1.load(AbstractLicenseMojo.java:338)
    at com.mycila.maven.plugin.license.document.Document.mergeProperties(Document.java:97)
    at com.mycila.maven.plugin.license.header.Header.isMatchForText(Header.java:179)
    at com.mycila.maven.plugin.license.document.Document.hasHeader(Document.java:85)
    at com.mycila.maven.plugin.license.AbstractLicenseMojo$2.run(AbstractLicenseMojo.java:376)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: One of setGitDir or setWorkTree must be called.
    at org.eclipse.jgit.lib.BaseRepositoryBuilder.requireGitDirOrWorkTree(BaseRepositoryBuilder.java:586)
    at org.eclipse.jgit.lib.BaseRepositoryBuilder.setup(BaseRepositoryBuilder.java:554)
    at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:92)
    at com.mycila.maven.plugin.license.git.GitLookup.<init>(GitLookup.java:75)
    at com.mycila.maven.plugin.license.git.CopyrightRangeProvider.getGitLookup(CopyrightRangeProvider.java:138)
    at com.mycila.maven.plugin.license.git.CopyrightRangeProvider.getAdditionalProperties(CopyrightRangeProvider.java:84)
    ... 12 more
[WARNING] failure occured while calling class com.mycila.maven.plugin.license.git.CopyrightRangeProvider
java.lang.RuntimeException: Could not compute the year of the last git commit for file /opt/zipkin-java/pom.xml
    at com.mycila.maven.plugin.license.git.CopyrightRangeProvider.getAdditionalProperties(CopyrightRangeProvider.java:95)
    at com.mycila.maven.plugin.license.AbstractLicenseMojo$1.load(AbstractLicenseMojo.java:338)
    at com.mycila.maven.plugin.license.document.Document.mergeProperties(Document.java:97)
    at com.mycila.maven.plugin.license.header.Header.isMatchForText(Header.java:179)
    at com.mycila.maven.plugin.license.document.Document.hasHeader(Document.java:85)
    at com.mycila.maven.plugin.license.AbstractLicenseMojo$2.run(AbstractLicenseMojo.java:376)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: One of setGitDir or setWorkTree must be called.
    at org.eclipse.jgit.lib.BaseRepositoryBuilder.requireGitDirOrWorkTree(BaseRepositoryBuilder.java:586)
    at org.eclipse.jgit.lib.BaseRepositoryBuilder.setup(BaseRepositoryBuilder.java:554)
    at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:92)
    at com.mycila.maven.plugin.license.git.GitLookup.<init>(GitLookup.java:75)
    at com.mycila.maven.plugin.license.git.CopyrightRangeProvider.getGitLookup(CopyrightRangeProvider.java:138)
    at com.mycila.maven.plugin.license.git.CopyrightRangeProvider.getAdditionalProperties(CopyrightRangeProvider.java:84)
    ... 12 more
java.lang.RuntimeException: Could not compute the year of the last git commit for file /opt/zipkin-java/.settings.xml
    at com.mycila.maven.plugin.license.git.CopyrightRangeProvider.getAdditionalProperties(CopyrightRangeProvider.java:95)
    at com.mycila.maven.plugin.license.AbstractLicenseMojo$1.load(AbstractLicenseMojo.java:338)
    at com.mycila.maven.plugin.license.document.Document.mergeProperties(Document.java:97)
    at com.mycila.maven.plugin.license.header.Header.isMatchForText(Header.java:179)
    at com.mycila.maven.plugin.license.document.Document.hasHeader(Document.java:85)
    at com.mycila.maven.plugin.license.AbstractLicenseMojo$2.run(AbstractLicenseMojo.java:376)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: One of setGitDir or setWorkTree must be called.
    at org.eclipse.jgit.lib.BaseRepositoryBuilder.requireGitDirOrWorkTree(BaseRepositoryBuilder.java:586)
    at org.eclipse.jgit.lib.BaseRepositoryBuilder.setup(BaseRepositoryBuilder.java:554)
    at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:92)
    at com.mycila.maven.plugin.license.git.GitLookup.<init>(GitLookup.java:75)
    at com.mycila.maven.plugin.license.git.CopyrightRangeProvider.getGitLookup(CopyrightRangeProvider.java:138)
    at com.mycila.maven.plugin.license.git.CopyrightRangeProvider.getAdditionalProperties(CopyrightRangeProvider.java:84)
    ... 12 more
[WARNING] Missing header in: /opt/zipkin-java/travis/publish.sh
[WARNING] Missing header in: /opt/zipkin-java/.settings.xml
[WARNING] Missing header in: /opt/zipkin-java/pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Zipkin (Parent) .................................... FAILURE [  0.922 s]
[INFO] Zipkin ............................................. SKIPPED
[INFO] Zipkin UI .......................................... SKIPPED
[INFO] Guava support library .............................. SKIPPED
[INFO] Storage ............................................ SKIPPED
[INFO] Storage: Cassandra ................................. SKIPPED
[INFO] Storage: MySQL ..................................... SKIPPED
[INFO] Storage: Elasticsearch ............................. SKIPPED
[INFO] Zipkin Collectors .................................. SKIPPED
[INFO] Collector: Scribe .................................. SKIPPED
[INFO] Collector: Kafka ................................... SKIPPED
[INFO] Auto Configuration ................................. SKIPPED
[INFO] Auto Configuration: Ui ............................. SKIPPED
[INFO] Auto Configuration: Kafka Collector ................ SKIPPED
[INFO] Auto Configuration: Scribe Collector ............... SKIPPED
[INFO] Auto Configuration: Cassandra Storage .............. SKIPPED
[INFO] Auto Configuration: Elasticsearch Storage .......... SKIPPED
[INFO] Auto Configuration: MySQL Storage .................. SKIPPED
[INFO] Zipkin Server ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.268 s
[INFO] Finished at: 2016-06-15T01:12:20+08:00
[INFO] Final Memory: 20M/217M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:2.11:check (default) on project parent: Some files do not have the expected license header -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by xiangqiao123** [comment]
how to resolve this problem ?
thanks!

**Comment by liangman** [comment]
./mvnw com.mycila:license-maven-plugin:format
in CONTRIBUTING.md.

**Comment by xiangqiao123** [comment]
thank you！

**Comment by ghost** [comment]
thank you!
