### ISSUE TITLE
handle cassandra pool busy

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1356]
When there are a lot of in-flight requests, we drop via a BusyPoolException. This notably happens in tests.

```
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [localhost/127.0.0.1] Pool is busy (no available connection and the queue has reached its max size 256)))
	at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:220) ~[cassandra-driver-core-3.3.0.jar!/:na]
	at com.datastax.driver.core.RequestHandler.access$1200(RequestHandler.java:50) ~[cassandra-driver-core-3.3.0.jar!/:na]
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:291) ~[cassandra-driver-core-3.3.0.jar!/:na]
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution$1.onFailure(RequestHandler.java:358) ~[cassandra-driver-core-3.3.0.jar!/:na]
```

There's a discussion here about limiting the in-flight requests https://groups.google.com/a/lists.datastax.com/forum/#!topic/java-driver-user/p3CwOL0kNrs

Note: in our tests, we batch spans in 100 to avoid this.

**Comment by michaelsembwever** [comment]
Problem with `ulimit` ?

**Comment by codefromthecrypt** [comment]
possibly!

it takes 15m for every attempt to sort this in travis, and quite a few
various attempts done today, so not that interested in trying again.

circleci is currently stable on cassandra with the extra configuration
applied to it. If that circle starts failing again, will get out the ulimit
stick :)

https://github.com/openzipkin/zipkin/commit/4597c8b6ca6cb6ffc7284008c32047756483ce19

**Comment by codefromthecrypt** [comment]
reopened cc @openzipkin/cassandra with a bit more in the description

**Comment by codefromthecrypt** [comment]
There are some related notes in the recently announced v1.4 enterprise driver https://groups.google.com/a/lists.datastax.com/forum/#!topic/java-driver-user/OjKA9awxVpQ

**Comment by alseddnm** [comment]
Hey @adriancole we see a bunch of errors in our service log as such ```ERROR: cannot load service names: Request processing failed; nested exception is com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /xxxxx:9042 (com.datastax.driver.core.exceptions.TransportException: [/1xxxx:9042] Connection has been closed),/(com.datastax.driver.core.exceptions.TransportException: [xyz/10.124.8.97:9042] Connection has been closed))```

```com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried:  (com.datastax.driver.core.exceptions.TransportException: [test-cassandra-cloud-mot.service.consul/10.124.4.155:9042] Connection has been closed), /10.124.17.24:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.124.17.24:9042] Timed out waiting for server response), /10.124.8.97:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.124.8.97:9042] Timed out waiting for server response))
	at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:84) ~[cassandra-driver-core-3.5.0-shaded.jar!/:?]
	at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:37) ~[cassandra-driver-core-3.5.0-shaded.jar!/:?]
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37) ~[cassandra-driver-core-3.5.0-shaded.jar!/:?]
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245) ~[cassandra-driver-core-3.5.0-shaded.jar!/:?]
	at zipkin2.storage.cassandra.internal.call.ResultSetFutureCall.getUninterruptibly(ResultSetFutureCall.java:74) ~[zipkin-storage-cassandra-2.9.1.jar!/:?]
	at at zipkin2.storage.cassandra.internal.call.ResultSetFutureCall.getUninterruptibly(ResultSetFutureCall.java:74) ~[zipkin-storage-cassandra-2.9.1.jar!/:?]
	at zipkin2.storage.cassandra.internal.call.ResultSetFutureCall$1CallbackListener.run(ResultSetFutureCall.java:50) [zipkin-storage-cassandra-2.9.1.jar!/:?]
	at zipkin2.storage.cassandra.internal.call.DirectExecutor.execute(DirectExecutor.java:23) [zipkin-storage-cassandra-2.9.1.jar!/:?]````
is this related to this issue?

**Comment by codefromthecrypt** [comment]
how are you expecting this to be handled?

**Comment by alseddnm** [comment]
We are using mesos/marathon to manage our docker containers, zipkin ran fine for 15 mins or so -> then heath check starts failing. Some how the instance dies and mesos spin a new one (during this small time window  C* connections closed then those errors start happening)..
I noticed this issue is about **BusyPoolException** so ours not related.. will investigate (my guess we may need to consider tuning JVM). Thank you....!

**Comment by codefromthecrypt** [comment]
busy pool would imply the cassandra pool is overrun. perhaps due to a surge
of spans. spans would be dropped in this case. not a cassandra tuner
personally, but I suspect increasing resources to account for spikes could
be possible. could ask experts like @michaelsembwever

**Comment by alseddnm** [comment]
@adriancole I believe this issue is zipkin/Cassandra related, going to open a new issue.

**Comment by jorgheymans** [comment]
Limiting in-flight requests has been a feature for a while of more recent Cassandra drivers. The original issue refers to issues during CI and these in particular seem to have been long solved. Cheers !
