### ISSUE TITLE
JsonCodec StackOverflow

### ISSUE THREAD

**Issue by gnoremac** [openzipkin/zipkin#1406]
Got the following exception 

```
java.lang.StackOverflowError
>	at zipkin.internal.Buffer.writeAscii(Buffer.java:107)
>	at zipkin.internal.Buffer.writeUtf8(Buffer.java:230)
>	at zipkin.internal.Buffer.writeJsonEscaped(Buffer.java:226)
>	at zipkin.internal.Buffer.writeJsonEscaped(Buffer.java:192)
>	at zipkin.internal.JsonCodec$3.write(JsonCodec.java:281)
>	at zipkin.internal.JsonCodec$3.write(JsonCodec.java:170)
>	at zipkin.internal.JsonCodec.writeList(JsonCodec.java:633)
>	at zipkin.internal.JsonCodec$4.write(JsonCodec.java:397)
>	at zipkin.internal.JsonCodec$4.write(JsonCodec.java:309)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:609)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
>	at zipkin.internal.JsonCodec.write(JsonCodec.java:611)
>	at zipkin.internal.JsonCodec.writeSpan(JsonCodec.java:426)
>	at zipkin.Span.toString(Span.java:321)
>	at java.lang.String.valueOf(String.java:2994)
>	at java.lang.StringBuilder.append(StringBuilder.java:131)
```

It looks like JsonCodec writes the span into the assertionException

```
static <T> byte[] write(Buffer.Writer<T> writer, T value) {
    Buffer b = new Buffer(writer.sizeInBytes(value));
    try {
      writer.write(value, b);
    } catch (RuntimeException e) {
      throw assertionError("Could not write " + value + " as json", e);
    }
    return b.toByteArray();
  }
```

but the toString method of the Span class calls the codec, if it fails it results in loop.

```
@Override
  public String toString() {
    return new String(SpanCodec.JSON.writeSpan(this), Util.UTF_8);
  }
```

**Comment by codefromthecrypt** [comment]
will fix immediately. thanks

**Comment by codefromthecrypt** [comment]
this looks like it is in brave...

**Comment by codefromthecrypt** [comment]
so when this is sorted, we'll need a bump in brave.

**Comment by codefromthecrypt** [comment]
Here's a failing test:

``` java
  static final class Foo {
    @Override
    public String toString() {
      return new String(JsonCodec.write(new Buffer.Writer<Foo>() {
        @Override public int sizeInBytes(Foo value) {
          return 1;
        }

        @Override public void write(Foo value, Buffer buffer) {
          throw new RuntimeException("buggy encoder");
        }
      }, this), UTF_8);
    }
  }

  @Test
  public void doesntLoopOnToStringError() {
    new Foo().toString();
  }
```

**Comment by codefromthecrypt** [comment]
I think an encoding bug was fixed between the version of zipkin brave is using and now, but here's a permanent fix https://github.com/openzipkin/zipkin/pull/1407

**Comment by codefromthecrypt** [comment]
releasing fix as zipkin 1.16.2 and will propagate this into reporter, brave etc patch releases

**Comment by codefromthecrypt** [comment]
zipkin-reporter 0.6.9 on the way (just dependency change to zipkin 1.16.1)

**Comment by codefromthecrypt** [comment]
cutting brave 3.15.3, zipkin-finagle 0.3.2 (pinned to zipkin 1.16.2, zipkin-reporter 0.6.9)

**Comment by gnoremac** [comment]
Wow your fast thanks.

**Comment by codefromthecrypt** [comment]
NP this class of bug is insidious and needs to be killed immediately!
