### ISSUE TITLE
zipkin-storage-elasticsearch:1.17 not compatible with Elasticsearch 5.x

### ISSUE THREAD

**Issue by jamesbee** [openzipkin/zipkin#1431]
hi, everyone. 

*spoiler: poor english incoming.*

I'm using embedded zipkin-server for a application insight server. Last week i upgrade elasticsearch products to 5.x for filebeats's new feature like streaming over kafka. Then i got caught by a internal server error when query Span:

```
// ignore spring call stack
Caused by: java.lang.NoClassDefFoundError: org/elasticsearch/search/aggregations/bucket/terms/TermsBuilder
	at zipkin.storage.elasticsearch.ElasticsearchStorage.computeGuavaSpanStore(ElasticsearchStorage.java:140) ~[zipkin-storage-elasticsearch-1.17.1.jar:na]
	at zipkin.storage.elasticsearch.ElasticsearchStorage.computeGuavaSpanStore(ElasticsearchStorage.java:26) ~[zipkin-storage-elasticsearch-1.17.1.jar:na]
	at zipkin.storage.guava.LazyGuavaStorageComponent$1.compute(LazyGuavaStorageComponent.java:30) ~[zipkin-guava-1.17.1.jar:na]
	at zipkin.storage.guava.LazyGuavaStorageComponent$1.compute(LazyGuavaStorageComponent.java:27) ~[zipkin-guava-1.17.1.jar:na]
	at zipkin.internal.Lazy.tryCompute(Lazy.java:50) ~[zipkin-1.17.1.jar:na]
	at zipkin.internal.Lazy.get(Lazy.java:37) ~[zipkin-1.17.1.jar:na]
	at zipkin.storage.guava.LazyGuavaStorageComponent.guavaSpanStore(LazyGuavaStorageComponent.java:40) ~[zipkin-guava-1.17.1.jar:na]
	at zipkin.storage.guava.GuavaStorageComponent.asyncSpanStore(GuavaStorageComponent.java:30) ~[zipkin-guava-1.17.1.jar:na]
	at zipkin.storage.guava.GuavaStorageComponent.spanStore(GuavaStorageComponent.java:26) ~[zipkin-guava-1.17.1.jar:na]
	at zipkin.server.ZipkinQueryApiV1.getServiceNames(ZipkinQueryApiV1.java:75) ~[zipkin-server-1.17.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) [spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	... 56 common frames omitted
// ignore class loader call stack
```

`TermsBuilder` used in ES 2.x and deprecated in 5.x.

I do some research and find ES 5.x supported in #1403 , seems no one had crushed to this exception yet.

Then i looked into decompiled class file, i suppose the reason cause this exception is :

```java
// decompiled class file
// zipkin.storage.elasticsearch.ElasticsearchSpanStore#getSpanNames
public ListenableFuture<List<String>> getSpanNames(String serviceName) {
    if(Strings.isNullOrEmpty(serviceName)) {
        return EMPTY_LIST;
    } else {
        serviceName = serviceName.toLowerCase();
        BoolQueryBuilder filter = QueryBuilders.boolQuery().should(QueryBuilders.nestedQuery("annotations", QueryBuilders.termQuery("annotations.endpoint.serviceName", serviceName))).should(QueryBuilders.nestedQuery("binaryAnnotations", QueryBuilders.termQuery("binaryAnnotations.endpoint.serviceName", serviceName)));
        return this.client.collectBucketKeys(this.catchAll, 
          QueryBuilders.boolQuery().must(QueryBuilders.matchAllQuery()).filter(filter),

          // this `(TermsBuilder)` type cast cause NoClassDefFoundError

          new AbstractAggregationBuilder[]{((TermsBuilder)AggregationBuilders.terms("name_agg").order(Order.term(true)).field("name")).size(2147483647)});
    }
}
```

Although `zipkin-storage-elasticsearch` is written in es 2.x & 5.x compatible format, but the compiled class added this type cast transparently by `javac` 😂 

sooo.... any idea?

**Comment by codefromthecrypt** [comment]
The version we're referring to is the cluster we connect to, not the
library version of zipkin itself. That said, we can fix this by making the
elasticsearch dependency optional. It isn't a quick job, so sorry might
take until next week.

**Comment by jamesbee** [comment]
Got it, thanks a lot!  :>

**Comment by codefromthecrypt** [comment]
sorry lost track of this

**Comment by codefromthecrypt** [comment]
starting this now.. I suspect it will take all week to move off the old library https://github.com/openzipkin/zipkin/pull/1495

**Comment by codefromthecrypt** [comment]
After working on this for a while, it looks like the least hard way is to decouple zipkin-storage-elasticsearch-http from zipkin-storage-elasticsearch (which has the 2.x dependency).

**Comment by codefromthecrypt** [comment]
I have a very rough version of this locally, will need the rest of the week to complete it

**Comment by codefromthecrypt** [comment]
sorry this took so long #1509

**Comment by abhijitvk** [comment]
@adriancole - Is there any compatibility matrix for zipkin and elastic storage + elastic search server?

**Comment by codefromthecrypt** [comment]
recent versions of zipkin use a storage driver called
zipkin-storage-elasticsearch-http. This uses the rest api and we've tested
with 2.x and 5.x I think that's in the README

https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/elasticsearch-http

Is there a version you are interested in? (1.x won't be supported)

**Comment by ezraroi** [comment]
@adriancole 
when using with Elastic 5.4.0 i am getting this:
```
Fielddata is disabled on text fields by default. Set fielddata=true on [serviceName] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.
```

I don't know how can i config Zipkin to create the index with `fielddata=true`

**Comment by ezraroi** [comment]
also i found this:
```
Fielddata is disabled on text fields by default. Set fielddata=true on [spanName] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead
```

**Comment by codefromthecrypt** [comment]
Thanks will have a look tomorrow.

On 14 May 2017 19:53, "Roi Ezra" <notifications@github.com> wrote:

@adriancole <https://github.com/adriancole>
when using with Elastic 5.4.0 i am getting this:

Fielddata is disabled on text fields by default. Set fielddata=true on
[serviceName] in order to load fielddata in memory by uninverting the
inverted index. Note that this can however use significant memory.
Alternatively use a keyword field instead.

I don't know how can i config Zipkin to create the index with fielddata=true

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openzipkin/zipkin/issues/1431#issuecomment-301307211>,
or mute the thread

**Comment by codefromthecrypt** [comment]
@ezraroi I just ran the test suites against ES 5.4 and everything passed with no warnings in the log. Also, what you are reporting doesn't have to do with this issue. Can you please open another issue after verifying you are using latest zipkin? If you still have this problem with latest zipkin, please add the whole stack trace in that issue

**Comment by ezraroi** [comment]
ok, sure will do so.
I am running Zipkin 1.24.0 in docker from openzipkin

**Comment by licheng-xd** [comment]
@ezraroi  @adriancole 
I have the sample problem where run zipkin with exec jar and elasticsearchr5.6 with docker. 

```
rg.springframework.web.util.NestedServletException: 
Request processing failed; nested exception is java.lang.IllegalStateException: 
response for aggregation failed: 
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"zipkin:span-2018-07-03","node":"IqUVIo7GQJiTXx5ts4fWpg","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}]},"status":400}
```

**Comment by codefromthecrypt** [comment]
please troubleshoot on gitter first https://gitter.im/openzipkin/zipkin

if this ends up a problem we have to fix, we would open a new issue as it
has nothing to do with elasticsearch 1
