### ISSUE TITLE
zipkin-server use a lot of cpu

### ISSUE THREAD

**Issue by dragontree101** [openzipkin/zipkin#1456]
i use zipkin 1.16 and es as store, my trace is a big json(150k-200k),
i found consume this trace very slow, and cpu usage almost 90%+

i don't know time is spend to consume kafka message or store to es?

i use jstack i found some block by es
```
OkHttp http://10.215.242.15:9200/..." #57 prio=5 os_prio=0 tid=0x00007f9765304000 nid=0x1046 waiting for monitor entry [0x00007f973b9f8000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at okhttp3.Dispatcher.finished(Dispatcher.java:197)
	- waiting to lock <0x0000000087e899f8> (a okhttp3.Dispatcher)
	at okhttp3.Dispatcher.finished(Dispatcher.java:186)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:136)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at com.github.kristofa.brave.BraveRunnable.run(BraveRunnable.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

how can i solve this problem?

**Comment by dragontree101** [comment]
maybe i don't set jvm param, i set jvm param and restart i seem ok.
