### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by tomgithub2016** [openzipkin/zipkin#1532]
In Windows ,

I

`git clone https://github.com/openzipkin/zipkin.git
`and

`cd zipkin`
`execute "mvnw -DskipTests --also-make -pl zipkin-server clean install"`

but build failure,  What's the problem?
```

 [INFO] ------------------------------------------------------------------------
[INFO] Building Zipkin UI 1.20.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ zipkin-ui ---
[INFO] Deleting C:\zipkin\zipkin-ui\target
[INFO]
[INFO] --- frontend-maven-plugin:1.3:install-node-and-npm (install node and npm) @ zipkin-ui ---
[INFO] Installing node version v6.9.2
[INFO] Copying node binary from E:\maven_repository\com\github\eirslett\node\6.9.2\node-6.9.2-win-x64.exe to C:\zipkin\zipkin-ui\target\node\node.exe
[INFO] Installed node locally.
[INFO] Installing npm version 3.10.9
[INFO] Unpacking E:\maven_repository\com\github\eirslett\npm\3.10.9\npm-3.10.9.tar.gz into C:\zipkin\zipkin-ui\target\node\node_modules
[INFO] Installed npm locally.
[INFO]
[INFO] --- frontend-maven-plugin:1.3:npm (npm install) @ zipkin-ui ---
[INFO] Running 'npm install' in C:\zipkin\zipkin-ui
[INFO]
[INFO] > phantomjs-prebuilt@2.1.14 install C:\zipkin\zipkin-ui\node_modules\phantomjs-prebuilt
[INFO] > node install.js
[INFO]
[INFO] PhantomJS not found on PATH
[INFO] Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
[INFO] Saving to C:\Users\taocc\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
[INFO] Receiving...
[INFO]
[ERROR] Error making request.
[ERROR] Error: read ECONNRESET
[ERROR]     at exports._errnoException (util.js:1022:11)
[ERROR]     at TLSWrap.onread (net.js:569:26)
[ERROR]
[ERROR] Please report this full log at https://github.com/Medium/phantomjs
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN zipkin-ui@0.0.0 No repository field.
[ERROR] npm ERR! Windows_NT 10.0.10240
[ERROR] npm ERR! argv "C:\\zipkin\\zipkin-ui\\target\\node\\node.exe" "C:\\zipkin\\zipkin-ui\\target\\node\\node_modules\\npm\\bin\\npm-cli.js" "install"
[ERROR] npm ERR! node v6.9.2
[ERROR] npm ERR! npm  v3.10.9
[ERROR] npm ERR! code ELIFECYCLE
[ERROR]
[ERROR] npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node install.js
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs phantomjs-prebuilt
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls phantomjs-prebuilt
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR]
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     C:\zipkin\zipkin-ui\npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Zipkin (Parent) .................................... SUCCESS [  5.533 s]
[INFO] Zipkin ............................................. SUCCESS [  7.362 s]
[INFO] Zipkin UI .......................................... FAILURE [08:13 min]
[INFO] Guava support library .............................. SKIPPED
[INFO] Storage ............................................ SKIPPED
[INFO] Storage: Elasticsearch ............................. SKIPPED
[INFO] Storage: Cassandra ................................. SKIPPED
[INFO] Storage: Cassandra 3 ............................... SKIPPED
[INFO] Storage: MySQL ..................................... SKIPPED
[INFO] Storage: Elasticsearch (HTTP) ...................... SKIPPED
[INFO] Zipkin Collectors .................................. SKIPPED
[INFO] Collector: Scribe .................................. SKIPPED
[INFO] Collector: Kafka ................................... SKIPPED
[INFO] Auto Configuration ................................. SKIPPED
[INFO] Auto Configuration: Ui ............................. SKIPPED
[INFO] Auto Configuration: Kafka Collector ................ SKIPPED
[INFO] Auto Configuration: Scribe Collector ............... SKIPPED
[INFO] Auto Configuration: Cassandra Storage .............. SKIPPED
[INFO] Auto Configuration: Cassandra 3 Storage ............ SKIPPED
[INFO] Auto Configuration: Elasticsearch Storage .......... SKIPPED
[INFO] Auto Configuration: Elasticsearch Storage (HTTP) ... SKIPPED
[INFO] Auto Configuration: Elasticsearch Storage (AWS) .... SKIPPED
[INFO] Auto Configuration: MySQL Storage .................. SKIPPED
[INFO] Auto Configuration: Prometheus Metrics ............. SKIPPED
[INFO] Zipkin Server ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:26 min
[INFO] Finished at: 2017-03-06T23:31:09+08:00
[INFO] Final Memory: 75M/1497M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:npm (npm install) on project zipkin-ui: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :zipkin-ui
```

**Comment by codefromthecrypt** [comment]
This is a duplicate of #1501

notably, the javascript project requires npm, which isn't installed on your machine and can't be auto-installed. you can try the following to skip building the ui

mvnw -DskipTests --also-make -pl -:zipkin-ui,zipkin-server clean install
