### ISSUE TITLE
Cassandra3 span store randomly throws exceptions when retrieving spans.

### ISSUE THREAD

**Issue by llinder** [openzipkin/zipkin#1542]
Zipkin Version: 1.20.0
Cassandra Version: 3.9

The Cassandra3 CassandraSpanStore.getSpansByTraceIds randomly throws the following exception.

The underlying issue seems to be that the driver sees that the result set current page is exhausted and prepares to fetch more results while in an asynchronous request.  When this happens the driver makes a check to see if the synchronous request is being made while in an event loop.  Then end result is the following stack trace:

```
java.lang.IllegalStateException: Detected a synchronous call on an I/O thread, this can cause deadlocks or unpredictable behavior. This generally happens when a Future callback calls a synchronous Session method (execute() or prepare()), or iterates a result set past the fetch size (causing an internal synchronous fetch of the next page of results). Avoid this in your callbacks, or schedule them on a different executor.
         at com.datastax.driver.core.AbstractSession.checkNotInEventLoop(AbstractSession.java:203) ~[cassandra-driver-core-3.1.3.jar!/:na]
         at com.datastax.driver.core.ArrayBackedResultSet$MultiPage.prepareNextRow(ArrayBackedResultSet.java:310) ~[cassandra-driver-core-3.1.3.jar!/:na]
         at com.datastax.driver.core.ArrayBackedResultSet$MultiPage.isExhausted(ArrayBackedResultSet.java:269) ~[cassandra-driver-core-3.1.3.jar!/:na]
         at com.datastax.driver.core.ArrayBackedResultSet$1.hasNext(ArrayBackedResultSet.java:143) ~[cassandra-driver-core-3.1.3.jar!/:na]
        at zipkin.storage.cassandra3.CassandraSpanStore$4.apply(CassandraSpanStore.java:354) ~[zipkin-storage-cassandra3-1.20.0.jar!/:na]
         at zipkin.storage.cassandra3.CassandraSpanStore$4.apply(CassandraSpanStore.java:351) ~[zipkin-storage-cassandra3-1.20.0.jar!/:na]
         at com.google.common.util.concurrent.Futures$2.apply(Futures.java:760) ~[guava-18.0.jar!/:na]
         at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906) ~[guava-18.0.jar!/:na]
         at zipkin.autoconfigure.storage.cassandra3.brave.TracedSession$BraveResultSetFuture.lambda$addListener$0(TracedSession.java:201) ~[zipkin-autoconfigure-storage-cassandra3-1.20.0.jar!/:na]
         at zipkin.autoconfigure.storage.cassandra3.brave.TracedSession$BraveResultSetFuture$$Lambda$1.run(Unknown Source) ~[zipkin-autoconfigure-storage-cassandra3-1.20.0.jar!/:na]
         at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar!/:na]
         at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar!/:na]
         at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar!/:na]
         at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar!/:na]
         at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:174) ~[cassandra-driver-core-3.1.3.jar!/:na]
         at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:177) ~[cassandra-driver-core-3.1.3.jar!/:na]
         at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:46) ~[cassandra-driver-core-3.1.3.jar!/:na]
         at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:797) ~[cassandra-driver-core-3.1.3.jar!/:na]
         at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:500) ~[cassandra-driver-core-3.1.3.jar!/:na]
         at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1070) ~[cassandra-driver-core-3.1.3.jar!/:na]
         at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:993) ~[cassandra-driver-core-3.1.3.jar!/:na]
         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) ~[netty-handler-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[netty-codec-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) ~[netty-codec-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) ~[netty-codec-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1280) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:890) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391) ~[netty-transport-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[netty-common-4.0.37.Final.jar!/:4.0.37.Final]
         at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145) ~[netty-common-4.0.37.Final.jar!/:4.0.37.Final]
         at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
```

**Comment by codefromthecrypt** [comment]
good capture of the problem.. should be reproducible in a test

**Comment by llinder** [comment]
It would be great to reproduce in a test.   Right now its pretty hit or miss in production though so I'm not sure the best way to reproduce it consistently yet.
