### ISSUE TITLE
Cannot load trace from UI when using cassandra datasource

### ISSUE THREAD

**Issue by ghost** [openzipkin/zipkin#1545]
Hi! I'm using zipkin with cassandra dataSource but when I'm trying to "Find a trace" and go into details on UI it returns me error:
ERROR: Cannot load trace ##############: zipkin.internal.MergeById.apply(Ljava/lang/Iterable;)Ljava/util/List;

My application.yaml file:
```
#-----------------------------------------------------------
server:
  port: 9411
eureka:
  client:
    fetchRegistry: true
endpoints:
  hypermedia:
    enabled: true
  sensitive: false
spring:
  application:
    name: zipkin-server
  zipkin:
    locator:
      discovery:
        enabled: true
  datasource:
    schema: classpath:/cassandra3-schema.cql
    url: jdbc:cassandra://${CASSANDRA_HOST:localhost}:${CASSANDRA_PORT:9042}
    keyspace: eagle2
    contactPoints: ${CASSANDRA_HOST:localhost}
    initialize: true
    continue-on-error: true
  sleuth:
    enabled: false
zipkin:
  storage:
      type: cassandra3
#-----------------------------------------------------------

build.gradle:

buildscript {
    ext {
        springBootVersion = '1.5.2.RELEASE'
    }
    repositories {
        mavenCentral()
        maven {
            url "https://artifacts.alfresco.com/nexus/content/repositories/public/"
        }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

apply plugin: 'org.springframework.boot'

dependencyManagement {
    imports {
        mavenBom 'org.springframework.cloud:spring-cloud-starter-parent:Camden.SR6'
    }
}

springBoot {
    mainClass = 'com.eagleinvsys.zipkin.ZipkinLauncher'
    executable = true
}

jar {
    baseName = 'zipkin-server'
    version = '1.0.0'
}

dependencies {
    compile 'org.springframework.cloud:spring-cloud-starter-eureka:1.2.6.RELEASE'
    //compile 'org.springframework.cloud:spring-cloud-sleuth-zipkin-stream:1.1.0.RELEASE'
    compile 'org.springframework.cloud:spring-cloud-starter-zipkin:1.2.0.M1'
    compile 'org.springframework.boot:spring-boot-starter-actuator'
    compile 'org.springframework.boot:spring-boot-starter-hateoas'
    compile 'io.zipkin.java:zipkin-autoconfigure-ui:1.21.0'
    compile 'io.zipkin.java:zipkin-server:1.21.0'
    compile ('io.zipkin.java:zipkin-autoconfigure-storage-cassandra3:1.21.0') {
        exclude group: 'com.datastax.cassandra:cassandra-driver-core'
    }
    compile 'com.datastax.cassandra:cassandra-driver-core:3.1.4'
    compile 'com.datastax.cassandra:cassandra-driver-mapping:3.1.4'
}

![capture](https://cloud.githubusercontent.com/assets/18097468/24354692/8353b9aa-12fb-11e7-86cc-cb292edf240a.PNG)
![capture1](https://cloud.githubusercontent.com/assets/18097468/24354693/8357284c-12fb-11e7-9170-d388eff8158e.PNG)

Keyspaces in cassandra have been created successfully
![capture2](https://cloud.githubusercontent.com/assets/18097468/24354775/dab557da-12fb-11e7-9691-381fd525adbd.PNG)

Do you have any ideas about this issue?

**Comment by ghost** [comment]
StackTrace:

```
java.lang.NoSuchMethodError: zipkin.internal.MergeById.apply(Ljava/lang/Iterable;)Ljava/util/List;
	at zipkin.storage.cassandra3.CassandraSpanStore$AdjustTrace.apply(CassandraSpanStore.java:257) ~[zipkin-storage-cassandra3-1.21.0.jar:na]
	at zipkin.storage.cassandra3.CassandraSpanStore$AdjustTrace.apply(CassandraSpanStore.java:253) ~[zipkin-storage-cassandra3-1.21.0.jar:na]
	at com.google.common.util.concurrent.Futures$2.apply(Futures.java:760) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:918) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:106) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:914) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:918) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:106) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:914) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:174) ~[cassandra-driver-core-3.1.4.jar:na]
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:177) ~[cassandra-driver-core-3.1.4.jar:na]
	at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:46) ~[cassandra-driver-core-3.1.4.jar:na]
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:799) ~[cassandra-driver-core-3.1.4.jar:na]
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:502) ~[cassandra-driver-core-3.1.4.jar:na]
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1070) ~[cassandra-driver-core-3.1.4.jar:na]
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:993) ~[cassandra-driver-core-3.1.4.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) ~[netty-handler-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[netty-codec-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) ~[netty-codec-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) ~[netty-codec-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1280) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:890) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391) ~[netty-transport-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[netty-common-4.0.37.Final.jar:4.0.37.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145) ~[netty-common-4.0.37.Final.jar:4.0.37.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

**Comment by codefromthecrypt** [comment]
it looks like your zipkin versions are not aligned. I'd set everything under the io.zipkin.java group id to the same version. gradle can do this I think.

**Comment by ghost** [comment]
Sorry for disturbing you, I simply added whole library 'io.zipkin.java:zipkin:1.21.0' and it fixed my problem
