### ISSUE TITLE
OutOfMemoryError after a couple of hours running

### ISSUE THREAD

**Issue by txedo** [openzipkin/zipkin#1576]
I am getting OutOfMemoryErrors on my zipkin-server 1.23.2 with mysql storage configured. I haven't tried any other storage component. Here are some information and VisualVM screenshots I could gather.

![image](https://cloud.githubusercontent.com/assets/520328/25442385/32a895d6-2aa5-11e7-87bc-4ed30657c493.png)

![image](https://cloud.githubusercontent.com/assets/520328/25442456/63e4c6d8-2aa5-11e7-9a4f-24efcacc8a27.png)

`
"http-nio-9411-exec-17" daemon prio=5 tid=98 RUNNABLE
	at java.lang.OutOfMemoryError.<init>(OutOfMemoryError.java:48)
	at org.apache.commons.logging.impl.WeakHashtable$Referenced.<init>(WeakHashtable.java:406)
	   Local Variable: org.apache.commons.logging.impl.WeakHashtable$Referenced#1
	at org.apache.commons.logging.impl.WeakHashtable$Referenced.<init>(WeakHashtable.java:396)
	at org.apache.commons.logging.impl.WeakHashtable.get(WeakHashtable.java:181)
	   Local Variable: org.apache.commons.logging.impl.WeakHashtable#1
	at org.apache.commons.logging.LogFactory.getCachedFactory(LogFactory.java:923)
	at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:433)
	   Local Variable: org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader#1
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:657)
	   Local Variable: class org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottleAdapter
	at org.springframework.util.ConcurrencyThrottleSupport.<init>(ConcurrencyThrottleSupport.java:61)
	   Local Variable: org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottleAdapter#1
	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottleAdapter.<init>(SimpleAsyncTaskExecutor.java:239)
	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottleAdapter.<init>(SimpleAsyncTaskExecutor.java:239)
	at org.springframework.core.task.SimpleAsyncTaskExecutor.<init>(SimpleAsyncTaskExecutor.java:64)
	at org.springframework.web.context.request.async.WebAsyncManager.<init>(WebAsyncManager.java:75)
	   Local Variable: org.springframework.web.context.request.async.WebAsyncManager#12
	at org.springframework.web.context.request.async.WebAsyncUtils.getAsyncManager(WebAsyncUtils.java:49)
	at org.springframework.web.filter.OncePerRequestFilter.isAsyncDispatch(OncePerRequestFilter.java:137)
	at org.springframework.web.filter.OncePerRequestFilter.skipDispatch(OncePerRequestFilter.java:118)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:98)
	   Local Variable: java.lang.String#1232269
	   Local Variable: org.apache.catalina.connector.RequestFacade#7
	   Local Variable: org.apache.catalina.connector.ResponseFacade#7
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	   Local Variable: org.apache.catalina.core.ApplicationFilterChain#11
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	   Local Variable: org.apache.catalina.connector.Request#7
	   Local Variable: org.apache.coyote.Request#7
	   Local Variable: org.apache.coyote.Response#7
	   Local Variable: org.apache.catalina.connector.Response#7
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	   Local Variable: org.apache.coyote.RequestInfo#7
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	   Local Variable: org.apache.coyote.http11.Http11Processor#7
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	   Local Variable: org.apache.tomcat.util.net.NioChannel#19
	   Local Variable: sun.nio.ch.SelectionKeyImpl#7
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	   Local Variable: org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper#9
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	   Local Variable: org.apache.tomcat.util.net.NioEndpoint$SocketProcessor#15
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	   Local Variable: java.util.concurrent.ThreadPoolExecutor$Worker#1
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	   Local Variable: org.apache.tomcat.util.threads.TaskThread$WrappingRunnable#1
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by codefromthecrypt** [comment]
You can verify that it is indeed storing in MySQL by looking at the /health
endpoint. Also, maybe check /metrics to see if you are getting storage
errors?

**Comment by txedo** [comment]
Please find below the output of /heath endpoint. /metrics doesn't reveal any error either, and it is actually storing in MySQL.

`
{  
   status:"UP",
   zipkin:{  
      status:"UP",
      MySQLStorage:{  
         status:"UP"
      }
   },
   diskSpace:{  
      status:"UP",
      total:10432581632,
      free:8554635264,
      threshold:10485760
   }
}
`

Checking the start_ts column I have noticed that spans are inserted at time at the beginning but after some minutes running they are inserted with an increasing delay. Currently it is 12:20 AM and the most recent span inserted is from 09:38 AM, which could explain the increasing memory leading to the OutOfMemoryError after a couple of hours.

**Comment by txedo** [comment]
Right now, the latest timestamp showing up on /trace is 1493289153403, and the latest on mysql is 1493285896646000.

**Comment by codefromthecrypt** [comment]
ok if you have no errors and increasing memory it seems there is a queue backing up. you can look at threads to see if any are stuck. if pending spans are valuable you can add another zipkin server and stop routing traffic to the clogged one. otherwise bounce the clogged once you see which threads are stuck

**Comment by codefromthecrypt** [comment]
@shakuzen @devinsba @denyska so we seem to be accepting unbounded POSTs, and the memory eats up before the collector component gets involved (hence no drop metrics). wonder if theres a way to control in-flight accepts better..

**Comment by codefromthecrypt** [comment]
cc @dsyer @marcingrzejszczak I suspect there's a way to address this cheaply.. I think there's at least 2 paths

Currently ZipkinHttpCollector asks for buffered content like so..
```java
  @RequestMapping(value = "/api/v1/spans", method = POST)
  public ListenableFuture<ResponseEntity<?>> uploadSpansJson(
      @RequestHeader(value = "Content-Encoding", required = false) String encoding,
      @RequestBody byte[] body
  ) 
```
This is unzipped on the calling thread then plopped into a collector async.

There's a chance for us to drop instead of plop, if we know more about the queue. For example, an in-flight control could be made and if we have a fixed-length queue, we could drop and reply back with a try-later http code.

There's another issue which is that we are asking for byte[] as a parameter. This means that some layer before us is buffering, and before we even process a surge of writes could OOM things.

I think the most important and easiest thing would be to add an in-flight limit either here or in the MySQL impl (notably elasticsearch and cassandra already have in-flight limit). Other ideas welcome, too

**Comment by jorgheymans** [comment]
I have decided to close this issue, here's why
- MySQL is now considered a legacy storage option: `... no longer encouraged, but exist to help aid transition to supported ones. These are indicated as "v1" as they use data layouts based on Zipkin's V1 Thrift model, as opposed to the simpler v2 data model currently used.`
- The other comments about accepting unbounded POST requests and doing most of the request processing on the calling thread are no longer relevant since the switch to Armeria and most things are now being done asynchronous and reactive. For reference here is the current implementation of the collector doing the work: https://github.com/openzipkin/zipkin/blob/5a8b26c476bfe710410f1ddfc38105355f1a7560/zipkin-server/src/main/java/zipkin2/server/internal/ZipkinHttpCollector.java#L105

Anyone feeling the need to revamp the MySQL storage option and bring it in line with the ElasticSearch and Cassandra v2 data model features is more than welcome to do so. Please ping our gitter channel before embarking on this effort !
