### ISSUE TITLE
Zipkin server 1.26 with Elasticsearch on AWS returns 403 Forbidden

### ISSUE THREAD

**Issue by mclarke47** [openzipkin/zipkin#1605]
With the the image `docker.io/openzipkin/zipkin:latest` (currentlydocker.io/openzipkin/zipkin:1.26 ) with the parameters:
```
STORAGE_TYPE:    elasticsearch
ES_HOSTS:             https://my-domain.eu-west-1.es.amazonaws.com
```
Zipkin server cannot connect to elasticsearch and throws errors consistently. It was suggested the new elasticsearch logging could have interfered somehow.

```
2017-06-06 10:21:44.904  INFO 6 --- [azonaws.com/...] z.s.e.http.ElasticsearchHttpStorage      : --> GET https://my-domain.eu-west-1.es.amazonaws.com/ http/1.1
2017-06-06 10:21:45.316  INFO 6 --- [azonaws.com/...] z.s.e.http.ElasticsearchHttpStorage      : <-- 403 Forbidden https://my-domain.eu-west-1.es.amazonaws.com/ (411ms, 186-byte body)
Exception in thread "OkHttp Dispatcher" java.lang.IllegalStateException: Response{protocol=http/1.1, code=403, message=Forbidden, url=https://my-domain.eu-west-1.es.amazonaws.com/}
	at zipkin.autoconfigure.storage.elasticsearch.aws.AWSSignatureVersion4.intercept(AWSSignatureVersion4.java:71)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
(Actual es domain has obviously been redacted)

**Comment by codefromthecrypt** [comment]
ftr I recommended setting `ES_HTTP_LOGGING=BODY` next time this happens. That way we can see the error amazon sent with the 403. Sometimes that's telling.
