### ISSUE TITLE
Unauthenticated AWS Elasticsearch

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1607]
@mclarke47 noticed that our AWS ES always invokes the credentials chain. It is possible to setup ES in amazon w/o authentication (ex relying on IP/port filters instead). Implicitly authenticating can end up with 403s or errors looking up credentials locally.

```
Exception in thread "OkHttp Dispatcher" com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
	at zipkin.autoconfigure.storage.elasticsearch.aws.ZipkinElasticsearchAwsStorageAutoConfiguration$1.get(ZipkinElasticsearchAwsStorageAutoConfiguration.java:98)
	at zipkin.autoconfigure.storage.elasticsearch.aws.AWSSignatureVersion4.sign(AWSSignatureVersion4.java:132)
```

cc @devinsba

**Comment by devinsba** [comment]
I saw this when trying to test locally initially, our deployed instance uses its instance profile as its authentication though so I hadn't tried to dig any further. It would be nice to be able to use a real datastore for testing locally so I see the value here.

My initial thought was a flag for disabling (or defaulting to anonymous) the credentials providers. I saw you made the same suggestion in gitter so I'm on board there.

I'll have time to start on some stuff again next week but our quarter is winding down so I'm pretty tied up in my real work
