### ISSUE TITLE
Elasticsearch HTTP storage to support multiple SSL endpoints

### ISSUE THREAD

**Issue by ilutz** [openzipkin/zipkin#1611]
Consider support for client side load balancing between zipkin-storage-elasticsearch-http and elasticsearch instances which have SSL enabled.

**Comment by codefromthecrypt** [comment]
@swankjesse @jakewharton @brianm do y'all know of a friendly little library which lets you fan-out okhttp across multiple TLS connections such as you can with plain text connections by hacking okhttp3.Dns? I'm trying to not add many deps for our native Elasticsearch thing.

**Comment by codefromthecrypt** [comment]
fan-out is a poor choice of terms, I think transparent round-robin and fail-over is more precisely what's needed here.

**Comment by swankjesse** [comment]
So our ConnectionPool tries it's best to minimize the number of connections. This would create more?

**Comment by codefromthecrypt** [comment]
I guess what I mean is to have different TLS endpoints, like
https://foo.com https://bar.com
I suspect that the different TLS identities between foo.com and
bar.com would prevent me from using the dns trick.

**Comment by codefromthecrypt** [comment]
Wrote a failing test here #1682 cc @dgrabows who was most recently asking for this

**Comment by gquintana** [comment]
In the mean time, consider raising the log level of this trace from Debug to Error to help people understand what's wrong:
```
2019-03-18T10:12:41,155 DEBUG reporter.AsyncReporter$BoundedAsyncReporter - Dropped 0 spans due to IllegalArgumentException(Only http supported with multiple hosts [https://host1:9200, https://host2:9200, https://host3:9200])
java.lang.IllegalArgumentException: Only http supported with multiple hosts [https://host1:9200, https://host2:9200, https://host3:9200]
        at zipkin2.elasticsearch.PseudoAddressRecordSet.create(PseudoAddressRecordSet.java:66) ~[zipkin-storage-elasticsearch-2.12.5.jar!/:?]
        at zipkin2.elasticsearch.ElasticsearchStorage.http(ElasticsearchStorage.java:372) ~[zipkin-storage-elasticsearch-2.12.5.jar!/:?]
        at zipkin2.elasticsearch.AutoValue_ElasticsearchStorage.http(AutoValue_ElasticsearchStorage.java:46) ~[zipkin-storage-elasticsearch-2.12.5.jar!/:?]
        at zipkin2.elasticsearch.ElasticsearchStorage.ensureIndexTemplates(ElasticsearchStorage.java:350) ~[zipkin-storage-elasticsearch-2.12.5.jar!/:?]
        at zipkin2.elasticsearch.AutoValue_ElasticsearchStorage.ensureIndexTemplates(AutoValue_ElasticsearchStorage.java:31) ~[zipkin-storage-elasticsearch-2.12.5.jar!/:?]
        at zipkin2.elasticsearch.ElasticsearchStorage.spanConsumer(ElasticsearchStorage.java:260) ~[zipkin-storage-elasticsearch-2.12.5.jar!/:?]
        at zipkin2.server.internal.brave.TracingStorageComponent.spanConsumer(TracingStorageComponent.java:49) ~[classes!/:?]
        at zipkin2.storage.StorageComponent$$FastClassBySpringCGLIB$$37dbd580.invoke(<generated>) ~[zipkin-2.12.5.jar!/:?]
```

**Comment by gquintana** [comment]
About the question "which HTTP client library?". I suggest using the official Elasticsearch REST low level client
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-low.html
It supports HTTPS and is able to auto discover new nodes using Elasticsearch cluster API.

**Comment by codefromthecrypt** [comment]
> In the mean time, consider raising the log level of this trace from Debug to Error to help people understand what's wrong:

your comment was about the zipkin-reporter project, but I'll answer here. raising this to error will cause logs to fill in a high-throughput service. tracing shouldn't cause apps to crash which is why this is debug level. Other approaches are to monitor the dropped message count

**Comment by codefromthecrypt** [comment]
This is obviated because now we are using armeria for the client layer of elasticsearch. This is a lot more sophisticated internally with client-side health checking etc, and makes sense in this server as we are already using armeria inbound. you can try multiple TLS endpoints now on zipkin 2.16+

This doesn't change my love for okhttp: you can imagine this was mixed feelings for me as okhttp really changed my relationship with oss permanently. However, this decision was bigger than me, and armeria folks are are really capable and hearty bunch, too. We are lucky to be in a position where tech decisions are so hard. Anyway rambling over.. multiple TLS works out-of-box now.

**Comment by codefromthecrypt** [comment]
@gquintana  PS the problem you mentioned about log levels, while unrelated to this issue, is recently sorted in zipkin-reporter where we settled on a warn-once pattern
