### ISSUE TITLE
ES indexing breaks when a span name is json

### ISSUE THREAD

**Issue by tianmingxing** [openzipkin/zipkin#1613]
After testing I found only ES5.1.2 can, other high version simply can not be integrated. In other high-profile environment error.

**Comment by codefromthecrypt** [comment]
hmm can you be more specific on what error you are receiving?

**Comment by tianmingxing** [comment]
This seems to be caused by data structs (JSON) incompatibility, and specifically you need to troubleshoot.

# zipkin error

```
2017-06-14 11:05:14.525  WARN 3478 --- [.0.0.1:9200/...] zipkin.server.ZipkinHttpCollector        : Cannot store spans [e6eca7b6c5f8f339299570389c2a1d15.9a10745372015704<:aa2aecaf47f57f79, e6eca7b6c5f8f339299570389c2a1d15.d773c06755a69ebd<:aa2aecaf47f57f79, e6eca7b6c5f8f339299570389c2a1d15.aa2aecaf47f57f79<:aa2aecaf47f57f79] due to IllegalStateException(response failed: {"error":{"root_cause":[{"type":"json_parse_exception","reason":"Unexpected character ('n' (code 110)): was expecting comma to separate Object entries\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@7ef838ae; line: 1, column: 91]"}],"type":"json_parse_exception","reason":"Unexpected character ('n' (code 110)): was expecting comma to separate Object entries\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@7ef838ae; line:1, column: 91]"},"status":500})

java.lang.IllegalStateException: response failed: {"error":{"root_cause":[{"type":"json_parse_exception","reason":"Unexpected character ('n' (code 110)): was expecting comma to separate Object entries\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@7ef838ae; line: 1, column: 91]"}],"type":"json_parse_exception","reason":"Unexpected character ('n' (code 110)): was expecting comma to separate Object entries\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@7ef838ae; line: 1, column: 91]"},"status":500}
	at zipkin.storage.elasticsearch.http.internal.client.HttpCall$CallbackAdapter.onResponse(HttpCall.java:108) [zipkin-storage-elasticsearch-http-1.26.1-SNAPSHOT.jar!/:na]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) [okhttp-3.8.0.jar!/:na]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.8.0.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_77]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
```

# elasticsearch 5.4.1 error
```
[2017-06-14T11:05:14,286][WARN ][r.suppressed             ] path: /_bulk, params: {}
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('n' (code 110)): was expecting comma to separate Object entries
 at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@7ef838ae; line: 1, column: 91]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456) ~[jackson-core-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:761) ~[jackson-core-2.8.6.jar:2.8.6]
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:55) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.bulk.BulkRequest.add(BulkRequest.java:368) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.rest.action.document.RestBulkAction.prepareRequest(RestBulkAction.java:89) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:64) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:260) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:199) [elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:505) [transport-netty4-5.4.1.jar:5.4.1]
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:72) [transport-netty4-5.4.1.jar:5.4.1]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at org.elasticsearch.http.netty4.pipelining.HttpPipeliningHandler.channelRead(HttpPipeliningHandler.java:63) [transport-netty4-5.4.1.jar:5.4.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
[2017-06-14T11:05:15,513][WARN ][r.suppressed             ] path: /_bulk, params: {}
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('n' (code 110)): was expecting comma to separate Object entries
 at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@12ddb70a; line: 1, column: 91]

```

**Comment by codefromthecrypt** [comment]
hmm.. well indeed it is hard to promise forward compatibility when data formats change on a minor version!

5.3 was working, maybe this is something new in 5.4? cc @openzipkin/elasticsearch

**Comment by codefromthecrypt** [comment]
@xiaoxing598 how are you creating spans. can you create a failing test? (ex I can upgrade my ES to 5.4, but just in case it doesn't break)

**Comment by tianmingxing** [comment]
Sorry i do not quite understand what you need me to help? Please describe more clearly, I can meet you at the moment.

**Comment by codefromthecrypt** [comment]
@xiaoxing598 I ran our whole test suite against ES 5.4.1 and also an ad-hoc test as well.

How are you creating spans? Do you have sample JSON that causes this?

**Comment by codefromthecrypt** [comment]
I also added a unit test with newlines wondering if this was a cause, but it wasn't as it passed fine..

```java
 @Test
  public void dataIncludesNewlines() {
    Span withNewlines = span1.toBuilder()
      .addAnnotation(ann1.toBuilder().value("h\nello").build())
      .addBinaryAnnotation(BinaryAnnotation.create("hello", "w\norld", ep)).build();

    accept(withNewlines);

    assertThat(store().getTraces(QueryRequest.builder().build()))
      .flatExtracting(t -> t)
      .contains(withNewlines);
  }
```

**Comment by codefromthecrypt** [comment]
probably easiest way is to set `ES_HTTP_LOGGING=BODY` to get the json

**Comment by tianmingxing** [comment]
We mainly use the PHP language development, in the integration of Zipkin used a framework [whitemerry/phpkin](https://github.com/whitemerry/phpkin), now look like it is the reason?

**Comment by tianmingxing** [comment]
I see this frame on the official website, which is your recommended PHP framework, so I used it.

**Comment by codefromthecrypt** [comment]
>
> I see this frame on the official website, which is your recommended PHP
> framework, so I used it.
>
phpkin is under the community support section, and it is very new. The
author added it to the list, though there are other libraries, too
https://github.com/openzipkin/zipkin/issues/1330

Regardless, if you capture the http body we can tell for sure what is wrong.

**Comment by tianmingxing** [comment]
This is the frame to send data to Zipkin source code:

```php
    /**
     * @inheritdoc
     */
    public function trace($spans)
    {
        $contextOptions = [
            'http' => [
                'method' => 'POST',
                'header' => 'Content-type: application/json',
                'content' => json_encode($spans),
                'ignore_errors' => true
            ]
        ];
        $context = stream_context_create(array_merge_recursive($contextOptions, $this->options['contextOptions']));
        @file_get_contents($this->options['host'] . $this->options['endpoint'], false, $context);

        if (
            !$this->options['muteErrors']
            && (empty($http_response_header) || !$this->validResponse($http_response_header))
        ) {
            throw new LoggerException('Trace upload failed');
        }
    }
```

I recorded the contents of the transmission, and through the log output, hoping to help you diagnose the problem lies.

```
[
    {
        "id": "4ee9eb1aea216e0a",
        "traceId": "a530341daffb8e6d9a3d4d7a32f9b1e5",
        "name": "find({\"ns\":\"test.theme\",\"filter\":{\"_id\":\"MongoDB\\\\BSON\\\\ObjectID(5810690caee7c479be1c0082)\"},\"projection\":{\"_id\":null,\"images\":true,\"texts\":true}})",
        "timestamp": 1497492561507979,
        "duration": 32901,
        "annotations": [
            {
                "endpoint": {
                    "serviceName": "mongodb query",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561507979,
                "value": "cs"
            },
            {
                "endpoint": {
                    "serviceName": "mongodb query",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561540880,
                "value": "cr"
            }
        ],
        "parentId": "d5ab31886d28bb54"
    },
    {
        "id": "5e208e2ba87f4d41",
        "traceId": "a530341daffb8e6d9a3d4d7a32f9b1e5",
        "name": "test.event.bulkWrite([{\"type\":\"update\",\"condition\":{\"$and\":[{\"founder.id\":12035},{\"closeStatus\":\"\\u672a\\u5f00\\u59cb\"},{\"startTime\":{\"$lte\":1497492561}}]},\"document\":{\"$set\":{\"closeStatus\":\"\\u8fdb\\u884c\\u4e2d\"}},\"options\":{\"multi\":true,\"upsert\":false}}])",
        "timestamp": 1497492561549244,
        "duration": 1174,
        "annotations": [
            {
                "endpoint": {
                    "serviceName": "mongodb execute batch",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561549244,
                "value": "cs"
            },
            {
                "endpoint": {
                    "serviceName": "mongodb execute batch",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561550418,
                "value": "cr"
            }
        ],
        "parentId": "d5ab31886d28bb54"
    },
    {
        "id": "a3163671dd150df1",
        "traceId": "a530341daffb8e6d9a3d4d7a32f9b1e5",
        "name": "test.event.bulkWrite([{\"type\":\"update\",\"condition\":{\"$and\":[{\"founder.id\":12035},{\"closeStatus\":\"\\u8fdb\\u884c\\u4e2d\"},{\"endTime\":{\"$lte\":1497492561}}]},\"document\":{\"$set\":{\"closeStatus\":\"\\u5df2\\u7ed3\\u675f\"}},\"options\":{\"multi\":true,\"upsert\":false}}])",
        "timestamp": 1497492561550474,
        "duration": 638,
        "annotations": [
            {
                "endpoint": {
                    "serviceName": "mongodb execute batch",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561550474,
                "value": "cs"
            },
            {
                "endpoint": {
                    "serviceName": "mongodb execute batch",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561551112,
                "value": "cr"
            }
        ],
        "parentId": "d5ab31886d28bb54"
    },
    {
        "id": "f05f84dce91f83f0",
        "traceId": "a530341daffb8e6d9a3d4d7a32f9b1e5",
        "name": "test.command({\"count\":\"event\",\"query\":{\"founder.id\":12035,\"isDeleted\":0,\"themeId\":\"5810690caee7c479be1c0082\"}})",
        "timestamp": 1497492561551565,
        "duration": 1059,
        "annotations": [
            {
                "endpoint": {
                    "serviceName": "mongodb execute",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561551565,
                "value": "cs"
            },
            {
                "endpoint": {
                    "serviceName": "mongodb execute",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561552624,
                "value": "cr"
            }
        ],
        "parentId": "d5ab31886d28bb54"
    },
    {
        "id": "96e51c2ed5f20efa",
        "traceId": "a530341daffb8e6d9a3d4d7a32f9b1e5",
        "name": "find({\"ns\":\"test.event\",\"filter\":{\"founder.id\":12035,\"isDeleted\":0,\"themeId\":\"5810690caee7c479be1c0082\"},\"sort\":{\"createdTime\":-1},\"limit\":6,\"skip\":0,\"projection\":{\"_id\":true,\"name\":true,\"startTime\":true,\"endTime\":true,\"advancedSetting.keyword\":true,\"participants\":true,\"prizes\":true,\"closeStatus\":true}})",
        "timestamp": 1497492561552843,
        "duration": 1068,
        "annotations": [
            {
                "endpoint": {
                    "serviceName": "mongodb query",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561552843,
                "value": "cs"
            },
            {
                "endpoint": {
                    "serviceName": "mongodb query",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561553911,
                "value": "cr"
            }
        ],
        "parentId": "d5ab31886d28bb54"
    },
    {
        "id": "8a524be53cd3f4af",
        "traceId": "a530341daffb8e6d9a3d4d7a32f9b1e5",
        "name": "supplier/event-list",
        "timestamp": 1497492561543162,
        "duration": 10983,
        "annotations": [
            {
                "endpoint": {
                    "serviceName": "action",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561543162,
                "value": "cs"
            },
            {
                "endpoint": {
                    "serviceName": "action",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561554145,
                "value": "cr"
            }
        ],
        "parentId": "d5ab31886d28bb54"
    },
    {
        "id": "d5ab31886d28bb54",
        "traceId": "a530341daffb8e6d9a3d4d7a32f9b1e5",
        "name": "http://test.example.com/supplier/event-list?themeId=5810690caee7c479be1c0082themeId=5810690caee7c479be1c0082",
        "timestamp": 1497492561409431,
        "duration": 145031,
        "annotations": [
            {
                "endpoint": {
                    "serviceName": "xxx",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561409431,
                "value": "sr"
            },
            {
                "endpoint": {
                    "serviceName": "xxx",
                    "ipv4": "0.0.0.0",
                    "port": "80"
                },
                "timestamp": 1497492561554462,
                "value": "ss"
            }
        ]
    }
]
```

**Comment by codefromthecrypt** [comment]
hah.. so the tracer is sending json as a span name! that's probably what
the issue is. That's a bug in the tracer or how it is used. span names
should be low cardinality such as "event-list", not a json body.

**Comment by codefromthecrypt** [comment]
I think to make this easier to troubleshoot, we should probably escape
json in span names (in ES) for now. Otherwise it is hard for people to
troubleshoot. anyone think otherwise?

**Comment by codefromthecrypt** [comment]
so turns out that this isn't a problem specific to an ES version, as plopping in this integration test also breaks ES 2.x

```java
  @Test
  public void spanNameIsJson() {
    String json = "{\"foo\":\"bar\"}";
    Span withJsonSpanName = span1.toBuilder().name(json).build();

    accept(withJsonSpanName);

    assertThat(store().getTraces(QueryRequest.builder().spanName(json).build()))
      .flatExtracting(t -> t)
      .contains(withJsonSpanName);
  }
```

**Comment by codefromthecrypt** [comment]
it doesn't break on cassandra or mysql, so I think we can localize a fix

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1616 fixes this

**Comment by codefromthecrypt** [comment]
here's a follow-up on the overall problem of span data https://github.com/openzipkin/zipkin/issues/1617

**Comment by jcchavezs** [comment]
@xiaoxing598 I just published this library https://github.com/jcchavezs/zipkin-php which is V2 native and strongly inspired in brave. There is also [an example](https://github.com/openzipkin/zipkin-php-example) on how to use it.
