### ISSUE TITLE
Problem serializing zipkin2.Span type with Kryo

### ISSUE THREAD

**Issue by connectwithnara** [openzipkin/zipkin#1879]
Kryo doesn't support Google's AutoValue extensions that zipkin2.Span uses. 

So the following error is seen during serialization:
```
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException
Serialization trace:
annotations (zipkin2.AutoValue_Span)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
        at com.twitter.chill.TraversableSerializer.read(Traversable.scala:43)
        at com.twitter.chill.TraversableSerializer.read(Traversable.scala:21)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:657)
....
Caused by: java.lang.UnsupportedOperationException
        at java.util.Collections$UnmodifiableCollection.add(Collections.java:1055)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:116)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:22)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106)
```

Kryo version: 2.24.0

**Comment by codefromthecrypt** [comment]
ironic that com.twitter.chill is in that stack.. they need to show zipkin
some love!

**Comment by codefromthecrypt** [comment]
PS here's the related issue in kryo about auto-value https://github.com/magro/kryo-serializers/issues/48

**Comment by codefromthecrypt** [comment]
you sure this is kryo 2.24? that version is almost 4 years old

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1880
