### ISSUE TITLE
Need help zipkin use rabbitMQ exception

### ISSUE THREAD

**Issue by pickmonster** [openzipkin/zipkin#1881]
When i learn zipkin, i want use zipkin + RabbitMQ + Mysql, but i get one exception like this:

2018-01-15 14:49:07.592  INFO [microservice-zipkin-stream-server,,,] 13036 --- [           main] c.s.b.r.p.RabbitExchangeQueueProvisioner : declaring queue for inbound: sleuth.sleuth, bound to: sleuth
2018-01-15 14:49:12.689  WARN [microservice-zipkin-stream-server,,,] 13036 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : Failed to declare exchange: Exchange [name=sleuth, type=topic, durable=true, autoDelete=false, internal=false, arguments={}], continuing... org.springframework.amqp.AmqpTimeoutException: java.util.concurrent.TimeoutException
2018-01-15 14:49:12.693 ERROR [microservice-zipkin-stream-server,,,] 13036 --- [48.188.247:8080] c.r.c.impl.ForgivingExceptionHandler     : An unexpected connection driver error occured

java.net.SocketException: Socket Closed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_131]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_131]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_131]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_131]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_131]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[na:1.8.0_131]
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288) ~[na:1.8.0_131]
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91) ~[amqp-client-4.0.2.jar:4.0.2]
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164) ~[amqp-client-4.0.2.jar:4.0.2]
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:571) ~[amqp-client-4.0.2.jar:4.0.2]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
======================================================
#rabbitmq配置
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=15672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

**Comment by shakuzen** [comment]
It looks like you're trying to use a Spring Cloud Sleuth Stream Server. Zipkin has [native support for RabbitMQ as a collector](https://github.com/openzipkin/zipkin/tree/master/zipkin-collector/rabbitmq) now, so you can use it with the standard Zipkin server instead of making a custom one. It may be easier to diagnose this kind of issue via chat: feel free to join us on [Zipkin's Gitter](https://gitter.im/openzipkin/zipkin). That being said, it looks like there's connection trouble with your RabbitMQ.

**Comment by pickmonster** [comment]
@shakuzen Yes, i want use a Spring Cloud Sleuth Stream Server to synchronize request, and i set application like this:
@EnableZipkinStreamServer// //使用Stream方式启动ZipkinServer
@SpringBootApplication
public class ZipkinStreamServerApplication {
    public static void main(String[] args) {
        SpringApplication.run(ZipkinStreamServerApplication.class,args);
    }
}
============↓ this is my application.properties===========
server.port=11020
spring.application.name=microservice-zipkin-stream-server
spring.sleuth.enabled=false
zipkin.storage.type=mysql
spring.datasource.schema[0]=classpath:/zipkin.sql

why give me a exception?
