### ISSUE TITLE
ui: Buffer underflow

### ISSUE THREAD

**Issue by franklinhu** [openzipkin/zipkin#189]
```
FAT [20121023-18:33:11.993] ZipkinWeb: java.nio.BufferUnderflowException
FAT [20121023-18:33:11.993] ZipkinWeb:     at java.nio.Buffer.nextGetIndex(Buffer.java:498)
FAT [20121023-18:33:11.993] ZipkinWeb:     at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:355)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.zipkin.conversions.json$WrappedBinaryAnnotation.toJson(json.scala:19)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.zipkin.conversions.json$WrappedTraceTimeline$$anonfun$toJson$10.apply(json.scala:79)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.zipkin.conversions.json$WrappedTraceTimeline$$anonfun$toJson$10.apply(json.scala:79)
FAT [20121023-18:33:11.993] ZipkinWeb:     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
FAT [20121023-18:33:11.993] ZipkinWeb:     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
FAT [20121023-18:33:11.993] ZipkinWeb:     at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:60)
FAT [20121023-18:33:11.993] ZipkinWeb:     at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:44)
FAT [20121023-18:33:11.993] ZipkinWeb:     at scala.collection.TraversableLike$class.map(TraversableLike.scala:194)
FAT [20121023-18:33:11.993] ZipkinWeb:     at scala.collection.mutable.ArrayBuffer.map(ArrayBuffer.scala:44)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.zipkin.conversions.json$WrappedTraceTimeline.toJson(json.scala:79)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.zipkin.conversions.json$WrappedTraceCombo$$anonfun$toJson$12.apply(json.scala:95)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.zipkin.conversions.json$WrappedTraceCombo$$anonfun$toJson$12.apply(json.scala:95)
FAT [20121023-18:33:11.993] ZipkinWeb:     at scala.Option.map(Option.scala:133)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.zipkin.conversions.json$WrappedTraceCombo.toJson(json.scala:95)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.zipkin.web.App$$anonfun$12$$anonfun$apply$23.apply(App.scala:236)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.zipkin.web.App$$anonfun$12$$anonfun$apply$23.apply(App.scala:235)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$10.apply(Future.scala:503)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.util.Try$.apply(Try.scala:13)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.util.Future$.apply(Future.scala:98)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:503)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:503)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:477)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:476)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.util.Promise$$anonfun$transform$1.apply(Future.scala:883)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.util.Promise$$anonfun$transform$1.apply(Future.scala:879)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.util.Promise$$anonfun$respondWithoutChaining$1.apply(Future.scala:868)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.util.Promise$$anonfun$respondWithoutChaining$1.apply(Future.scala:863)
FAT [20121023-18:33:11.993] ZipkinWeb:     at com.twitter.concurrent.IVar$$anonfun$runqs$1.apply$mcV$sp(IVar.scala:174)
FAT [20121023-18:33:11.993] ZipkinWeb:     (...more...)
```

**Comment by eirslett** [comment]
Closing due to lack of activity.
