### ISSUE TITLE
kafka 10: GC overhead limit exceeded

### ISSUE THREAD

**Issue by DelayQueue** [openzipkin/zipkin#1986]
It's easy to show "GC overhead" in a production environment.

```
Exception in thread "http-nio-9411-ClientPoller-0" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1038)
	at org.apache.tomcat.util.net.NioEndpoint$Poller.timeout(NioEndpoint.java:1013)
	at org.apache.tomcat.util.net.NioEndpoint$Poller.run(NioEndpoint.java:833)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-1-thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at zipkin.internal.ThriftCodec$Field.read(ThriftCodec.java:619)
	at zipkin.internal.ThriftCodec$3.read(ThriftCodec.java:251)
	at zipkin.internal.ThriftCodec$3.read(ThriftCodec.java:239)
	at zipkin.internal.ThriftCodec$SpanReader.read(ThriftCodec.java:348)
	at zipkin.internal.ThriftCodec$SpanReader.read(ThriftCodec.java:300)
	at zipkin.internal.ThriftCodec.readList(ThriftCodec.java:560)
	at zipkin.internal.ThriftCodec.readSpans(ThriftCodec.java:88)
	at zipkin.collector.Collector.decodeList(Collector.java:152)
	at zipkin.collector.Collector.decodeList(Collector.java:41)
	at zipkin.internal.Collector.acceptSpans(Collector.java:57)
	at zipkin.collector.Collector.acceptSpans(Collector.java:114)
	at zipkin.collector.kafka10.KafkaCollectorWorker.run(KafkaCollectorWorker.java:89)
	at zipkin.collector.kafka10.KafkaCollector$LazyKafkaWorkers.lambda$guardFailures$0(KafkaCollector.java:195)
	at zipkin.collector.kafka10.KafkaCollector$LazyKafkaWorkers$$Lambda$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by codefromthecrypt** [comment]
wild guess is that your storage layer cannot keep up, causing a backlog on
the server. Could that be the case?

**Comment by DelayQueue** [comment]
Oh, yeah. Thanks for reminding me .  I use hbase to save data ,but hbase cannot keep up. Maybe I should modify AsyncSpanConsumer without thread pool.

**Comment by DelayQueue** [comment]
I add limitation to thread pool to avoid backlog. 
```
  ZipkinHbaseStorageAutoConfiguration
  @Bean
  @ConditionalOnMissingBean(Executor.class)
  Executor executor() {
    ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
    executor.setThreadNamePrefix("ZipkinHbaseStorage-");
    executor.setCorePoolSize(20); // add limitation
    executor.setMaxPoolSize(20); // add limitation
    executor.initialize();
    return executor.getThreadPoolExecutor();// change return value
  }
```

```
InternalBlockingToAsyncSpanConsumerAdapter
@Override public void accept(final List<Span> spans, Callback<Void> callback) {
    ThreadPoolExecutor t = (ThreadPoolExecutor) executor;
    while (t.getQueue().size() >= 20) { // add condition
      try {
        Thread.sleep(3000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
    }
    executor.execute(new InternalCallbackRunnable<Void>(callback) {
      @Override
      Void complete() {
        delegate.accept(spans);
        return null;
      }

      @Override
      public String toString() {
        return "Accept(" + spans + ")";
      }
    });
  }
```

**Comment by codefromthecrypt** [comment]
cool. glad you found a way to shed load
