### ISSUE TITLE
zipkin UI not load server_name

### ISSUE THREAD

**Issue by oneinstack** [openzipkin/zipkin#2000]
Hi:
Kafka cluster was designated when the root “/kafka”, elasticsearch Elasticsearch data has been written normally,however, Zipkin UI not load server_name
STORAGE_TYPE=elasticsearch
KAFKA_ZOOKEEPER=10.0.0.1:2181/kafka ,
ES_HOSTS=http://10.0.0.2:9200

error log:
```
2018-04-17 17:20:14.723  INFO [/] 35598 --- [  XNIO-2 task-5] backAsyncSpanStore$StringsDoubleCallback : first error

java.lang.IllegalStateException: over capacity
        at zipkin2.elasticsearch.internal.client.HttpCall.enqueue(HttpCall.java:87) [zipkin-storage-elasticsearch-2.7.1.jar!/:na]
        at zipkin.internal.V2SpanStoreAdapter.getServiceNames(V2SpanStoreAdapter.java:104) [io.zipkin.java-zipkin-2.7.1.jar!/:na]
        at zipkin.internal.LenientDoubleCallbackAsyncSpanStore.getServiceNames(LenientDoubleCallbackAsyncSpanStore.java:116) [io.zipkin.java-zipkin-2.7.1.jar!/:na]
        at zipkin.storage.InternalAsyncToBlockingSpanStoreAdapter.getServiceNames(InternalAsyncToBlockingSpanStoreAdapter.java:57) [io.zipkin.java-zipkin-2.7.1.jar!/:na]
        at zipkin.server.internal.ZipkinQueryApiV1.getServiceNames(ZipkinQueryApiV1.java:75) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
```

**Comment by codefromthecrypt** [comment]
all of your http connections are in use. Sometimes people have separate
servers for collector traffic vs UI.

ES_MAX_REQUESTS controls the amount for the current process

https://github.com/openzipkin/zipkin/tree/master/zipkin-server#elasticsearch-storage
