### ISSUE TITLE
NPE when running Zipkin in CF

### ISSUE THREAD

**Issue by marcingrzejszczak** [openzipkin/zipkin#2006]
when running Zipkin in CF I got such an interesting exception

```
 2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] Caused by: java.lang.NullPointerException: null
2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] at zipkin.internal.CorrectForClockSkew.adjustTimestamps(CorrectForClockSkew.java:182) ~[io.zipkin.java-zipkin-2.7.1.jar!/:na]
2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] at zipkin.internal.CorrectForClockSkew.adjust(CorrectForClockSkew.java:112) ~[io.zipkin.java-zipkin-2.7.1.jar!/:na]
2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] at zipkin.internal.CorrectForClockSkew.adjust(CorrectForClockSkew.java:128) ~[io.zipkin.java-zipkin-2.7.1.jar!/:na]
2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] at zipkin.internal.CorrectForClockSkew.apply(CorrectForClockSkew.java:97) ~[io.zipkin.java-zipkin-2.7.1.jar!/:na]
2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] at zipkin.internal.CorrectForClockSkew.apply(CorrectForClockSkew.java:51) ~[io.zipkin.java-zipkin-2.7.1.jar!/:na]
2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] at zipkin.internal.V2SpanStoreAdapter$GetTracesMapper.map(V2SpanStoreAdapter.java:173) ~[io.zipkin.java-zipkin-2.7.1.jar!/:na]
2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] at zipkin.internal.V2SpanStoreAdapter$GetTracesMapper.map(V2SpanStoreAdapter.java:165) ~[io.zipkin.java-zipkin-2.7.1.jar!/:na]
2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] at zipkin2.Call$Mapping.doExecute(Call.java:237) ~[io.zipkin.zipkin2-zipkin-2.7.1.jar!/:na]
2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] at zipkin2.Call$Base.execute(Call.java:379) ~[io.zipkin.zipkin2-zipkin-2.7.1.jar!/:na]
2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] at zipkin.internal.V2SpanStoreAdapter.getTraces(V2SpanStoreAdapter.java:44) ~[io.zipkin.java-zipkin-2.7.1.jar!/:na]
2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] at zipkin.server.internal.ZipkinQueryApiV1.getTraces(ZipkinQueryApiV1.java:106) ~[classes/:na]
2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[na:na]
2018-04-19T16:29:52.743+02:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
2018-04-19T16:29:52.744+02:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
2018-04-19T16:29:52.744+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
2018-04-19T16:29:52.744+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
2018-04-19T16:29:52.744+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
2018-04-19T16:29:52.744+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
2018-04-19T16:29:52.744+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
2018-04-19T16:29:52.744+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
2018-04-19T16:29:52.744+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
2018-04-19T16:29:52.744+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.14.RELEA
```

https://github.com/openzipkin/zipkin/blob/master/zipkin/src/main/java/zipkin/internal/CorrectForClockSkew.java#L182

```java
  // Search for a local span on the skewed endpoint
    for (int i = 0, length = span.binaryAnnotations.size(); i < length; i++) {
      BinaryAnnotation b = span.binaryAnnotations.get(i);
      if (b.endpoint == null) continue;
      if (b.key.equals(Constants.LOCAL_COMPONENT) && ipsMatch(skew.endpoint, b.endpoint)) {
        return span.toBuilder().timestamp(span.timestamp - skew.skew).build();
      }
    }
    return span;
```

a couple of NPEs possible here 

`return span.toBuilder().timestamp(span.timestamp - skew.skew).build();`

**Comment by codefromthecrypt** [comment]
thanks for the details!

**Comment by codefromthecrypt** [comment]
so it is odd that a local span would not have a timestamp.. that's what happened here. I will filter out so that bad data won't crash the ability to see things.

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/2009 should fix it
