### ISSUE TITLE
Errors thrown by InetAddress.getLocalHost

### ISSUE THREAD

**Issue by olix0r** [openzipkin/zipkin#203]
When running the web server locally, I encountered the following error:

```
[info] Running com.twitter.zipkin.web.Main -f zipkin-web/config/web-dev.scala
Nov 24, 2012 12:56:02 AM com.twitter.logging.Logger log
INFO: Loading configuration
Nov 24, 2012 12:56:02 AM java.util.logging.LogManager$RootLogger log
FATAL: Error in config file: %s
java.net.UnknownHostException: birderator: birderator
    at java.net.InetAddress.getLocalHost(InetAddress.java:1438)
    at com.twitter.zipkin.config.ZipkinConfig$class.$init$(ZipkinConfig.scala:30)
    at Evaluator__web$2ddev_16de0e15bca3885a651af7857b6a8434a7dbff86$$anon$1.<init>((inline):23)
    at Evaluator__web$2ddev_16de0e15bca3885a651af7857b6a8434a7dbff86.apply((inline):23)
    at Evaluator__web$2ddev_16de0e15bca3885a651af7857b6a8434a7dbff86.apply((inline):1)
    at com.twitter.util.Eval.applyProcessed(Eval.scala:197)
    at com.twitter.util.Eval.apply(Eval.scala:167)
    at com.twitter.ostrich.admin.RuntimeEnvironment.loadConfig(RuntimeEnvironment.scala:230)
    at com.twitter.ostrich.admin.RuntimeEnvironment.loadRuntimeConfig(RuntimeEnvironment.scala:256)
    at com.twitter.zipkin.web.Main$.main(Main.scala:28)
    at com.twitter.zipkin.web.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at sbt.Run.invokeMain(Run.scala:66)
    at sbt.Run.run0(Run.scala:59)
    at sbt.Run.execute$1(Run.scala:48)
    at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:52)
    at sbt.TrapExit$.executeMain$1(TrapExit.scala:33)
    at sbt.TrapExit$$anon$1.run(TrapExit.scala:42)
Caused by: java.net.UnknownHostException: birderator
    at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
    at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:866)
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1258)
    at java.net.InetAddress.getLocalHost(InetAddress.java:1434)
    ... 20 more
```

This is because [`InetAddress.getLocalHost` is not equivalent to `InetAddress.getHostByName("localhost")`](http://stackoverflow.com/a/1881967).  I have a small branch that resolves this issue by using `InetAddress.getHostByName("localhost")`

**Comment by mosesn** [comment]
Which version of java are you using?

**Comment by olix0r** [comment]
https://github.com/twitter/zipkin/tree/resolve-localhost

**Comment by olix0r** [comment]
```
 => java -version
java version "1.7.0_04"
Java(TM) SE Runtime Environment (build 1.7.0_04-b21)
Java HotSpot(TM) 64-Bit Server VM (build 23.0-b21, mixed mode)
```

**Comment by olix0r** [comment]
https://github.com/twitter/zipkin/pull/204
