### ISSUE TITLE
collector-rabbitmq start fails when the queue exists

### ISSUE THREAD

**Issue by ldcsaa** [openzipkin/zipkin#2068]
If rabbitmq queue exists and args of the queue not same as args of collector-rabbitmq default, zipkin server  would start fail .

exception file/line: 
---------------------
at zipkin.collector.rabbitmq.RabbitMQCollector$LazyInit.compute(RabbitMQCollector.java:141) ~[zipkin-collector-rabbitmq-2.8.4.jar!/:?]

stack trace:
---------------------
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'x-message-ttl'for queue 'queue.monitor.zipkin' in v
host 'monitor': received none but current is the value '36000000' of type 'long', class-id=50, method-id=10)
        at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66) ~[amqp-client-5.1.2.jar!/:5.1.2]
        at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36) ~[amqp-client-5.1.2.jar!/:5.1.2]
        at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:494) ~[amqp-client-5.1.2.jar!/:5.1.2]
        at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:288) ~[amqp-client-5.1.2.jar!/:5.1.2]
        at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:138) ~[amqp-client-5.1.2.jar!/:5.1.2]
        at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:947) ~[amqp-client-5.1.2.jar!/:5.1.2]
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.queueDeclare(AutorecoveringChannel.java:333) ~[amqp-client-5.1.2.jar!/:5.1.2]
        at zipkin.collector.rabbitmq.RabbitMQCollector$LazyInit.compute(RabbitMQCollector.java:141) ~[zipkin-collector-rabbitmq-2.8.4.jar!/:?]
        at zipkin.collector.rabbitmq.RabbitMQCollector$LazyInit.compute(RabbitMQCollector.java:128) ~[zipkin-collector-rabbitmq-2.8.4.jar!/:?]
        at zipkin.internal.LazyCloseable.tryCompute(LazyCloseable.java:51) ~[io.zipkin.java-zipkin-2.8.4.jar!/:?]
        at zipkin.internal.Lazy.get(Lazy.java:37) ~[io.zipkin.java-zipkin-2.8.4.jar!/:?]
        at zipkin.collector.rabbitmq.RabbitMQCollector.start(RabbitMQCollector.java:108) ~[zipkin-collector-rabbitmq-2.8.4.jar!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1831) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1774) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        ... 23 more

**Comment by codefromthecrypt** [comment]
Can you provide the parameters you are using? We aren't setting "x-message-ttl"
in our codebase (to none or anything else). Is this the standard build?

I wonder if in a unit test, we can define a queue with the ttl to reproduce
the error? cc @shakuzen

**Comment by ldcsaa** [comment]
PS: while zipkin server start, it will create a queue uses it's defaut args. so, conform the target queue is not exists (if exists delete it) ! and DO NOT start zipkin server. we create the queue use different args manually.

and now, start zipkin server, it would raise exception.
(I think, you should check if the queue exists before create it)

my args example:
--------------------------
Virtual host: monitor
Queue Name: queue.monitor.zipkin
Durability: true
Auto delete: false
arg "x-message-ttl": 36000000
arg "x-max-length": 1000000
arg "x-max-length-bytes": 300485760

my startup cmd:
---------------------------
java -jar zipkin-server-2.8.4-exec.jar -server -Xmx128m -Xms128m --management.endpoints.enabled-by-default=true --zipkin.collector.rabbitmq.uri=amqp://user_name:password@hostname:port/vhost --zipkin.collector.rabbitmq.queue=queue.monitor.zipkin --zipkin.collector.rabbitmq.connection-timeout=15000 --zipkin.collector.rabbitmq.concurrency=1

**Comment by shakuzen** [comment]
I have reproduce the issue. Indeed, we should check for an existing queue of the configured name and do nothing in that case.

**Comment by shakuzen** [comment]
@ldcsaa sorry for the long wait on this, but the bug should be fixed in the latest release (2.12.1). Let us know if you still have any issue with this.
