### ISSUE TITLE
ERROR: cannot load service names: Request processing failed; nested exception is java.lang.NullPointerException

### ISSUE THREAD

**Issue by alseddnm** [openzipkin/zipkin#2091]
Got Null pointer error in zipkin UI
Using Cassandra3
env we set are:
export CASSANDRA_USERNAME=???
export CASSANDRA_PASSWORD=???
export CASSANDRA_CONTACT_POINTS=???
export CASSANDRA_KEYSPACE=zipkin2
 export STORAGE_TYPE=cassandra3
**exception:**
```
2018-06-11 16:37:47.426 ERROR [/] 56622 --- [  XNIO-2 task-8] io.undertow.request                      : UT005023: Exception handling request to //api/v1/services

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982) ~[spring-webmvc-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
```

 **Stack trace:**

```
Caused by: java.lang.NullPointerException: null
	at zipkin2.storage.cassandra.CassandraSpanStore.<init>(CassandraSpanStore.java:64) ~[io.zipkin.zipkin2-zipkin-storage-cassandra-2.8.1.jar!/:na]
	at zipkin2.storage.cassandra.CassandraStorage.spanStore(CassandraStorage.java:168) ~[io.zipkin.zipkin2-zipkin-storage-cassandra-2.8.1.jar!/:na]
	at zipkin2.storage.cassandra.AutoValue_CassandraStorage.spanStore(AutoValue_CassandraStorage.java:47) ~[io.zipkin.zipkin2-zipkin-storage-cassandra-2.8.1.jar!/:na]
	at zipkin.internal.V2StorageComponent.spanStore(V2StorageComponent.java:65) ~[io.zipkin.java-zipkin-2.8.1.jar!/:na]
	at zipkin.server.internal.ZipkinQueryApiV1.getServiceNames(ZipkinQueryApiV1.java:75) ~[classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) ~[spring-webmvc-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) ~[spring-webmvc-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) ~[spring-webmvc-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
	... 83 common frames omitted
```

**Comment by alseddnm** [comment]
my bad ):- we did create `zipkin2-schema-indexes` closing..

**Comment by mahsaNajafzadeh** [comment]
I have the same issue, could you please explain how to fix it?

**Comment by codefromthecrypt** [comment]
@mahsaNajafzadeh can you try 2.12.1 as there was a similar bug recently fixed.
