### ISSUE TITLE
java.sql.BatchUpdateException: (conn=2359) unexpected end of stream, read 0 bytes from 4 

### ISSUE THREAD

**Issue by wxiaoqi** [openzipkin/zipkin#2119]
# Question Desc

I download the release jar to run on the server. Zipkin could not collect the trace data after one day. Then I see the log ，found the exception like this.

```
java.sql.BatchUpdateException: (conn=2359) unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:275) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.MariaDbStatement.executeBatch(MariaDbStatement.java:1252) ~[mariadb-java-client-2.2.3.jar!/:?]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) [HikariCP-2.7.9.jar!/:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java) [HikariCP-2.7.9.jar!/:?]
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:100) [jooq-3.10.7.jar!/:?]
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:100) [jooq-3.10.7.jar!/:?]
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:104) [jooq-3.10.7.jar!/:?]
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:75) [jooq-3.10.7.jar!/:?]
	at zipkin2.storage.mysql.v1.MySQLSpanConsumer$BatchInsertSpans.apply(MySQLSpanConsumer.java:167) [zipkin-storage-mysql-v1-2.9.1.jar!/:?]
	at zipkin2.storage.mysql.v1.MySQLSpanConsumer$BatchInsertSpans.apply(MySQLSpanConsumer.java:58) [zipkin-storage-mysql-v1-2.9.1.jar!/:?]
	at zipkin2.storage.mysql.v1.DataSourceCall.doExecute(DataSourceCall.java:57) [zipkin-storage-mysql-v1-2.9.1.jar!/:?]
	at zipkin2.storage.mysql.v1.DataSourceCall$1CallbackRunnable.run(DataSourceCall.java:69) [zipkin-storage-mysql-v1-2.9.1.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.sql.SQLNonTransientConnectionException: (conn=2359) unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:175) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:272) ~[mariadb-java-client-2.2.3.jar!/:?]
	... 14 more
Caused by: java.sql.SQLException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
Query is: insert into `zipkin_spans` (`trace_id`, `id`, `debug`, `start_ts`, `name`, `duration`) values (12971462161868237, 12971462161868237, null, 1530606474954000, 'http:/channel/prj/customerlist/201857', 54352) on duplicate key update `zipkin_spans`.`start_ts` = 1530606474954000, `zipkin_spans`.`name` = 'http:/channel/prj/customerlist/201857', `zipkin_spans`.`duration` = 54352
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:119) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:700) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:140) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67) ~[mariadb-java-client-2.2.3.jar!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	... 3 more
Caused by: java.io.EOFException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacketArray(StandardPacketInputStream.java:239) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacket(StandardPacketInputStream.java:207) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1347) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1328) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:137) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67) ~[mariadb-java-client-2.2.3.jar!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	... 3 more
```

# Hope 

So what can I do to fix this question.

**Comment by codefromthecrypt** [comment]
what is the type of server? mysql or mariadb and what version?

**Comment by codefromthecrypt** [comment]
this is related issue I guess

https://github.com/openzipkin/docker-zipkin/issues/181

**Comment by codefromthecrypt** [comment]
this will attempt to help https://github.com/openzipkin/zipkin/pull/2120

**Comment by wxiaoqi** [comment]
Mysql Server Verison: 5.5.5-10.0.0 2.1.2-maxscale

**Comment by codefromthecrypt** [comment]
please try version 2.10.0

**Comment by wxiaoqi** [comment]
2018-07-05 08:02:15.082  WARN 8 --- [nMySQLStorage-1] c.z.h.p.ProxyConnection                  : HikariPool-1 - Connection org.mariadb.jdbc.MariaDbConnection@4fdfcf0d marked as broken because of SQLSTATE(08), ErrorCode(0)

java.sql.BatchUpdateException: (conn=2496) unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:275) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.MariaDbStatement.executeBatch(MariaDbStatement.java:1252) ~[mariadb-java-client-2.2.3.jar!/:?]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) [HikariCP-2.7.9.jar!/:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java) [HikariCP-2.7.9.jar!/:?]
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:100) [jooq-3.10.7.jar!/:?]
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:100) [jooq-3.10.7.jar!/:?]
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:104) [jooq-3.10.7.jar!/:?]
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:75) [jooq-3.10.7.jar!/:?]
	at zipkin2.storage.mysql.v1.MySQLSpanConsumer$BatchInsertSpans.apply(MySQLSpanConsumer.java:167) [zipkin-storage-mysql-v1-2.9.4.jar!/:?]
	at zipkin2.storage.mysql.v1.MySQLSpanConsumer$BatchInsertSpans.apply(MySQLSpanConsumer.java:58) [zipkin-storage-mysql-v1-2.9.4.jar!/:?]
	at zipkin2.storage.mysql.v1.DataSourceCall.doExecute(DataSourceCall.java:57) [zipkin-storage-mysql-v1-2.9.4.jar!/:?]
	at zipkin2.storage.mysql.v1.DataSourceCall$1CallbackRunnable.run(DataSourceCall.java:69) [zipkin-storage-mysql-v1-2.9.4.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.sql.SQLNonTransientConnectionException: (conn=2496) unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:175) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:272) ~[mariadb-java-client-2.2.3.jar!/:?]
	... 14 more
Caused by: java.sql.SQLException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
Query is: insert ignore into `zipkin_annotations` (`trace_id`, `span_id`, `a_key`, `a_type`, `a_timestamp`, `a_value`, `endpoint_service_name`, `endpoint_ipv4`, `endpoint_port`) values (-3183468888124600236, -3183468888124600236, 'lc', 6, 1530691923265000, X'68797374726978', 'cplm-object', 168431254, -532)
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:119) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$2.handleResultException(AbstractQueryProtocol.java:700) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:140) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67) ~[mariadb-java-client-2.2.3.jar!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	... 3 more
Caused by: java.io.EOFException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacketArray(StandardPacketInputStream.java:239) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacket(StandardPacketInputStream.java:207) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1347) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1328) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:137) ~[mariadb-java-client-2.2.3.jar!/:?]
	at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:67) ~[mariadb-java-client-2.2.3.jar!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	... 3 more

**Comment by codefromthecrypt** [comment]
could you have similar problem to https://github.com/openzipkin/docker-zipkin/issues/181?
