### ISSUE TITLE
the doc has wrong info.  Kafka 0.10+ Collector Auto-configure Module

### ISSUE THREAD

**Issue by 0xsimonchung** [openzipkin/zipkin#2140]
- [x] issue. 
this link does not contained available jar file for java.  doc link https://github.com/openzipkin/zipkin/tree/2.4.6/zipkin-autoconfigure/collector-kafka10
```
curl -sSL https://zipkin.io/quickstart.sh | bash -s io.zipkin.java:zipkin-autoconfigure-collector-kafka10:LATEST:module kafka10.jar 
```

when use command to start it appear fail.
```
$ KAFKA_BOOTSTRAP_SERVERS=127.0.0.1:9092 \
    java \
    -Dloader.path='kafka10.jar,kafka10.jar!/lib' \
    -Dspring.profiles.active=kafka \
    -cp zipkin.jar \
    org.springframework.boot.loader.PropertiesLauncher


Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:115)
	at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:109)
	at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:95)
	at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:86)
	at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:60)
	at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:56)
	at org.springframework.boot.loader.PropertiesLauncher.getArchive(PropertiesLauncher.java:500)
	at org.springframework.boot.loader.PropertiesLauncher.getClassPathArchives(PropertiesLauncher.java:476)
	at org.springframework.boot.loader.PropertiesLauncher.getClassPathArchives(PropertiesLauncher.java:446)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
```

**Comment by codefromthecrypt** [comment]
kafka 1.0 is in the default jar now. Notes here, but 2.10.2 is the latest
version https://github.com/openzipkin/zipkin/releases/tag/2.9.4

**Comment by 0xsimonchung** [comment]
thank you, i use the command to run it success. 
KAFKA_BOOTSTRAP_SERVERS=127.0.0.1:9092  java -jar zipkin.jar

**Comment by 0xsimonchung** [comment]
but the document also confused me.

**Comment by codefromthecrypt** [comment]
the document pointed to is not the current version of zipkin. If you are
having trouble connecting to kafka, this might also help:

https://github.com/openzipkin/sleuth-webmvc-example/pull/8

regardless, this seems a more troubleshooting question. please use gitter
for more follow-up https://gitter.im/openzipkin/zipkin

**Comment by 0xsimonchung** [comment]
thank you very much, you are so nice.

**Comment by codefromthecrypt** [comment]
no problem!
