### ISSUE TITLE
New annotation_query index breaks cqlsh

### ISSUE THREAD

**Issue by drolando** [openzipkin/zipkin#2163]
I'm not sure whether this issue belongs here or in Cassandra itself, however it might stil be useful as reference.

After upgrading to Cassandra 3.11.3 and creating the new annotation_query index, `DESCRIBE KEYSPACE zipkin2` fails with `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 111: ordinal not in range(128)`. Setting `--encoding=utf-8` doesn't help.

The issue seems to be the same as https://issues.apache.org/jira/browse/CASSANDRA-10875, which should theoretically already be fixed.

cc @michaelsembwever

**Comment by amitskatti** [comment]
The traceback we see is:
```
[cqlsh 5.0.1 | Cassandra 3.11.1 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cqlsh> desc KEYSPACE zipkin2;

Traceback (most recent call last):
  File "/usr/bin/cqlsh.py", line 919, in onecmd
    self.handle_statement(st, statementtext)
  File "/usr/bin/cqlsh.py", line 956, in handle_statement
    return custom_handler(parsed)
  File "/usr/bin/cqlsh.py", line 1539, in do_describe
    self.describe_keyspace(ksname)
  File "/usr/bin/cqlsh.py", line 1275, in describe_keyspace
    self.print_recreate_keyspace(self.get_keyspace_meta(ksname), sys.stdout)
  File "/usr/bin/cqlsh.py", line 1225, in print_recreate_keyspace
    out.write(ksdef.export_as_string())
  File "/usr/share/cassandra/lib/cassandra-driver-internal-only-3.10.zip/cassandra-driver-3.10/cassandra/metadata.py", line 661, in export_as_string
    + [t.export_as_string() for t in self.tables.values()])
  File "/usr/share/cassandra/lib/cassandra-driver-internal-only-3.10.zip/cassandra-driver-3.10/cassandra/metadata.py", line 1116, in export_as_string
    ret = self._all_as_cql()
  File "/usr/share/cassandra/lib/cassandra-driver-internal-only-3.10.zip/cassandra-driver-3.10/cassandra/metadata.py", line 1125, in _all_as_cql
    ret += "\n%s;" % index.as_cql_query()
  File "/usr/share/cassandra/lib/cassandra-driver-internal-only-3.10.zip/cassandra-driver-3.10/cassandra/metadata.py", line 1402, in as_cql_query
    ret += " WITH OPTIONS = %s" % Encoder().cql_encode_all_types(options)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 111: ordinal not in range(128)
```

**Comment by michaelsembwever** [comment]
It can be narrowed to `DESCRIBE TABLE zipkin2.span;`

Mostly likely related to the unicode character [here](https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/cassandra/src/main/resources/zipkin2-schema-indexes.cql#L43) used in the SASI. (Confirmed: if the delimiter is changed to any ascii character then cqlsh is happy to describe the span table.)

@drolando and @amitskatti I'm presuming that Zipkin otherwise is working fine for you?

**Comment by michaelsembwever** [comment]
It's a bug in https://github.com/datastax/python-driver
 in that in `metadata.py` is trying to unpack the options (to the custom index) without ever first explicitly setting it to unicode, eg `.encode('utf-8')`

(for example the different between calling `encoder.cql_encode_object(..)` and `encoder.cql_encode_unicode(..)`)

**Comment by michaelsembwever** [comment]
have filed an upstream ticket: https://issues.apache.org/jira/browse/CASSANDRA-14632

**Comment by drolando** [comment]
@michaelsembwever hey! Do you know if this will be fixed in cassandra 4.0?
