### ISSUE TITLE
zipkin2(latest) with elasticserch（5.6.12） and query error

### ISSUE THREAD

**Issue by huhu-sky** [openzipkin/zipkin#2343]
## Describe the Bug
I debug the zipkin2 and use es as the storage. when query, it's error, below is the stacetrace:
~~~
Caused by: java.lang.IllegalStateException: response for aggregation failed: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [traceId] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"zipkin:span-2019-01-04","node":"lb6DkKBATYuoy2rBOsWw5w","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [traceId] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}]},"status":400}
	at zipkin2.elasticsearch.internal.client.HttpCall.parseResponse(HttpCall.java:151) ~[classes/:?]
	at zipkin2.elasticsearch.internal.client.HttpCall.execute(HttpCall.java:79) ~[classes/:?]
	at zipkin2.Call$FlatMapping.doExecute(Call.java:276) ~[classes/:?]
	at zipkin2.Call$Base.execute(Call.java:379) ~[classes/:?]
	at zipkin2.Call$Mapping.doExecute(Call.java:237) ~[classes/:?]
	at zipkin2.Call$Base.execute(Call.java:379) ~[classes/:?]
	at zipkin2.Call$Mapping.doExecute(Call.java:237) ~[classes/:?]
	at zipkin2.Call$Base.execute(Call.java:379) ~[classes/:?]
	at zipkin2.server.internal.ZipkinQueryApiV2.getTraces(ZipkinQueryApiV2.java:123) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	... 84 more
~~~

## Steps to Reproduce
use two zipkin-demo to produce the data and use the /zipkin/api/v2/traces  api to query

## Expected Behaviour

**Comment by codefromthecrypt** [comment]
the following type definitely should not be from classes:

```
    at zipkin2.elasticsearch.internal.client.HttpCall.execute(HttpCall.java:79) ~[classes/:?]
```

ex if it was the normal build it would come from the a jar like this:

```
    at zipkin2.elasticsearch.internal.client.HttpCall.execute(HttpCall.java:79) ~[zipkin-storage-elasticsearch-2.11.12.jar!/:?]
```

Please use the default server from https://github.com/openzipkin/zipkin#quick-start or if for some reason that doesn't work, normal maven central like https://search.maven.org/remotecontent?filepath=io/zipkin/java/zipkin-server/2.11.12/zipkin-server-2.11.12-exec.jar

if you still have problems, please continue support on gitter. good luck!

**Comment by huhu-sky** [comment]
### sorry for late answering.
@adriancole  i use image from docker docker.io/openzipkin/zipkin:latest and i have the same error. below is the stacktrace!
~~~
Caused by: java.lang.IllegalStateException: response for aggregation failed: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"zipkin:span-2019-01-04","node":"lb6DkKBATYuoy2rBOsWw5w","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}]},"status":400}
    at zipkin2.elasticsearch.internal.client.HttpCall.parseResponse(HttpCall.java:151) ~[zipkin-storage-elasticsearch-2.11.12.jar!/:?]
    at zipkin2.elasticsearch.internal.client.HttpCall.execute(HttpCall.java:79) ~[zipkin-storage-elasticsearch-2.11.12.jar!/:?]
    at zipkin2.server.internal.ZipkinQueryApiV2.getSpanNames(ZipkinQueryApiV2.java:93) ~[classes/:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    ... 84 more
~~~
~~~
docker run -d -p 9611:9411  -p 9610:9410  -e STORAGE_TYPE=elasticsearch -e ES_HOSTS=http://192.168.0.29:9200 -e RABBIT_ADDRESSES=192.168.0.29:5672 --name zipkin-server-es docker.io/openzipkin/zipkin
~~~
~~~
STORAGE_TYPE=elasticsearch ES_HOSTS=http://192.168.0.29:9200 RABBIT_ADDRESSES=192.168.0.29:5672 java -jar zipkin-server-2.11.12-exec.jar
~~~

**Comment by codefromthecrypt** [comment]
As mentioned on gitter, only guess is there is an invalid index template
which is stopping the code from automatically making the new one. Here's
notes from there, but let's keep this troubleshooting in gitter not github
issue, as github issues spam a lot of people.

the server at startup does a "_template" GET request to see if there's a
template available and failing that installs one

you could increase logging to see if it is creating the wrong one..
ES_HTTP_LOGGING=BODY
https://github.com/openzipkin/zipkin/tree/master/zipkin-server#elasticsearch-storage
