### ISSUE TITLE
Zipkin Elasticsearch storage fails to put index templates

### ISSUE THREAD

**Issue by gquintana** [openzipkin/zipkin#2367]
## Describe the Bug
Starting Zipkin with Elasticsearch Storage and Elasticsearch 6.5.4

## Steps to Reproduce

Start Zipkin v2.12.0 with Elasticsearch 6.5.4 as storage. There is a problem during index template configuration:
```
2019-01-28 15:47:17.210 DEBUG 412 --- [pool-2-thread-1] z.c.k.KafkaCollector                     : Cannot store spans [02a7641b97d0a41e/8fcbe13bb5f55469] due to IllegalStateException(response for update-template failed: {"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to parse content to map"}],"type":"parse_exception","reason":"Failed to parse content to map","caused_by":{"type":"json_parse_exception","reason":"Unexpected character ('z' (code 122)): was expecting comma to separate Object entries\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@676d081c; line: 2, column: 24]"}},"status":400})

java.lang.IllegalStateException: response for update-template failed: {"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to parse content to map"}],"type":"parse_exception","reason":"Failed to parse content to map","caused_by":{"type":"json_parse_exception","reason":"Unexpected character ('z' (code 122)): was expecting comma to separate Object entries\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@676d081c; line: 2, column: 24]"}},"status":400}
        at zipkin2.elasticsearch.internal.client.HttpCall.parseResponse(HttpCall.java:151) ~[zipkin-storage-elasticsearch-2.12.0.jar!/:?]
        at zipkin2.elasticsearch.internal.client.HttpCall.execute(HttpCall.java:79) ~[zipkin-storage-elasticsearch-2.12.0.jar!/:?]
        at zipkin2.elasticsearch.EnsureIndexTemplate.apply(EnsureIndexTemplate.java:42) ~[zipkin-storage-elasticsearch-2.12.0.jar!/:?]
        at zipkin2.elasticsearch.ElasticsearchStorage.ensureIndexTemplates(ElasticsearchStorage.java:351) ~[zipkin-storage-elasticsearch-2.12.0.jar!/:?]
        at zipkin2.elasticsearch.AutoValue_ElasticsearchStorage.ensureIndexTemplates(AutoValue_ElasticsearchStorage.java:31) ~[zipkin-storage-elasticsearch-2.12.0.jar!/:?]
        at zipkin2.elasticsearch.ElasticsearchStorage.spanConsumer(ElasticsearchStorage.java:260) ~[zipkin-storage-elasticsearch-2.12.0.jar!/:?]
        at zipkin2.collector.Collector.record(Collector.java:150) ~[zipkin-collector-2.12.0.jar!/:?]
        at zipkin2.collector.Collector.accept(Collector.java:110) ~[zipkin-collector-2.12.0.jar!/:?]
        at zipkin2.collector.Collector.acceptSpans(Collector.java:140) ~[zipkin-collector-2.12.0.jar!/:?]
        at zipkin2.collector.Collector.acceptSpans(Collector.java:127) ~[zipkin-collector-2.12.0.jar!/:?]
        at zipkin2.collector.kafka.KafkaCollectorWorker.run(KafkaCollectorWorker.java:101) ~[zipkin-collector-kafka-2.12.0.jar!/:?]
        at zipkin2.collector.kafka.KafkaCollector$LazyKafkaWorkers.lambda$guardFailures$0(KafkaCollector.java:252) ~[zipkin-collector-kafka-2.12.0.jar!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

## Expected Behaviour
Index templates properly configured

**Comment by gquintana** [comment]
Also occurs in UI:
```
Caused by: java.lang.IllegalStateException: response for update-template failed: {"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to parse content to map"}],"type":"parse_exception","reason":"Failed to parse content to map","caused_by":{"type":"json_parse_exception","reason":"Unexpected character ('z' (code 122)): was expecting comma to separate Object entries\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@6ffd0b34; line: 2, column: 24]"}},"status":400}
        at zipkin2.elasticsearch.internal.client.HttpCall.parseResponse(HttpCall.java:151) ~[zipkin-storage-elasticsearch-2.12.0.jar!/:?]
        at zipkin2.elasticsearch.internal.client.HttpCall.execute(HttpCall.java:79) ~[zipkin-storage-elasticsearch-2.12.0.jar!/:?]
        at zipkin2.elasticsearch.EnsureIndexTemplate.apply(EnsureIndexTemplate.java:42) ~[zipkin-storage-elasticsearch-2.12.0.jar!/:?]
        at zipkin2.elasticsearch.ElasticsearchStorage.ensureIndexTemplates(ElasticsearchStorage.java:351) ~[zipkin-storage-elasticsearch-2.12.0.jar!/:?]
        at zipkin2.elasticsearch.AutoValue_ElasticsearchStorage.ensureIndexTemplates(AutoValue_ElasticsearchStorage.java:31) ~[zipkin-storage-elasticsearch-2.12.0.jar!/:?]
        at zipkin2.elasticsearch.ElasticsearchStorage.spanStore(ElasticsearchStorage.java:248) ~[zipkin-storage-elasticsearch-2.12.0.jar!/:?]
        at zipkin2.server.internal.ZipkinQueryApiV2.getServiceNames(ZipkinQueryApiV2.java:89) ~[classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        ... 84 more
```

**Comment by gquintana** [comment]
It was not a bug, I had a double quote in ES_INDEX environment variable, as a result JSON to Elasticsearch was invalid.
