### ISSUE TITLE
is support finagle 6.3 & scala 2.10?

### ISSUE THREAD

**Issue by roymax** [openzipkin/zipkin#241]
my demo project under finagle 6.3 & scala 2.10, i try connect zipkin but get IncompatibleClassChangeError

here is my code

```
class AskServiceConfig extends ServerConfig[AskService.ThriftServer] {

 var tracerFactory: Tracer.Factory = ZipkinTracer.apply(scribeHost = "127.0.0.1", scribePort = 9410, sampleRate = 1.0f )
```

```
FAT [20130415-09:27:00.076] Ask: A server service  threw an exception
FAT [20130415-09:27:00.076] Ask: java.lang.IncompatibleClassChangeError: Implementing class
FAT [20130415-09:27:00.076] Ask:     at java.lang.ClassLoader.defineClass1(Native Method)
FAT [20130415-09:27:00.076] Ask:     at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
FAT [20130415-09:27:00.076] Ask:     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
FAT [20130415-09:27:00.076] Ask:     at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
FAT [20130415-09:27:00.076] Ask:     at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
FAT [20130415-09:27:00.076] Ask:     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
FAT [20130415-09:27:00.076] Ask:     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
FAT [20130415-09:27:00.076] Ask:     at java.security.AccessController.doPrivileged(Native Method)
FAT [20130415-09:27:00.076] Ask:     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
FAT [20130415-09:27:00.076] Ask:     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
FAT [20130415-09:27:00.076] Ask:     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.finagle.zipkin.thrift.scribe$log_args.write(scribe.scala:203)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.scrooge.FinagleThriftClient$$anonfun$encodeRequest$1.apply(FinagleThriftClient.scala:27)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.scrooge.FinagleThriftClient$$anonfun$encodeRequest$1.apply(FinagleThriftClient.scala:22)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.util.Try$.apply(Try.scala:13)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.util.Future$.apply(Future.scala:56)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.scrooge.FinagleThriftClient$class.encodeRequest(FinagleThriftClient.scala:22)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.finagle.zipkin.thrift.scribe$FinagledClient.encodeRequest(scribe.scala:290)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.finagle.zipkin.thrift.scribe$FinagledClient.log(scribe.scala:305)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.finagle.zipkin.thrift.RawZipkinTracer.logSpan(RawZipkinTracer.scala:123)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.finagle.zipkin.thrift.RawZipkinTracer.mutate(RawZipkinTracer.scala:145)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.finagle.zipkin.thrift.RawZipkinTracer.annotate(RawZipkinTracer.scala:217)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.finagle.zipkin.thrift.RawZipkinTracer.record(RawZipkinTracer.scala:156)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.finagle.zipkin.thrift.ZipkinTracer.record(ZipkinTracer.scala:79)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.finagle.tracing.Trace$$anonfun$record$1.apply(Trace.scala:192)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.finagle.tracing.Trace$$anonfun$record$1.apply(Trace.scala:192)
FAT [20130415-09:27:00.076] Ask:     at scala.collection.immutable.Set$Set1.foreach(Set.scala:86)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.finagle.tracing.Trace$.record(Trace.scala:192)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.finagle.tracing.Trace$.record(Trace.scala:224)
FAT [20130415-09:27:00.076] Ask:     at com.twitter.finagle.thrift.ThriftServerTracingFilter$$anonfun$apply$2$$anonfun$apply$3.apply(ThriftServerFramedCodec.scala:173)
FAT [20130415-09:27:00.076] Ask:     (...more...)

```

**Comment by bmdhacks** [comment]
Finagle 6.4 now has scala 2.10 artifacts, so this should be working now.
