### ISSUE TITLE
Running as ecs container on aws

### ISSUE THREAD

**Issue by musabqamri123** [openzipkin/zipkin#2420]
Unable to run it on AWS, fails with following exception 

Looks like need to enable ALLOW_UNESCAPED_CHARACTERS_IN_URL . But it cannot be passed as vm argument

14:41:59
2019-02-28 14:41:59.117 DEBUG 1 --- [ XNIO-1 I/O-1] i.u.r.io : UT005014: Failed to parse request

14:41:59
io.undertow.util.BadRequestException: null

14:41:59
at io.undertow.server.protocol.http.HttpRequestParser$$generated.handleHttpVerb(Unknown Source) ~[undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:41:59
at io.undertow.server.protocol.http.HttpRequestParser.handle(HttpRequestParser.java:243) ~[undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:41:59
at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:187) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:41:59
at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:41:59
at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:41:59
at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:41:59
at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:41:59
at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

14:41:59
at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

14:41:59
at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

14:41:59
at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

14:41:59
at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:131) [xnio-nio-3.7.0.Final.jar!/:3.7.0.Final]

14:41:59
at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612) [xnio-nio-3.7.0.Final.jar!/:3.7.0.Final]

14:41:59
at org.xnio.nio.WorkerThread.run(WorkerThread.java:479) [xnio-nio-3.7.0.Final.jar!/:3.7.0.Final]

**Comment by musabqamri123** [comment]
Running it on AWS fargate... i guess request is sent by AWS ELB for health check or so....

**Comment by codefromthecrypt** [comment]
do you know what request creates this?

Here is the associated doc.. https://github.com/undertow-io/undertow/commit/d63b767010133d574196740892a845c1375e8bed

**Comment by codefromthecrypt** [comment]
this looks like more about query parameters. will raise a fix

**Comment by codefromthecrypt** [comment]
#2422 should fix this.. I tested manually

```bash
$ java -jar ./zipkin-server/target/zipkin-server-*exec.jar --logging.level.io.undertow=trace
```

```bash
$ curl -s localhost:9411/api/v2/traces?serviceName=bÃ¥r -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9411 (#0)
> GET /api/v2/traces?serviceName=bÃ¥r HTTP/1.1
> Host: localhost:9411
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: keep-alive
< vary: origin
< Content-Type: application/json;charset=UTF-8
< Content-Length: 2
< Date: Fri, 01 Mar 2019 04:06:16 GMT
< 
* Connection #0 to host localhost left intact
[]
```

**Comment by musabqamri123** [comment]
Looks like its part of undertow 2.0.19 
[undertow-io/undertow@d63b767](https://github.com/undertow-io/undertow/commit/d63b767010133d574196740892a845c1375e8bed)

and the undertow version which ships with spring-boot 2.1.3 is 2.0.17
![image](https://user-images.githubusercontent.com/20564174/53623017-c187ca80-3c21-11e9-8064-610691a1bfbc.png)

**Comment by musabqamri123** [comment]
io.undertow.util.BadRequestException: java.lang.IllegalArgumentException: Invalid string contents ﾣﾟTﾬﾶￌ/b�ﾗ￘ￔNrﾝ￭UVￓ^￈z%ﾒ>l9ﾶ

**Comment by codefromthecrypt** [comment]
can you please send the command that is creating that error? The code
mention exists in 2.0.19.Final, but also many versions prior.

If you run with `java -jar
./zipkin-server/target/zipkin-server-*exec.jar
--logging.level.io.undertow=trace` it will show the request info
leading to that error.

Make sure you are building locally or the latest exec jar from here
http://oss.jfrog.org/oss-snapshot-local/io/zipkin/java/zipkin-server/2.12.3-SNAPSHOT/

**Comment by musabqamri123** [comment]
Looks like undertow issue for unicode.
Sorry its not related to version.

Let me know if you have any solution for this

**Comment by musabqamri123** [comment]
I am running it as a docker container on aws.. locally its running fine..

i am running with following command .. which enable TRACE for undertow but the request content is not getting printed in logs 


14:07:40
2019-03-01 14:07:40.639 **TRACE** 1 --- [ XNIO-2 I/O-1] i.u.request : Opened connection with /10.202.20.152:18256

14:07:40
2019-03-01 14:07:40.640 DEBUG 1 --- [ XNIO-2 I/O-1] i.u.r.io : UT005014: Failed to parse request

14:07:40
io.undertow.util.BadRequestException: null

14:07:40
at io.undertow.server.protocol.http.HttpRequestParser$$generated.handleHttpVerb(Unknown Source) ~[undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:07:40
at io.undertow.server.protocol.http.HttpRequestParser.handle(HttpRequestParser.java:243) ~[undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:07:40
at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:187) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:07:40
at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:07:40
at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:07:40
at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:07:40
at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

14:07:40
at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

14:07:40
at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

14:07:40
at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

14:07:40
at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

14:07:40
at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:131) [xnio-nio-3.7.0.Final.jar!/:3.7.0.Final]

14:07:40
at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612) [xnio-nio-3.7.0.Final.jar!/:3.7.0.Final]

14:07:40
at org.xnio.nio.WorkerThread.run(WorkerThread.java:479) [xnio-nio-3.7.0.Final.jar!/:3.7.0.Final]

14:08:10
2019-03-01 14:08:10.582 **TRACE** 1 --- [ XNIO-2 I/O-2] i.u.request : Opened connection with /10.202.10.145:41022

14:08:10
2019-03-01 14:08:10.582 DEBUG 1 --- [ XNIO-2 I/O-2] i.u.r.io : UT005014: Failed to parse request


ENTRYPOINT ["java","-Dserver.servlet.context-path=/zipkinserver","-Djava.security.egd=file:/dev/./urandom","-Dlogging.level.io.undertow=trace","-Dserver.undertow.accesslog.enabled=true","-Dlogging.level.root=debug","-jar", "/usr/src/zipkin-server.jar"]

**Comment by codefromthecrypt** [comment]
please try latest zipkin 2.12.3

**Comment by musabqamri123** [comment]
Its same with latest zipkin version 2.12.3

06:05:48
io.undertow.util.BadRequestException: java.lang.IllegalArgumentException: Invalid string contents ﾣﾟkro￁zﾨ8eﾤ
io.undertow.util.BadRequestException: java.lang.IllegalArgumentException: Invalid string contents ﾣﾟkro￁zﾨ8eﾤ

06:05:48
at io.undertow.server.protocol.http.HttpRequestParser.handle(HttpRequestParser.java:245) ~[undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:05:48
at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:187) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:05:48
at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:05:48
at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:05:48
at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:05:48
at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:05:48
at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

06:05:48
at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

06:05:48
at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

06:05:48
at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

06:05:48
at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:131) [xnio-nio-3.7.0.Final.jar!/:3.7.0.Final]

06:05:48
at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612) [xnio-nio-3.7.0.Final.jar!/:3.7.0.Final]

06:05:48
at org.xnio.nio.WorkerThread.run(WorkerThread.java:479) [xnio-nio-3.7.0.Final.jar!/:3.7.0.Final]

06:05:48
Caused by: java.lang.IllegalArgumentException: Invalid string contents ﾣﾟkro￁zﾨ8eﾤ

06:05:48
at io.undertow.util.HttpString.<init>(HttpString.java:116) ~[undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:05:48
at io.undertow.util.HttpString.<init>(HttpString.java:106) ~[undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:05:48
at io.undertow.server.protocol.http.HttpRequestParser$$generated.handleHttpVerb(Unknown Source) ~[undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:05:48
at io.undertow.server.protocol.http.HttpRequestParser.handle(HttpRequestParser.java:243) ~[undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:05:48
... 12 more

06:06:18
2019-03-04 06:06:18.037 TRACE 1 --- [ XNIO-2 I/O-1] i.u.request : Opened connection with /10.202.20.143:11302

06:06:18
2019-03-04 06:06:18.037 DEBUG 1 --- [ XNIO-2 I/O-1] i.u.r.io : UT005014: Failed to parse request

06:06:18
io.undertow.util.BadRequestException: null

06:06:18
at io.undertow.server.protocol.http.HttpRequestParser$$generated.handleHttpVerb(Unknown Source) ~[undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:06:18
at io.undertow.server.protocol.http.HttpRequestParser.handle(HttpRequestParser.java:243) ~[undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:06:18
at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:187) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:06:18
at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:06:18
at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:06:18
at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:06:18
at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57) [undertow-core-2.0.17.Final.jar!/:2.0.17.Final]

06:06:18
at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

06:06:18
at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

06:06:18
at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

06:06:18
at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.7.0.Final.jar!/:3.7.0.Final]

06:06:18
at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:131) [xnio-nio-3.7.0.Final.jar!/:3.7.0.Final]

06:06:18
at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612) [xnio-nio-3.7.0.Final.jar!/:3.7.0.Final]

06:06:18
at org.xnio.nio.WorkerThread.run(WorkerThread.java:479) [xnio-nio-3.7.0.Final.jar!/:3.7.0.Final]

06:06:18
2019-03-04 06:06:18.046 TRACE 1 --- [ XNIO-2 I/O-2] i.u.request : Opened connection with /10.202.10.64:64718

06:06:18
2019-03-04 06:06:18.046 DEBUG 1 --- [ XNIO-2 I/O-2] i.u.r.io : UT005014: Failed to parse request
