### ISSUE TITLE
InterruptedException in KafkaConsumer - Failed to close coordinator

### ISSUE THREAD

**Issue by gquintana** [openzipkin/zipkin#2448]
## Describe the Bug

When the KafkaCollectorWorker stops:
```
2019-03-18T10:41:24,962 ERROR org.apache.kafka.clients.consumer.KafkaConsumer - [Consumer clientId=consumer-1, groupId=zipkin] Failed to close coordinator
org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.closeHeartbeatThread(AbstractCoordinator.java:380) ~[kafka-clients-2.0.1.jar!/:?]
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.close(AbstractCoordinator.java:777) ~[kafka-clients-2.0.1.jar!/:?]
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.close(ConsumerCoordinator.java:590) ~[kafka-clients-2.0.1.jar!/:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2140) ~[kafka-clients-2.0.1.jar!/:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2108) ~[kafka-clients-2.0.1.jar!/:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2059) ~[kafka-clients-2.0.1.jar!/:?]
        at zipkin2.collector.kafka.KafkaCollectorWorker.run(KafkaCollectorWorker.java:106) ~[zipkin-collector-kafka-2.12.5.jar!/:?]
        at zipkin2.collector.kafka.KafkaCollector$LazyKafkaWorkers.lambda$guardFailures$0(KafkaCollector.java:252) ~[zipkin-collector-kafka-2.12.5.jar!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.InterruptedException
        at java.lang.Object.wait(Native Method) ~[?:1.8.0_202]
        at java.lang.Thread.join(Thread.java:1252) ~[?:1.8.0_202]
        at java.lang.Thread.join(Thread.java:1326) ~[?:1.8.0_202]
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.closeHeartbeatThread(AbstractCoordinator.java:377) ~[kafka-clients-2.0.1.jar!/:?]
        ... 10 more
```

## Steps to Reproduce

1. Run Zipkin server with Kafka collector
2. Stop the service

## Expected Behaviour

Properly close KafkaConsumer to 
* avoid error stacktraces
* allow clean consumer group rebalance because consumer leaves group properly
* avoir losing messages on stop: all polled messages should be processed before stopping the worker

**Comment by codefromthecrypt** [comment]
KafkaConsumer is in a try-finally.. what more correct way of closing are you suggesting? cc @jeqo 

```java
  @Override
  public void run() {
    try (KafkaConsumer kafkaConsumer = new KafkaConsumer<>(properties)) {
```

**Comment by codefromthecrypt** [comment]
I'm guessing you mean to share some signal (like atomic boolean isRunning) such that when `KafkaCollector.close()` is called it trips some conditional the poll loop would read and then exit vs using interrupt. Is that right?

**Comment by codefromthecrypt** [comment]
PS I agree that the error message is distracting and it would be a better idea to close differently than to try to change that logging category

**Comment by gquintana** [comment]
@adriancole That's it

**Comment by gquintana** [comment]
About logging, I also found this code strange:
```
      LOG.info("Closing Kafka consumer...");
      LOG.info("Kafka consumer closed.");
```
It gives the feeling the KafkaConsumer is close between the 2 logs, which is not the case.

**Comment by codefromthecrypt** [comment]
good points all around. Are you up to raising a change for the things found on this issue?

**Comment by gquintana** [comment]
I'll have a look and see if I can fix it.
