### ISSUE TITLE
kafka jaas

### ISSUE THREAD

**Issue by zackzhangzz** [openzipkin/zipkin#2471]
start zipkin:
java -Dzipkin.collector.kafka.overrides.sasl.mechanism=PLAIN -Dzipkin.collector.kafka.overrides.security.protocol=SASL_PLAINTEXT -Dzipkin.collector.kafka.overrides.sasl.jaas.config=/neworiental/service/zipkin/jaas.conf -jar zipkin.jar  --KAFKA_BOOTSTRAP_SERVERS=10.15.35.8:9092,10.125.4.193:9092,10.175.34.194:9092

jaas.conf:
KafkaClient {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="test"
  password="test";
};

show error:
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:799) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:650) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:630) ~[kafka-clients-2.0.1.jar!/:?]
	at zipkin2.collector.kafka.KafkaCollectorWorker.run(KafkaCollectorWorker.java:66) ~[zipkin-collector-kafka-2.12.2.jar!/:?]
	at zipkin2.collector.kafka.KafkaCollector$LazyKafkaWorkers.lambda$guardFailures$0(KafkaCollector.java:252) ~[zipkin-collector-kafka-2.12.2.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]

**Comment by codefromthecrypt** [comment]
@jeqo mind validating this one?

**Comment by jeqo** [comment]
Yes, I'll give a try. 
@zackzhangzz could you confirm that that's the complete stack trace?

**Comment by zackzhangzz** [comment]
@jeqo 
2019-03-28 11:56:09.934  WARN 51490 --- [pool-2-thread-1] z.c.k.KafkaCollectorWorker               : Unexpected error in polling loop spans

org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:799) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:650) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:630) ~[kafka-clients-2.0.1.jar!/:?]
	at zipkin2.collector.kafka.KafkaCollectorWorker.run(KafkaCollectorWorker.java:66) ~[zipkin-collector-kafka-2.12.2.jar!/:?]
	at zipkin2.collector.kafka.KafkaCollector$LazyKafkaWorkers.lambda$guardFailures$0(KafkaCollector.java:252) ~[zipkin-collector-kafka-2.12.2.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: Login module not specified in JAAS config
	at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:66) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:90) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:84) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:119) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:65) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:88) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:713) ~[kafka-clients-2.0.1.jar!/:?]
	... 7 more

2019-03-28 11:56:09.940  INFO 51490 --- [pool-2-thread-1] z.c.k.KafkaCollectorWorker               : Kafka consumer polling loop stopped.
2019-03-28 11:56:09.941  INFO 51490 --- [pool-2-thread-1] z.c.k.KafkaCollectorWorker               : Closing Kafka consumer...
2019-03-28 11:56:09.941  INFO 51490 --- [pool-2-thread-1] z.c.k.KafkaCollectorWorker               : Kafka consumer closed.
2019-03-28 11:56:09.941 ERROR 51490 --- [pool-2-thread-1] z.c.k.KafkaCollector                     : Kafka worker exited with exception

org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:799) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:650) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:630) ~[kafka-clients-2.0.1.jar!/:?]
	at zipkin2.collector.kafka.KafkaCollectorWorker.run(KafkaCollectorWorker.java:66) ~[zipkin-collector-kafka-2.12.2.jar!/:?]
	at zipkin2.collector.kafka.KafkaCollector$LazyKafkaWorkers.lambda$guardFailures$0(KafkaCollector.java:252) ~[zipkin-collector-kafka-2.12.2.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: Login module not specified in JAAS config
	at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:66) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:90) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:84) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:119) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:65) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:88) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:713) ~[kafka-clients-2.0.1.jar!/:?]
	... 7 more

2019-03-28 11:56:10.001  INFO 51490 --- [           main] o.xnio                                   : XNIO version 3.7.0.Final
2019-03-28 11:56:10.020  INFO 51490 --- [           main] o.x.nio                                  : XNIO NIO Implementation Version 3.7.0.Final
2019-03-28 11:56:10.063  INFO 51490 --- [           main] o.j.threads                              : JBoss Threads version 2.3.2.Final
2019-03-28 11:56:10.171  INFO 51490 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 9411 (http) with context path ''
2019-03-28 11:56:10.176  INFO 51490 --- [           main] z.s.ZipkinServer                         : Started ZipkinServer in 5.293 seconds (JVM running for 6.347)

**Comment by jeqo** [comment]
@zackzhangzz this looks similar to https://stackoverflow.com/a/45757197 could you give a try and check if it solves your issue?

**Comment by zackzhangzz** [comment]
java -Dzipkin.collector.kafka.overrides.sasl.mechanism=PLAIN -Dzipkin.collector.kafka.overrides.security.protocol=SASL_PLAINTEXT -Dzipkin.collector.kafka.overrides.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule\ required\ username="test"\ password="test"  -jar zipkin.jar  --KAFKA_BOOTSTRAP_SERVERS=ip:port


2019-04-01 12:09:47.117  WARN 1721 --- [pool-2-thread-1] z.c.k.KafkaCollectorWorker               : Unexpected error in polling loop spans

org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:799) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:650) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:630) ~[kafka-clients-2.0.1.jar!/:?]
	at zipkin2.collector.kafka.KafkaCollectorWorker.run(KafkaCollectorWorker.java:66) ~[zipkin-collector-kafka-2.12.2.jar!/:?]
	at zipkin2.collector.kafka.KafkaCollector$LazyKafkaWorkers.lambda$guardFailures$0(KafkaCollector.java:252) ~[zipkin-collector-kafka-2.12.2.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: JAAS config entry not terminated by semi-colon
	at org.apache.kafka.common.security.JaasConfig.parseAppConfigurationEntry(JaasConfig.java:121) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:63) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:90) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:84) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:119) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:65) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:88) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:713) ~[kafka-clients-2.0.1.jar!/:?]
	... 7 more

2019-04-01 12:09:47.124  INFO 1721 --- [pool-2-thread-1] z.c.k.KafkaCollectorWorker               : Kafka consumer polling loop stopped.
2019-04-01 12:09:47.124  INFO 1721 --- [pool-2-thread-1] z.c.k.KafkaCollectorWorker               : Closing Kafka consumer...
2019-04-01 12:09:47.124  INFO 1721 --- [pool-2-thread-1] z.c.k.KafkaCollectorWorker               : Kafka consumer closed.
2019-04-01 12:09:47.124 ERROR 1721 --- [pool-2-thread-1] z.c.k.KafkaCollector                     : Kafka worker exited with exception

org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:799) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:650) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:630) ~[kafka-clients-2.0.1.jar!/:?]
	at zipkin2.collector.kafka.KafkaCollectorWorker.run(KafkaCollectorWorker.java:66) ~[zipkin-collector-kafka-2.12.2.jar!/:?]
	at zipkin2.collector.kafka.KafkaCollector$LazyKafkaWorkers.lambda$guardFailures$0(KafkaCollector.java:252) ~[zipkin-collector-kafka-2.12.2.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: JAAS config entry not terminated by semi-colon
	at org.apache.kafka.common.security.JaasConfig.parseAppConfigurationEntry(JaasConfig.java:121) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:63) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:90) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:84) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:119) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:65) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:88) ~[kafka-clients-2.0.1.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:713) ~[kafka-clients-2.0.1.jar!/:?]

**Comment by codefromthecrypt** [comment]
it seems possible that using a spring properties file for more awkward values could br better. sorry I cannot hunt the how to link right now but it shouldn't be hard to find

**Comment by zackzhangzz** [comment]
Do you mean like this?

application.properties:
spring.kafka.bootstrap-servers=ip:port
spring.kafka.properties.security.protocol=SASL_PLAINTEXT
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="" password="";

Will zipkin auto load   application.properties?

**Comment by zackzhangzz** [comment]
java -Dzipkin.collector.kafka.overrides.sasl.mechanism=PLAIN -Dzipkin.collector.kafka.overrides.security.protocol=SASL_PLAINTEXT -Djava.security.auth.login.config=/jaas.conf  -jar zipkin.jar  --KAFKA_BOOTSTRAP_SERVERS=ip:port 

I try this. It works! Thanks.
