### ISSUE TITLE
Rare NPE in Jersey Brave instrumentation

### ISSUE THREAD

**Issue by timothybasanov** [openzipkin/zipkin#2555]
I’ve seen this exception, but have no repro scenario:
```
java.lang.NullPointerException
    at brave.jersey.server.EventParser.requestMatched(EventParser.java:37) ~[brave-instrumentation-jersey-server-5.6.2.jar:?]
    at brave.jersey.server.SpanCustomizingApplicationEventListener.onEvent(SpanCustomizingApplicationEventListener.java:58) ~[brave-instrumentation-jersey-server-5.6.2.jar:?]
```

**Comment by codefromthecrypt** [comment]
this should be in the brave project. do you mind recreating it there?
