### ISSUE TITLE
zipkin-server cannot work in IDEA , but when i use " java -jar zipkin.jar " in windows cmd , it works.

### ISSUE THREAD

**Issue by ruansheng8** [openzipkin/zipkin#2609]
![image](https://user-images.githubusercontent.com/24709538/58224174-2fd6b780-7d4f-11e9-8311-fe173e682366.png)

### **Start log in IDEA :**

```
:: Powered by Spring Boot ::         (v2.1.5.RELEASE)

2019-05-23 11:29:51.915  INFO 12864 --- [           main] z.s.ZipkinServer                         : Starting ZipkinServer on YY-shengR with PID 12864 (D:\IdeaProjects\incubator-zipkin\zipkin-server\target\classes started by ruansheng in D:\IdeaProjects\incubator-zipkin)
2019-05-23 11:29:51.918  INFO 12864 --- [           main] z.s.ZipkinServer                         : The following profiles are active: shared
2019-05-23 11:29:53.394  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.verboseExceptions: false (default)
2019-05-23 11:29:53.395  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.verboseSocketExceptions: false (default)
2019-05-23 11:29:53.395  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.verboseResponses: false (default)
2019-05-23 11:29:53.398  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.useEpoll: false (default)
2019-05-23 11:29:53.497  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.useOpenSsl: true (default)
2019-05-23 11:29:53.497  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.dumpOpenSslInfo: false (default)
2019-05-23 11:29:53.497  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.maxNumConnections: 2147483647 (default)
2019-05-23 11:29:53.497  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.numCommonWorkers: 24 (default)
2019-05-23 11:29:53.497  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.numCommonBlockingTaskThreads: 200 (default)
2019-05-23 11:29:53.498  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultMaxRequestLength: 10485760 (default)
2019-05-23 11:29:53.498  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultMaxResponseLength: 10485760 (default)
2019-05-23 11:29:53.498  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultRequestTimeoutMillis: 10000 (default)
2019-05-23 11:29:53.498  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultResponseTimeoutMillis: 15000 (default)
2019-05-23 11:29:53.499  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultConnectTimeoutMillis: 3200 (default)
2019-05-23 11:29:53.499  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultWriteTimeoutMillis: 1000 (default)
2019-05-23 11:29:53.499  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultServerIdleTimeoutMillis: 15000 (default)
2019-05-23 11:29:53.499  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultClientIdleTimeoutMillis: 10000 (default)
2019-05-23 11:29:53.499  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultHttp2InitialConnectionWindowSize: 1048576 (default)
2019-05-23 11:29:53.499  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultHttp2InitialStreamWindowSize: 1048576 (default)
2019-05-23 11:29:53.500  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultHttp2MaxFrameSize: 16384 (default)
2019-05-23 11:29:53.500  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultHttp2MaxStreamsPerConnection: 2147483647 (default)
2019-05-23 11:29:53.500  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultHttp2MaxHeaderListSize: 8192 (default)
2019-05-23 11:29:53.500  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultHttp1MaxInitialLineLength: 4096 (default)
2019-05-23 11:29:53.500  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultHttp1MaxHeaderSize: 8192 (default)
2019-05-23 11:29:53.500  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultHttp1MaxChunkSize: 8192 (default)
2019-05-23 11:29:53.500  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultUseHttp2Preface: true (default)
2019-05-23 11:29:53.501  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultUseHttp1Pipelining: false (default)
2019-05-23 11:29:53.501  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultBackoffSpec: exponential=200:10000,jitter=0.2 (default)
2019-05-23 11:29:53.501  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.defaultMaxTotalAttempts: 10 (default)
2019-05-23 11:29:53.501  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.routeCache: maximumSize=4096 (default)
2019-05-23 11:29:53.501  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.compositeServiceCache: maximumSize=256 (default)
2019-05-23 11:29:53.501  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.parsedPathCache: maximumSize=4096 (default)
2019-05-23 11:29:53.501  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.headerValueCache: maximumSize=4096 (default)
2019-05-23 11:29:53.502  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.cachedHeaders: :authority,:scheme,:method,accept-encoding,content-type (default)
2019-05-23 11:29:53.504  INFO 12864 --- [           main] c.l.a.c.Flags                            : com.linecorp.armeria.annotatedServiceExceptionVerbosity: unhandled (default)
2019-05-23 11:29:53.505  INFO 12864 --- [           main] c.l.a.c.Flags                            : /dev/epoll not available: java.lang.IllegalStateException: Only supported on Linux
2019-05-23 11:29:53.506  INFO 12864 --- [           main] c.l.a.c.Flags                            : Using OpenSSL: BoringSSL, 0x1010007f
2019-05-23 11:29:53.737  INFO 12864 --- [           main] c.l.a.s.d.DocStringExtractor             : Using com.linecorp.armeria.thrift.jsonDir: META-INF/armeria/thrift
2019-05-23 11:29:53.843  INFO 12864 --- [           main] c.l.a.c.u.SystemInfo                     : Hostname: yy-shengr (from 'hostname' command)
2019-05-23 11:29:56.268  INFO 12864 --- [oss-http-*:9411] c.l.a.s.Server                           : Serving HTTP at /0:0:0:0:0:0:0:0:9411 - http://127.0.0.1:9411/
2019-05-23 11:29:56.269  INFO 12864 --- [           main] c.l.a.s.ArmeriaAutoConfiguration         : Armeria server started at ports: {/0:0:0:0:0:0:0:0:9411=ServerPort(/0:0:0:0:0:0:0:0:9411, [http])}
2019-05-23 11:29:56.349  INFO 12864 --- [           main] c.d.d.core                               : DataStax Java driver 3.7.1 for Apache Cassandra
2019-05-23 11:29:56.358  INFO 12864 --- [           main] c.d.d.c.GuavaCompatibility               : Detected Guava >= 19 in the classpath, using modern compatibility layer
2019-05-23 11:29:56.515  INFO 12864 --- [           main] c.d.d.c.Native                           : Could not load JNR C Library, native system calls through this library will not be available (set this logger level to DEBUG to see the full stack trace).
2019-05-23 11:29:56.515  INFO 12864 --- [           main] c.d.d.c.ClockFactory                     : Using java.lang.System clock to generate timestamps.
2019-05-23 11:29:56.624  INFO 12864 --- [           main] z.s.ZipkinServer                         : Started ZipkinServer in 5.357 seconds (JVM running for 7.945)
```

### **When i send http request , zipkin server has error :**
```
2019-05-23 11:30:27.472  WARN 12864 --- [-worker-nio-2-4] c.l.a.i.a.AnnotatedHttpService           : [id: 0x714eec3f, L:0.0.0.0/0.0.0.0:9411 ! R:/127.0.0.1:45389][h1c://yy-shengr:9411/api/v2/spans#POST] Unexpected exception from an exception handler zipkin2.server.internal.BodyIsExceptionMessage:

java.lang.NullPointerException: text
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_191]
	at com.linecorp.armeria.common.HttpData.of(HttpData.java:120) ~[armeria-0.86.0.jar:?]
	at com.linecorp.armeria.common.HttpResponse.of(HttpResponse.java:133) ~[armeria-0.86.0.jar:?]
	at zipkin2.server.internal.BodyIsExceptionMessage.handleException(ZipkinHttpCollector.java:244) ~[classes/:?]
	at com.linecorp.armeria.internal.annotation.AnnotatedHttpService$CompositeExceptionHandlerFunction.handleException(AnnotatedHttpService.java:488) ~[armeria-0.86.0.jar:?]
	at com.linecorp.armeria.internal.annotation.AnnotatedHttpService$ExceptionFilteredHttpResponse.beforeError(AnnotatedHttpService.java:415) ~[armeria-0.86.0.jar:?]
	at com.linecorp.armeria.common.stream.FilteredStreamMessage$FilteringSubscriber.onError(FilteredStreamMessage.java:206) ~[armeria-0.86.0.jar:?]
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:330) ~[armeria-0.86.0.jar:?]
	at com.linecorp.armeria.common.stream.DeferredStreamMessage.abort(DeferredStreamMessage.java:281) ~[armeria-0.86.0.jar:?]
	at com.linecorp.armeria.common.stream.FilteredStreamMessage.abort(FilteredStreamMessage.java:171) ~[armeria-0.86.0.jar:?]
	at com.linecorp.armeria.common.stream.DeferredStreamMessage.abort(DeferredStreamMessage.java:278) ~[armeria-0.86.0.jar:?]
	at com.linecorp.armeria.common.stream.FilteredStreamMessage.abort(FilteredStreamMessage.java:171) ~[armeria-0.86.0.jar:?]
	at com.linecorp.armeria.common.stream.FilteredStreamMessage.abort(FilteredStreamMessage.java:171) ~[armeria-0.86.0.jar:?]
	at com.linecorp.armeria.server.HttpServerHandler.lambda$cleanup$2(HttpServerHandler.java:238) ~[armeria-0.86.0.jar:?]
	at java.util.IdentityHashMap.forEach(IdentityHashMap.java:1354) ~[?:1.8.0_191]
	at com.linecorp.armeria.server.HttpServerHandler.cleanup(HttpServerHandler.java:233) ~[armeria-0.86.0.jar:?]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) [netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

![image](https://user-images.githubusercontent.com/24709538/58224431-606b2100-7d50-11e9-9551-49509df76a65.png)

### **When i use java -jar zipkin.jar in windows , it works**

![image](https://user-images.githubusercontent.com/24709538/58224552-ce174d00-7d50-11e9-8128-4a791284d042.png)

**Comment by jorgheymans** [comment]
The recommended way to run the server during development is documented [here](https://github.com/apache/incubator-zipkin#running-the-server-from-source) .

**Comment by shakuzen** [comment]
@Cearnach it may be easier for us to troubleshoot your issue on Gitter: https://gitter.im/openzipkin/zipkin
The latest master should now have fixed the NullPointerException you were experiencing thanks to #2611. Now logs should tell you the actual cause of the error.

**Comment by codefromthecrypt** [comment]
as mentioned, we don't plan to support running out of an IDE
