### ISSUE TITLE
When elasticsearch is down, the health endpoint hangs with a 503

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2674]
This might not be too important but usually we return a detailed message instead of failing the endpoint completely

When started and elasticsearch is down
```bash
$ curl -s localhost:9411/health
503 Service Unavailable
```

When elasticsearch is down after being up once
```bash
$ curl -s localhost:9411/health
{"status":"DOWN","zipkin":{"status":"DOWN","details":{"ElasticsearchStorage{clientCustomizer=[TimeoutCustomizer{timeout=10000ms}], clientFactoryCustomizer=[TimeoutCustomizer{timeout=10000ms}], hostsSupplier=[http://localhost:9200], pipeline=null, flushOnWrites=false, maxRequests=64, strictTraceId=true, searchEnabled=true, autocompleteKeys=[], autocompleteTtl=3600000, autocompleteCardinality=20000, indexShards=5, indexReplicas=1, indexNameFormatter=IndexNameFormatter{index=zipkin, dateSeparator=-, dateFormat=yyyy-MM-dd}, namesLookback=86400000}":{"status":"DOWN","details":{"error":"java.util.concurrent.CompletionException: com.linecorp.armeria.client.endpoint.EndpointGroupException: HealthCheckedEndpointGroup(all:[Endpoint{localhost:9200, ipAddr=127.0.0.1, weight=1000}], healthy:]) is empty"}}}}}
```

**Comment by codefromthecrypt** [comment]
actually if you hit anything except the health endpoint first, it puts things into an unusable state. I think @anuraaga has some change in mind to fall back to unhealth checked names when health checking isn't complete yet. We need to solve this one way or another before release as when it is bad, most commands will return 503 and it isn't possible even to control-c out of it.

```
2019-07-20 15:54:08.774  WARN 39062 --- [-worker-nio-2-1] z.s.i.BodyIsExceptionMessage             : Unexpected error handling request.

com.linecorp.armeria.client.endpoint.EndpointGroupException: HealthCheckedEndpointGroup(all:], healthy:]) is empty
	at com.linecorp.armeria.client.endpoint.RoundRobinStrategy$RoundRobinSelector.select(RoundRobinStrategy.java:65) ~[armeria-0.88.0.jar!/:?]
	at com.linecorp.armeria.client.endpoint.EndpointGroupRegistry.selectNode(EndpointGroupRegistry.java:120) ~[armeria-0.88.0.jar!/:?]
	at com.linecorp.armeria.client.Endpoint.resolve(Endpoint.java:215) ~[armeria-0.88.0.jar!/:?]
	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:61) ~[armeria-0.88.0.jar!/:?]
	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:42) ~[armeria-0.88.0.jar!/:?]
	at com.linecorp.armeria.client.encoding.HttpDecodingClient.execute(HttpDecodingClient.java:92) ~[armeria-0.88.0.jar!/:?]
	at com.linecorp.armeria.client.encoding.HttpDecodingClient.execute(HttpDecodingClient.java:39) ~[armeria-0.88.0.jar!/:?]
	at com.linecorp.armeria.client.logging.LoggingClient.execute(LoggingClient.java:172) ~[armeria-0.88.0.jar!/:?]
	at zipkin2.elasticsearch.internal.client.RawContentLoggingClient.lambda$execute$0(RawContentLoggingClient.java:53) ~[zipkin-storage-elasticsearch-2.15.1-SNAPSHOT.jar!/:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235) ~[?:?]
	at zipkin2.elasticsearch.internal.client.RawContentLoggingClient.execute(RawContentLoggingClient.java:48) ~[zipkin-storage-elasticsearch-2.15.1-SNAPSHOT.jar!/:?]
	at zipkin2.elasticsearch.internal.client.RawContentLoggingClient.execute(RawContentLoggingClient.java:30) ~[zipkin-storage-elasticsearch-2.15.1-SNAPSHOT.jar!/:?]
	at com.linecorp.armeria.internal.ClientUtil.executeWithFallback(ClientUtil.java:42) ~[armeria-0.88.0.jar!/:?]
	at com.linecorp.armeria.client.UserClient.execute(UserClient.java:159) ~[armeria-0.88.0.jar!/:?]
	at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:61) ~[armeria-0.88.0.jar!/:?]
```

**Comment by anuraaga** [comment]
This happened because we moved the `await` out of `httpObject` into `check` I guess. I think I was expecting the `Storage` abstraction to call `check()` before issuing queries / spans, etc. Do you think such a change would make sense?

**Comment by codefromthecrypt** [comment]
I think before we made a call to ensure the index templates existed before proceeding. if the health check is now a dependency, then it should be a dependency of checking for index templates.

**Comment by codefromthecrypt** [comment]
I also think we will need to have a switch to turn off health checks because we may not have found all the quirks. we will want to be able to release zipkin soon, and there have been many odd things that seem to imply better safe to be able to either opt-into health checking or at least opt out of it.

**Comment by codefromthecrypt** [comment]
for example I get these quirks even on my laptop, which seems off. I think it is because of use of "localhost" which then trips it into health checking loop. If there's only one IP resolved maybe better to not have health checking as an in-band requirement.

**Comment by codefromthecrypt** [comment]
by in-band what I mean is that usually we don't require commands to route through the health checking device. We do have initialization dependencies, like make sure schema can be installed, but every thing I've run into about health check so far is red herring. I feel like we may have a catastrophe if we enable this by default to point where people won't want to upgrade. It might be better to make this opt-in until it isn't causing a lot of delay startup or hanging shutdown etc.

**Comment by anuraaga** [comment]
Yeah I think opt-in should be good until https://github.com/line/armeria/issues/1910 - hopefully that solves all the quirks

**Comment by anuraaga** [comment]
Though one thing, before that we should track down why an exception causes the server to hang - I think that would happen for any exception, here it just happens to be `EndpointGroupException`

**Comment by codefromthecrypt** [comment]
one way is to allow "untrusted connection" until health check boots up as it takes a while anyway. I think this is a good idea regardless of adding a switch to disable things. Primarily because the timeouts we are hitting are way longer than normal ES stuff. If we have some tuning to do, we should do that in the background until things are not eggshell.

ex. first version has health checking opt-in and then after we prove it is stable etc, we have health checking enabled by default. I think we can get some sites like LINE to test with health check and show it is stable for example, but usually we have chicken egg problem with testing.

By disabling health check we can also get to the bottom of what all the hanging is about, as I've not even gotten reliable tracing in order yet.

**Comment by codefromthecrypt** [comment]
here's a more recent stack trace of the "initial request not falling back to well known addresses" problem off off @kojilin's branch of 0.89

```
2019-07-22 08:36:58.160  WARN 58431 --- [-worker-nio-2-1] z.s.i.BodyIsExceptionMessage             : Unexpected error handling request.

com.linecorp.armeria.client.endpoint.EndpointGroupException: com.linecorp.armeria.client.endpoint.OrElseEndpointGroup@49f257c5 is empty
	at com.linecorp.armeria.client.endpoint.RoundRobinStrategy$RoundRobinSelector.select(RoundRobinStrategy.java:65) ~[armeria-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at com.linecorp.armeria.client.endpoint.EndpointGroupRegistry.selectNode(EndpointGroupRegistry.java:120) ~[armeria-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at com.linecorp.armeria.client.Endpoint.resolve(Endpoint.java:215) ~[armeria-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:61) ~[armeria-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:42) ~[armeria-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at com.linecorp.armeria.client.encoding.HttpDecodingClient.execute(HttpDecodingClient.java:92) ~[armeria-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at com.linecorp.armeria.client.encoding.HttpDecodingClient.execute(HttpDecodingClient.java:39) ~[armeria-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at com.linecorp.armeria.client.logging.LoggingClient.execute(LoggingClient.java:172) ~[armeria-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at zipkin2.elasticsearch.internal.client.RawContentLoggingClient.lambda$execute$0(RawContentLoggingClient.java:53) ~[zipkin-storage-elasticsearch-2.15.1-SNAPSHOT.jar!/:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235) ~[?:?]
	at zipkin2.elasticsearch.internal.client.RawContentLoggingClient.execute(RawContentLoggingClient.java:48) ~[zipkin-storage-elasticsearch-2.15.1-SNAPSHOT.jar!/:?]
	at zipkin2.elasticsearch.internal.client.RawContentLoggingClient.execute(RawContentLoggingClient.java:30) ~[zipkin-storage-elasticsearch-2.15.1-SNAPSHOT.jar!/:?]
	at com.linecorp.armeria.client.brave.BraveClient.execute(BraveClient.java:152) ~[armeria-brave-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at com.linecorp.armeria.client.brave.BraveClient.execute(BraveClient.java:56) ~[armeria-brave-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at com.linecorp.armeria.internal.ClientUtil.executeWithFallback(ClientUtil.java:42) ~[armeria-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at com.linecorp.armeria.client.UserClient.execute(UserClient.java:159) ~[armeria-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:61) ~[armeria-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:78) ~[armeria-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:74) ~[armeria-zipkin-armeria-0.21.2.Final-gb1aa67a-1413.jar!/:?]
	at zipkin2.elasticsearch.internal.client.HttpCall.sendRequest(HttpCall.java:133) ~[zipkin-storage-elasticsearch-2.15.1-SNAPSHOT.jar!/:?]
	at zipkin2.elasticsearch.internal.client.HttpCall.doExecute(HttpCall.java:96) ~[zipkin-storage-elasticsearch-2.15.1-SNAPSHOT.jar!/:?]
	at zipkin2.Call$Base.execute(Call.java:380) ~[zipkin-2.15.1-SNAPSHOT.jar!/:?]
	at zipkin2.elasticsearch.VersionSpecificTemplates.getVersion(VersionSpecificTemplates.java:224) ~[zipkin-storage-elasticsearch-2.15.1-SNAPSHOT.jar!/:?]
	at zipkin2.elasticsearch.VersionSpecificTemplates.get(VersionSpecificTemplates.java:190) ~[zipkin-storage-elasticsearch-2.15.1-SNAPSHOT.jar!/:?]
```

**Comment by codefromthecrypt** [comment]
response back to users is less than awesome on this first request while health check booting up

```
curl -X POST -s localhost:9411/api/v2/spans -H'Content-Type: application/json' -d @netflix.json
com.linecorp.armeria.client.endpoint.EndpointGroupException: com.linecorp.armeria.client.endpoint.OrElseEndpointGroup@5865d659 is empty
```

**Comment by codefromthecrypt** [comment]
I have tests now for the concerns about the response also https://github.com/openzipkin/zipkin/pull/2711
