### ISSUE TITLE
hunt down this error control-c on server

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2683]
^C2019-07-18 09:38:59.532  INFO 65346 --- [       Thread-2] o.s.b.f.s.DisposableBeanAdapter          : Destroy method 'close' on bean with name 'cassandraCluster' threw an exception: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/AbstractFuture$AtomicHelper
Exception in thread "globalEventExecutor-3-2" java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/async/InternalAsyncUtil
	at org.apache.logging.log4j.core.impl.MutableLogEvent.setMessage(MutableLogEvent.java:220)
	at org.apache.logging.log4j.core.impl.ReusableLogEventFactory.createEvent(ReusableLogEventFactory.java:80)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:404)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.slf4j.Log4jLogger.log(Log4jLogger.java:376)
	at io.netty.util.internal.logging.LocationAwareSlf4JLogger.log(LocationAwareSlf4JLogger.java:46)
	at io.netty.util.internal.logging.LocationAwareSlf4JLogger.warn(LocationAwareSlf4JLogger.java:209)
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:252)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.async.InternalAsyncUtil
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 12 more

**Comment by codefromthecrypt** [comment]
sorted
