### ISSUE TITLE
timeout when using multiple hosts in ES_HOSTS

### ISSUE THREAD

**Issue by jorgheymans** [openzipkin/zipkin#2763]
## Describe the Bug
When specifying multiple hosts in ES_HOSTS, zipkin fails to connect to them. 

ES version is 7.2.0

openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)

## Steps to Reproduce
`STORAGE_TYPE=elasticsearch  ES_HOSTS=http://host1:9200,http://host2:9200 java -jar zipkin-server-2.16.1-exec.jar  
`

An exception is thrown about half a minute after the zipkin UI is accessed for the first time:

```
2019-08-20 14:39:26.844  INFO 14512 --- [           main] z.s.ZipkinServer                         : Started ZipkinServer in 3.986 seconds (JVM running for 5.296)
2019-08-20 14:39:48.260  WARN 14512 --- [cking-tasks-1-2] c.l.a.i.a.DefaultExceptionHandler        : [id: 0x15e9a196, L:/0:0:0:0:0:0:0:1:9411 - R:/0:0:0:0:0:0:0:1:54342][h1c://d02di1505646dit:9411/zipkin/api/v2/services#GET] Unhandled exception from an annotated service:

java.lang.IllegalStateException: couldn't connect any of []
        at zipkin2.server.internal.elasticsearch.LazyHttpClientImpl.decorateHealthCheck(LazyHttpClientImpl.java:134) ~[classes!/:?]
        at zipkin2.server.internal.elasticsearch.LazyHttpClientImpl.getEndpoint(LazyHttpClientImpl.java:95) ~[classes!/:?]
        at zipkin2.server.internal.elasticsearch.LazyHttpClientImpl.get(LazyHttpClientImpl.java:67) ~[classes!/:?]
        at zipkin2.elasticsearch.ElasticsearchStorage.http(ElasticsearchStorage.java:309) ~[zipkin-storage-elasticsearch-2.16.1.jar!/:?]
        at zipkin2.elasticsearch.AutoValue_ElasticsearchStorage.http(AutoValue_ElasticsearchStorage.java:42) ~[zipkin-storage-elasticsearch-2.16.1.jar!/:?]
        at zipkin2.elasticsearch.VersionSpecificTemplates.get(VersionSpecificTemplates.java:189) ~[zipkin-storage-elasticsearch-2.16.1.jar!/:?]
        at zipkin2.elasticsearch.ElasticsearchStorage.ensureIndexTemplates(ElasticsearchStorage.java:279) ~[zipkin-storage-elasticsearch-2.16.1.jar!/:?]
        at zipkin2.elasticsearch.AutoValue_ElasticsearchStorage.ensureIndexTemplates(AutoValue_ElasticsearchStorage.java:27) ~[zipkin-storage-elasticsearch-2.16.1.jar!/:?]
        at zipkin2.elasticsearch.ElasticsearchStorage.spanStore(ElasticsearchStorage.java:209) ~[zipkin-storage-elasticsearch-2.16.1.jar!/:?]
        at zipkin2.elasticsearch.ElasticsearchStorage.serviceAndSpanNames(ElasticsearchStorage.java:214) ~[zipkin-storage-elasticsearch-2.16.1.jar!/:?]
        at zipkin2.server.internal.ZipkinQueryApiV2.getServiceNames(ZipkinQueryApiV2.java:83) ~[classes!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at com.linecorp.armeria.internal.annotation.AnnotatedHttpService.invoke(AnnotatedHttpService.java:260) ~[armeria-0.90.2.jar!/:?]
        at com.linecorp.armeria.internal.annotation.AnnotatedHttpService.lambda$serve0$3(AnnotatedHttpService.java:246) ~[armeria-0.90.2.jar!/:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at com.linecorp.armeria.common.AbstractRequestContext.lambda$makeContextAware$1(AbstractRequestContext.java:69) ~[armeria-0.90.2.jar!/:?]
        at io.micrometer.core.instrument.AbstractTimer.record(AbstractTimer.java:160) ~[micrometer-core-1.2.0.jar!/:1.2.0]
        at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:144) ~[micrometer-core-1.2.0.jar!/:1.2.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.39.Final.jar!/:4.1.39.Final]
        at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021) ~[?:?]
        at com.linecorp.armeria.client.endpoint.EndpointGroup.awaitInitialEndpoints(EndpointGroup.java:76) ~[armeria-0.90.2.jar!/:?]
        at zipkin2.server.internal.elasticsearch.LazyHttpClientImpl.decorateHealthCheck(LazyHttpClientImpl.java:131) ~[classes!/:?]
```
The classic UI will show this:
![image](https://user-images.githubusercontent.com/193792/63348376-637aab00-c359-11e9-9b7a-b1376ecc11f6.png)

Lens does not show (have ?) the error.

Maybe related during startup there is also this:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.resolver.dns.DnsNameResolver (jar:file:/C:/tmp/zipkin-server-2.16.1-exec.jar!/BOOT-INF/lib/netty-resolver-dns-4.1.39.Final.jar!/) to method sun.net.dns.ResolverConfiguration.open()
WARNING: Please consider reporting this to the maintainers of io.netty.resolver.dns.DnsNameResolver
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by jorgheymans** [comment]
Using IP addresses instead of hostnames fixes the issue.

**Comment by codefromthecrypt** [comment]
@anuraaga I guess we could make the "no endpoints" message more precise if at the end of the day dns is not resolvable, huh?

**Comment by codefromthecrypt** [comment]
meanwhile I asked @jorgheymans to try JRE 11 as eventhough I don't recall all the reasons, I do remember always avoiding JRE 9 :P

**Comment by jorgheymans** [comment]
on jdk11, starting with `--zipkin.storage.elasticsearch.health-check.enabled=false` in addition i get this straight away when accessing the UI:

```
2019-08-20 15:07:33.783  WARN 13472 --- [cking-tasks-1-1] c.l.a.i.a.DefaultExceptionHandler        : [id: 0xcbcf74ac, L:/0:0:0:0:0:0:0:1:9411 - R:/0:0:0:0:0:0:0:1:55523][h1c://d02aoeua456iddiu:9411/zipkin/api/v2/services#GET] Unhandled exception from an annotated service:

java.util.concurrent.RejectedExecutionException: Rejected execution: zipkin2.server.internal.elasticsearch.InitialEndpointSupplier$CompositeEndpointGroup@7f2fa739 is empty
        at zipkin2.elasticsearch.internal.client.HttpCall.lambda$sendRequest$3(HttpCall.java:173) ~[zipkin-storage-elasticsearch-2.16.1.jar!/:?]
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
        at com.linecorp.armeria.common.HttpMessageAggregator.fail(HttpMessageAggregator.java:146) ~[armeria-0.90.2.jar!/:?]
        at com.linecorp.armeria.common.HttpMessageAggregator.onError(HttpMessageAggregator.java:60) ~[armeria-0.90.2.jar!/:?]
        at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:370) ~[armeria-0.90.2.jar!/:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:194) ~[armeria-0.90.2.jar!/:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:363) ~[armeria-0.90.2.jar!/:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:306) ~[armeria-0.90.2.jar!/:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:181) ~[armeria-0.90.2.jar!/:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:166) ~[armeria-0.90.2.jar!/:?]
        at com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:309) ~[armeria-0.90.2.jar!/:?]
        at com.linecorp.armeria.common.HttpMessageAggregator.onSubscribe(HttpMessageAggregator.java:55) ~[armeria-0.90.2.jar!/:?]
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.lambda$subscribe$0(DefaultStreamMessage.java:124) ~[armeria-0.90.2.jar!/:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.39.Final.jar!/:4.1.39.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) ~[netty-common-4.1.39.Final.jar!/:4.1.39.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515) ~[netty-transport-4.1.39.Final.jar!/:4.1.39.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[netty-common-4.1.39.Final.jar!/:4.1.39.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.39.Final.jar!/:4.1.39.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.39.Final.jar!/:4.1.39.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.linecorp.armeria.client.endpoint.EndpointGroupException: zipkin2.server.internal.elasticsearch.InitialEndpointSupplier$CompositeEndpointGroup@7f2fa739 is empty
```

**Comment by codefromthecrypt** [comment]
I presume this is still dns.

does this show anything for you?
```bash
$ curl -s localhost:9411/actuator/prometheus|grep ^armeria_client_endpointGroup
armeria_client_endpointGroup_healthy{authority="elasticsearch:9200",ip="172.18.0.2",name="elasticsearch",} 1.0
armeria_client_endpointGroup_count{name="elasticsearch",state="unhealthy",} 0.0
armeria_client_endpointGroup_count{name="elasticsearch",state="healthy",} 1.0
```

**Comment by codefromthecrypt** [comment]
So if I understand correctly.. the following work
* multiple IP addresses
* single hostname

What doesn't work are multiple hostnames and the result is an empty endpoint group

**Comment by codefromthecrypt** [comment]
there's actually a copy of this class here. https://github.com/line/armeria/pull/1939

maybe I can make a pull request off that branch you can test? a little tired to do today, but I can try to follow-up tomorrow. thanks for the help debugging this @jorgheymans !
