### ISSUE TITLE
health check message is quite useless on TLS error

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2776]
If you point https at a plain text endpoint the health check response useless:

```
curl -s localhost:9411/health
{"status":"DOWN","zipkin":{"status":"DOWN","details":{"ElasticsearchStorage{initialEndpoints=https://localhost:9200, index=zipkin}":{"status":"DOWN","details":{"error":"java.util.concurrent.RejectedExecutionException: Rejected execution: null"}}}}}
```

There's a very understandable reason in the log.. the sort of thing we want to see especially on failure:

```
2019-08-24 08:56:32.870  WARN 49402 --- [-worker-nio-2-4] c.l.a.c.HttpClientPipelineConfigurator   : [id: 0xaed0f172, L:/127.0.0.1:62203 - R:localhost/127.0.0.1:9200] TLS handshake failed:

javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1224) ~[netty-handler-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1185) ~[netty-handler-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1256) ~[netty-handler-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1299) ~[netty-handler-4.1.39.Final.jar!/:4.1.39.Final]
```

I'll try to sort this out

cc @anuraaga @trustin

**Comment by codefromthecrypt** [comment]
This makes the problem a bit better, as at least we can see the `com.linecorp.armeria.common.ClosedSessionException` now. I do think it would be nicer to see the root exception, but possibly this is enough for now.. Will wait for feedback before closing.

https://github.com/openzipkin/zipkin/pull/2777

**Comment by jorgheymans** [comment]
TLS errors are now shown properly in the `health` endpoint:

![image](https://user-images.githubusercontent.com/193792/79042297-c5dd3000-7bf6-11ea-9158-91c72f435b5f.png)
