### ISSUE TITLE
ITZipkinSelfTracing.postIsTraced_v1 missing a span

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2781]
When `ITZipkinSelfTracing.postIsTraced_v1()` runs in travis, it consistently is missing the span for the storage call ("accept-spans"). It is so far not reprodicable elsewhere, and for now, we are ignoring the test.

```
2019-08-24 10:21:46.099  INFO 8830 --- [           main] z.s.i.b.ITZipkinSelfTracing              : Started ITZipkinSelfTracing in 0.976 seconds (JVM running for 34.896)
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.358 s <<< FAILURE! - in zipkin2.server.internal.brave.ITZipkinSelfTracing
[ERROR] postIsTraced_v1  Time elapsed: 10.127 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in zipkin2.server.internal.brave.ITZipkinSelfTracing Wanted 3 spans: got 2. Current traces: [[{"traceId":"0000000000000001","id":"0000000000000002","name":"test-trace","timestamp":1566604800000}], [{"traceId":"6fe88461749627eb","id":"6fe88461749627eb","kind":"SERVER","name":"post /api/v1/spans","timestamp":1566642106126618,"duration":11372,"localEndpoint":{"serviceName":"zipkin-server","ipv4":"172.17.0.1"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":50554},"annotations":[{"timestamp":1566642106126630,"value":"wr"},{"timestamp":1566642106137976,"value":"ws"}],"tags":{"http.method":"POST","http.path":"/api/v1/spans"}}]] within 10 seconds.
	at zipkin2.server.internal.brave.ITZipkinSelfTracing.awaitSpans(ITZipkinSelfTracing.java:119)
	at zipkin2.server.internal.brave.ITZipkinSelfTracing.postIsTraced_v1(ITZipkinSelfTracing.java:88)
Caused by: java.lang.AssertionError: Wanted 3 spans: got 2. Current traces: [[{"traceId":"0000000000000001","id":"0000000000000002","name":"test-trace","timestamp":1566604800000}], [{"traceId":"6fe88461749627eb","id":"6fe88461749627eb","kind":"SERVER","name":"post /api/v1/spans","timestamp":1566642106126618,"duration":11372,"localEndpoint":{"serviceName":"zipkin-server","ipv4":"172.17.0.1"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":50554},"annotations":[{"timestamp":1566642106126630,"value":"wr"},{"timestamp":1566642106137976,"value":"ws"}],"tags":{"http.method":"POST","http.path":"/api/v1/spans"}}]]
```

**Comment by codefromthecrypt** [comment]
if you just ignore the v1, the v2 will fail. I set both to ignore.

```
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in zipkin2.server.internal.brave.ITZipkinSelfTracing Wanted 3 spans: got 2. Current traces: [[{"traceId":"0000000000000001","id":"0000000000000002","name":"test-trace","timestamp":1566604800000}], [{"traceId":"fff6fd2f587752ec","id":"fff6fd2f587752ec","kind":"SERVER","name":"post /api/v2/spans","timestamp":1566646125299530,"duration":17064,"localEndpoint":{"serviceName":"zipkin-server","ipv4":"172.17.0.1"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":34992},"annotations":[{"timestamp":1566646125299541,"value":"wr"},{"timestamp":1566646125316581,"value":"ws"}],"tags":{"http.method":"POST","http.path":"/api/v2/spans"}}]] within 10 seconds.
	at zipkin2.server.internal.brave.ITZipkinSelfTracing.awaitSpans(ITZipkinSelfTracing.java:121)
	at zipkin2.server.internal.brave.ITZipkinSelfTracing.postIsTraced_v2(ITZipkinSelfTracing.java:101)
Caused by: java.lang.AssertionError: Wanted 3 spans: got 2. Current traces: [[{"traceId":"0000000000000001","id":"0000000000000002","name":"test-trace","timestamp":1566604800000}], [{"traceId":"fff6fd2f587752ec","id":"fff6fd2f587752ec","kind":"SERVER","name":"post /api/v2/spans","timestamp":1566646125299530,"duration":17064,"localEndpoint":{"serviceName":"zipkin-server","ipv4":"172.17.0.1"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":34992},"annotations":[{"timestamp":1566646125299541,"value":"wr"},{"timestamp":1566646125316581,"value":"ws"}],"tags":{"http.method":"POST","http.path":"/api/v2/spans"}}]]
```
