### ISSUE TITLE
Cannot decode spans due to IllegalArgumentException(Expected json, proto3 or thrift list encoding)

### ISSUE THREAD

**Issue by zhangzhaorui** [openzipkin/zipkin#2913]
Hi~，Boss！
I ran into some problems when I started the kafka+Cassandra+zipkin cluster with docker-compose。
I logged into kafka through filebeat collection and opened zipkin debug level log to find the error message！

The error message is as follows
2019-11-11 08:06:22.713 DEBUG 1 --- [pool-2-thread-1] z.c.k.KafkaCollector                     : Cannot decode spans due to IllegalArgumentException(Expected json, proto3 or thrift list encoding)

java.lang.IllegalArgumentException: Expected json, proto3 or thrift list encoding
	at zipkin2.SpanBytesDecoderDetector.decoderForListMessage(SpanBytesDecoderDetector.java:81) ~[zipkin-2.19.1.jar:?]
	at zipkin2.SpanBytesDecoderDetector.decoderForListMessage(SpanBytesDecoderDetector.java:72) ~[zipkin-2.19.1.jar:?]
	at zipkin2.collector.Collector.acceptSpans(Collector.java:167) ~[zipkin-collector-2.19.1.jar:?]
	at zipkin2.collector.kafka.KafkaCollectorWorker.run(KafkaCollectorWorker.java:108) ~[zipkin-collector-kafka-2.19.1.jar:?]
	at zipkin2.collector.kafka.KafkaCollector$LazyKafkaWorkers.lambda$guardFailures$0(KafkaCollector.java:268) ~[zipkin-collector-kafka-2.19.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

Please tell me how to solve it！Thank you very much

**Comment by zhangzhaorui** [comment]
docker-compose.yml
version: '2'

services:

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=cassandra3
      - CASSANDRA_ENSURE_SCHEMA=false
      - CASSANDRA_CONTACT_POINTS=172.16.31.96
      - KAFKA_BOOTSTRAP_SERVERS=172.16.31.96:9092
      - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
    ports:
      - 9411:9411
    depends_on:
      - storage
      - kafka-zookeeper


  kafka-zookeeper:
    image: openzipkin/zipkin-kafka
    container_name: kafka-zookeeper
    ports:
      - 2181:2181
      - 9092:9092
      - 19092:19092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=172.16.31.96:2181
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-manager:
    image: solsson/kafka-manager
    container_name: kafka-manager
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=172.16.31.96:2181
    volumes:
      - /etc/localtime:/etc/localtime

  storage:
    image: openzipkin/zipkin-cassandra
    container_name: cassandra
    ports:
      - 9042:9042
    volumes:
      - ./cassandra-data:/cassandra/data
      - /etc/localtime:/etc/localtime

  dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=cassandra3
      - CASSANDRA_CONTACT_POINTS=172.16.31.96
    volumes:
      - /etc/localtime:/etc/localtime
    depends_on:
      - storage

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.250.250.0/24

**Comment by jorgheymans** [comment]
@zhangzhaorui if this is still an issue, can you drop by in our gitter channel please ? https://gitter.im/openzipkin/zipkin
