### ISSUE TITLE
brave-instrumentation-jaxrs throws UnsupportedOperationException on the latest Jersey Client

### ISSUE THREAD

**Issue by SimY4** [openzipkin/zipkin#2931]
## Describe the Bug
I recently updated my brave-instumentation-jaxrs dependency from version 4.19.3 to 5.9.0 and noticed that with no additional code change brave instrumentation started failing with UnsupportedOperationException.

## Steps to Reproduce

The minimal example to reproduce this:

```
import brave.Tracing;
import brave.http.HttpTracing;
import brave.jaxrs2.TracingClientFilter;
import org.glassfish.jersey.client.ClientConfig;
import org.glassfish.jersey.client.JerseyClientBuilder;

Tracing tracing = Tracing.newBuilder().localServiceName("example").build()
ClientConfig clientConfig = new ClientConfig();
clientConfig.register(TracingClientFilter.create(HttpTracing.create(tracing).clientOf("any")));
Client client = JerseyClientBuilder.createClient(clientConfig);
```

Then try to hit an endpoint of any kind.

You'll get an exception that looks like this:
```
javax.ws.rs.ProcessingException: null
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:263)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:750)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:748)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:404)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:300)
        ...
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.mockito.internal.junit.JUnitRule$1.evaluateSafely(JUnitRule.java:57)
	at org.mockito.internal.junit.JUnitRule$1.evaluate(JUnitRule.java:48)
	at au.com.dius.pact.consumer.BaseProviderRule.lambda$runPactTest$2(BaseProviderRule.java:160)
	at au.com.dius.pact.consumer.BaseMockServer.runAndWritePact(MockHttpServer.kt:181)
	at au.com.dius.pact.consumer.ConsumerPactRunnerKt.runConsumerTest(ConsumerPactRunner.kt:13)
	at au.com.dius.pact.consumer.BaseProviderRule.runPactTest(BaseProviderRule.java:158)
	at au.com.dius.pact.consumer.BaseProviderRule.access$100(BaseProviderRule.java:22)
	at au.com.dius.pact.consumer.BaseProviderRule$1.evaluate(BaseProviderRule.java:78)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.UnsupportedOperationException: null
	at java.util.AbstractMap.put(AbstractMap.java:209)
	at javax.ws.rs.core.AbstractMultivaluedMap.getValues(AbstractMultivaluedMap.java:278)
	at javax.ws.rs.core.AbstractMultivaluedMap.putSingle(AbstractMultivaluedMap.java:96)
	at brave.jaxrs2.TracingClientFilter$HttpClientRequest.header(TracingClientFilter.java:103)
	at brave.http.HttpClientRequest$1.put(HttpClientRequest.java:31)
	at brave.http.HttpClientRequest$1.put(HttpClientRequest.java:29)
	at brave.propagation.B3Propagation$B3Injector.injectMulti(B3Propagation.java:202)
	at brave.propagation.B3Propagation$B3Injector.inject(B3Propagation.java:195)
	at brave.http.HttpClientHandler.handleSend(HttpClientHandler.java:113)
	at brave.http.HttpClientHandler.handleSend(HttpClientHandler.java:101)
	at brave.jaxrs2.TracingClientFilter.filter(TracingClientFilter.java:64)
	at org.glassfish.jersey.client.ClientFilteringStages$RequestFilteringStage.apply(ClientFilteringStages.java:91)
	at org.glassfish.jersey.client.ClientFilteringStages$RequestFilteringStage.apply(ClientFilteringStages.java:79)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)
	... 42 common frames omitted
```

## Expected Behaviour
Request successfully executed and being traced propertly.

**Comment by SimY4** [comment]
Sorry, wrong project.
