### ISSUE TITLE
Unexpected error handling request，.

### ISSUE THREAD

**Issue by uckyk** [openzipkin/zipkin#2953]
Today, Zipkin online has the following problems. At present, it is suspected that the access client writes too fast (but the sampling rate is only 0.1% about 5K / mins). The UI interface is particularly slow. Read the log and report an error as follows. What is this Armeria bag for? I can't find out why I reported this mistake.

> 2020-01-07 16:19:57.359  WARN 1 --- [ng-tasks-1-1307] z.s.i.BodyIsExceptionMessage             : Unexpected error handling request.

com.linecorp.armeria.client.ResponseTimeoutException: null
	at com.linecorp.armeria.client.ResponseTimeoutException.get(ResponseTimeoutException.java:36) ~[armeria-0.97.0.jar!/:?]
	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.run(HttpResponseDecoder.java:197) ~[armeria-0.97.0.jar!/:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:150) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-native-epoll-4.1.43.Final-linux-x86_64.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2020-01-07 16:19:57.363  WARN 1 --- [ng-tasks-1-1307] z.s.i.BodyIsExceptionMessage             : Unexpected error handling request.

com.linecorp.armeria.common.ClosedSessionException: null

2020-01-07 16:20:51.282  WARN 1 --- [rker-epoll-2-14] z.s.i.BodyIsExceptionMessage             : Unexpected error handling request.

com.linecorp.armeria.common.ClosedSessionException: null

2020-01-07 16:20:55.870  WARN 1 --- [ng-tasks-1-1307] z.s.i.BodyIsExceptionMessage             : Unexpected error handling request.

com.linecorp.armeria.common.ClosedSessionException: null

2020-01-07 16:22:21.003  WARN 1 --- [rker-epoll-2-17] z.s.i.BodyIsExceptionMessage             : Unexpected error handling request.

com.linecorp.armeria.common.ClosedSessionException: null

2020-01-07 16:22:21.369  WARN 1 --- [ng-tasks-1-1337] z.s.i.BodyIsExceptionMessage             : Unexpected error handling request.

com.linecorp.armeria.common.ClosedSessionException: null

2020-01-07 16:27:03.984  WARN 1 --- [rker-epoll-2-28] z.s.i.BodyIsExceptionMessage             : Unexpected error handling request.

com.linecorp.armeria.common.ClosedSessionException: null

2020-01-07 16:27:04.537  WARN 1 --- [ng-tasks-1-1508] z.s.i.BodyIsExceptionMessage             : Unexpected error handling request.

com.linecorp.armeria.common.ClosedSessionException: null

**Comment by uckyk** [comment]
By the way, the data is written into Kafka and stored in ES, not through HTTP

**Comment by uckyk** [comment]
I found a service that has a lot of spannames (URLs with Article timestamps), about 40000, and is very slow to render each page.
I use zuul to access spring cloud sleuth + Kafka + Zipkin.
How to control spanname generation, thank you

**Comment by uckyk** [comment]
> I found a service that has a lot of spannames (URLs with Article timestamps), about 40000, and is very slow to render each page.
> I use zuul to access spring cloud sleuth + Kafka + Zipkin.
> How to control spanname generation, thank you

http:/mesfasdia/publicasdf-api/artasdficles/301731601/pv
http:/mesfasdia/publicasdf-api/artasdficles/301731602/pv
http:/mesfasdia/publicasdf-api/artasdficles/301731603/pv
http:/mesfasdia/publicasdf-api/artasdficles/301731604/pv

**Comment by codefromthecrypt** [comment]
@uckyk 40000 is way too many span names. please use gitter for troubleshooting https://gitter.im/openzipkin/zipkin
