### ISSUE TITLE
Include zipkin-web/src/ into release snapshot for zipkin-web

### ISSUE THREAD

**Issue by drax68** [openzipkin/zipkin#297]
Seems it's needed for correct work of web-interface if start command from release notes used. 

```
INF [20130902-12:20:33.930] finatra: GET /
ERR [20130902-12:20:35.263] finatra: Internal Server Error
ERR [20130902-12:20:35.263] finatra: java.io.FileNotFoundException: zipkin-web/src/main/resources/templates/layouts/application.mustache (No such file or directory)
ERR [20130902-12:20:35.263] finatra:     at java.io.FileInputStream.open(Native Method)
ERR [20130902-12:20:35.263] finatra:     at java.io.FileInputStream.<init>(FileInputStream.java:138)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.finatra.FileResolver$.getLocalInputStream(FileService.scala:37)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.finatra.FileResolver$.getInputStream(FileService.scala:27)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.finatra.View.mustache(View.scala:84)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.finatra.View.render(View.scala:96)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.finatra.Response.setContent(Response.scala:62)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.finatra.Response.build(Response.scala:186)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.finatra.ResponseAdapter$$anonfun$apply$1.apply(ResponseAdapter.scala:23)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.finatra.ResponseAdapter$$anonfun$apply$1.apply(ResponseAdapter.scala:23)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$6.apply(Future.scala:635)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Try$.apply(Try.scala:13)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Future$.apply(Future.scala:58)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:635)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:635)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:609)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:608)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:67)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Promise$Transformer.k(Promise.scala:67)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Promise$Transformer.apply(Promise.scala:76)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Promise$Transformer.apply(Promise.scala:58)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Promise$$anon$1.run(Promise.scala:271)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.concurrent.Scheduler$LocalScheduler.run(Scheduler.scala:60)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.concurrent.Scheduler$LocalScheduler.submit(Scheduler.scala:40)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:26)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Promise.runq(Promise.scala:248)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Promise.updateIfEmpty(Promise.scala:502)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Promise.update(Promise.scala:475)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.util.Promise.setValue(Promise.scala:458)
ERR [20130902-12:20:35.263] finatra:     at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:71)
ERR [20130902-12:20:35.263] finatra:     (...more...)
```

**Comment by dirkweinhardt** [comment]
Substituting -D env=production for -D local_docroot=zipkin-web/src/main/resources did the trick for me:

java -cp libs -jar zipkin-web-1.1.0.jar -f config/web-dev.scala -D env=production

https://groups.google.com/forum/#!msg/zipkin-user/oqgXXa_HA0k/oszvXx_EtgYJ

**Comment by eirslett** [comment]
Closing due to lack of activity. zipkin-web/zipkin-ui is also refactored a lot. This issue probably doesn't apply anymore.
