### ISSUE TITLE
empty.min runtime exception

### ISSUE THREAD

**Issue by franklinhu** [openzipkin/zipkin#309]
Looks like we aren't handling an empty list correctly.

https://groups.google.com/forum/#!topic/zipkin-dev/apRnUbU7LnQ

```
[error] DEB [20131017-00:43:56.492] cassie: multiget_slice(Zipkin, [java.nio.HeapByteBuffer[pos=0 lim=29 cap=29], java.nio.HeapByteBuffer[pos=0 lim=29 cap=29], java.nio.HeapByteBuffer[pos=0 lim=29 cap=29], java.nio.HeapByteBuffer[pos=0 lim=29 cap=29], java.nio.HeapByteBuffer[pos=0 lim=29 cap=29], java.nio.HeapByteBuffer[pos=0 lim=29 cap=29], java.nio.HeapByteBuffer[pos=0 lim=29 cap=29], java.nio.HeapByteBuffer[pos=0 lim=29 cap=29], java.nio.HeapByteBuffer[pos=0 lim=29 cap=29], java.nio.HeapByteBuffer[pos=0 lim=29 cap=29]], ColumnParent(column_family:AnnotationsIndex), SlicePredicate(slice_range:SliceRange(start:00 04 E8 D5 6E 66 59 50, finish:, reversed:true, count:100)), ONE)
[error] ERR [20131017-00:43:56.496] query: getTraceIds failed
[error] ERR [20131017-00:43:56.496] query: java.lang.UnsupportedOperationException: empty.min
[error] ERR [20131017-00:43:56.496] query:     at scala.collection.TraversableOnce$class.min(TraversableOnce.scala:194)
[error] ERR [20131017-00:43:56.496] query:     at scala.collection.immutable.Stream.min(Stream.scala:186)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.zipkin.query.QueryService$$anonfun$getTraceIds$1$$anonfun$apply$9$$anonfun$apply$11$$anonfun$11.apply(QueryService.scala:161)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.zipkin.query.QueryService$$anonfun$getTraceIds$1$$anonfun$apply$9$$anonfun$apply$11$$anonfun$11.apply(QueryService.scala:161)
[error] ERR [20131017-00:43:56.496] query:     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
[error] ERR [20131017-00:43:56.496] query:     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
[error] ERR [20131017-00:43:56.496] query:     at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:60)
[error] ERR [20131017-00:43:56.496] query:     at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
[error] ERR [20131017-00:43:56.496] query:     at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
[error] ERR [20131017-00:43:56.496] query:     at scala.collection.mutable.ArrayBuffer.map(ArrayBuffer.scala:47)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.zipkin.query.QueryService$$anonfun$getTraceIds$1$$anonfun$apply$9$$anonfun$apply$11.apply(QueryService.scala:160)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.zipkin.query.QueryService$$anonfun$getTraceIds$1$$anonfun$apply$9$$anonfun$apply$11.apply(QueryService.scala:157)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$6.apply(Future.scala:635)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Try$.apply(Try.scala:13)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Future$.apply(Future.scala:58)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:635)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:635)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:609)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:608)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:67)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Promise$Transformer.k(Promise.scala:67)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Promise$Transformer.apply(Promise.scala:76)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Promise$Transformer.apply(Promise.scala:58)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Promise$$anon$1.run(Promise.scala:262)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.concurrent.Scheduler$LocalScheduler.run(Scheduler.scala:60)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.concurrent.Scheduler$LocalScheduler.submit(Scheduler.scala:40)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:26)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Promise.runq(Promise.scala:248)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Promise.updateIfEmpty(Promise.scala:502)
[error] ERR [20131017-00:43:56.496] query:     at com.twitter.util.Promise.update(Promise.scala:475)
[error] ERR [20131017-00:43:56.496] query:     (...more...)
```

**Comment by codefromthecrypt** [comment]
closed via #442
