### ISSUE TITLE
Provider org.mariadb.jdbc.internal.com.send.authentication.SendGssApiAuthPacket could not be instantiated

### ISSUE THREAD

**Issue by benxionghu** [openzipkin/zipkin#3372]
Run Zipkin from Dockercompose to store the file in mysql  ；But the operation reported an error
Here is my docker-comemage.yml file  

version: '2'

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
      - MYSQL_DB=zipkin
      - MYSQL_USER=mysqlname
      - MYSQL_PASS=mysqlpassword
      - MYSQL_HOST=ip
      - MYSQL_TCP_PORT=3306
    ports:
      - 9411:9411

**Comment by benxionghu** [comment]
java.util.ServiceConfigurationError: org.mariadb.jdbc.authentication.AuthenticationPlugin: Provider org.mariadb.jdbc.internal.com.send.authentication.SendGssApiAuthPacket could not be instantiated


	at java.util.ServiceLoader.fail(Unknown Source) ~[?:?]


	at java.util.ServiceLoader$ProviderImpl.newInstance(Unknown Source) ~[?:?]


	at java.util.ServiceLoader$ProviderImpl.get(Unknown Source) ~[?:?]


	at java.util.ServiceLoader$3.next(Unknown Source) ~[?:?]


	at org.mariadb.jdbc.authentication.AuthenticationPluginLoader.get(AuthenticationPluginLoader.java:47) ~[mariadb-java-client-2.7.1.jar:?]


	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:734) ~[mariadb-java-client-2.7.1.jar:?]


	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:553) ~[mariadb-java-client-2.7.1.jar:?]


	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1387) ~[mariadb-java-client-2.7.1.jar:?]


	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635) ~[mariadb-java-client-2.7.1.jar:?]


	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150) ~[mariadb-java-client-2.7.1.jar:?]


	at org.mariadb.jdbc.Driver.connect(Driver.java:89) ~[mariadb-java-client-2.7.1.jar:?]


	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-3.4.5.jar:?]


	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[HikariCP-3.4.5.jar:?]


	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-3.4.5.jar:?]


	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[HikariCP-3.4.5.jar:?]


	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[HikariCP-3.4.5.jar:?]


	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-3.4.5.jar:?]


	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-3.4.5.jar:?]


	at zipkin2.storage.mysql.v1.HasTraceIdHigh.test(HasTraceIdHigh.java:40) ~[zipkin-storage-mysql-v1-2.23.2.jar:?]


	at zipkin2.storage.mysql.v1.Schema.<init>(Schema.java:50) ~[zipkin-storage-mysql-v1-2.23.2.jar:?]


	at zipkin2.storage.mysql.v1.MySQLStorage.schema(MySQLStorage.java:131) ~[zipkin-storage-mysql-v1-2.23.2.jar:?]


	at zipkin2.storage.mysql.v1.MySQLStorage.spanStore(MySQLStorage.java:139) ~[zipkin-storage-mysql-v1-2.23.2.jar:?]


	at zipkin2.server.internal.ZipkinQueryApiV2.getTraces(ZipkinQueryApiV2.java:147) ~[classes/:?]


	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]


	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]


	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]


	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]


	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.invoke(AnnotatedService.java:331) ~[armeria-1.3.0.jar:?]


	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.lambda$serve0$6(AnnotatedService.java:306) ~[armeria-1.3.0.jar:?]


	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]


	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]


	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:502) ~[armeria-1.3.0.jar:?]


	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44) [micrometer-core-1.6.2.jar:1.6.2]


	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]


	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]


	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]


	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]


	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]


	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.54.Final.jar:4.1.54.Final]


	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by benxionghu** [comment]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.mariadb.jdbc.internal.com.send.authentication.SendGssApiAuthPacket


	at jdk.internal.reflect.GeneratedConstructorAccessor26.newInstance(Unknown Source) ~[?:?]


	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]


	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]


	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]

**Comment by benxionghu** [comment]
This is my error message

**Comment by haiyes** [comment]
Did you solve the problem?

**Comment by 1301536601** [comment]
The problem has been solved. The solution is that my mysql version is 8.0, and the program runs normally after switching to 5.7. Thank you very much for your reply

**Comment by benxionghu** [comment]
> 你解决问题了吗？

The problem has been solved. The solution is that my mysql version is 8.0, and the program runs normally after switching to 5.7. Thank you very much for your reply

**Comment by benxionghu** [comment]
The problem has been solved. The solution is that my mysql version is 8.0, and the program runs normally after switching to 5.7. Thank you very much for your reply

**Comment by qzmer1104** [comment]
why don't let user choose mysql version?

**Comment by fgjg123000** [comment]
Is 8.0 now supported？

**Comment by liaozesonger1** [comment]
实验得出：
1. zipkin docker 不能使用 mysql 8.0.28，可以使用mysql 8.0.17;
2. 可以通过直接运行 zipkin.jar 使用  mysql 8.0.28。

zipkin.jar来源：
https://zipkin.io/quickstart.sh
得到zipkin.jar，再单独打成docker运行可行。

**Comment by u2bo** [comment]
> 实验得出：
> 
> 1. zipkin docker 不能使用 mysql 8.0.28，可以使用mysql 8.0.17;
> 2. 可以通过直接运行 zipkin.jar 使用  mysql 8.0.28。
> 
> zipkin.jar来源： https://zipkin.io/quickstart.sh 得到zipkin.jar，再单独打成docker运行可行。

有封装好直接用的吗 @liaozesonger1
