### ISSUE TITLE
Unexpected error handling request

### ISSUE THREAD

**Issue by illeagalName** [openzipkin/zipkin#3373]
## Describe the Bug

`2021-09-06 19:48:18.394  WARN [/] 816431 --- [ing-tasks-1-455] z.s.i.BodyIsExceptionMessage             : Unexpected error handling request.

java.lang.RuntimeException:
	at zipkin2.elasticsearch.internal.client.HttpCall.lambda$parseResponse$4(HttpCall.java:265) ~[zipkin-storage-elasticsearch-2.23.2.jar!/:?]
	at zipkin2.elasticsearch.internal.client.HttpCall.parseResponse(HttpCall.java:275) ~[zipkin-storage-elasticsearch-2.23.2.jar!/:?]
	at zipkin2.elasticsearch.internal.client.HttpCall.doExecute(HttpCall.java:166) ~[zipkin-storage-elasticsearch-2.23.2.jar!/:?]
	at zipkin2.Call$Base.execute(Call.java:391) ~[zipkin-2.23.2.jar!/:?]
	at zipkin2.server.internal.ZipkinQueryApiV2.getServiceNames(ZipkinQueryApiV2.java:97) ~[classes!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.invoke(AnnotatedService.java:331) ~[armeria-1.3.0.jar!/:?]
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.lambda$serve0$6(AnnotatedService.java:306) ~[armeria-1.3.0.jar!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:502) ~[armeria-1.3.0.jar!/:?]
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44) [micrometer-core-1.6.2.jar!/:1.6.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.54.Final.jar!/:4.1.54.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

![image](https://user-images.githubusercontent.com/26620932/132217956-84087269-7337-4c7e-8055-87d99e2a9518.png)

## Steps to Reproduce
1.elasticsearch:7.14.0
2.kibana:7.14.0
3.RabbitMQ:3.8.8
4.SpringCloud:2020.0.3

**When I open the home page(http://localhost:9941) ,the console reported an error in the image**

## Expected Behaviour
Help me!!!

**Comment by leonaltair** [comment]
same problem with me. I'm planning to switch my elasticsearch version into 7.9 and try again.

**Comment by leonaltair** [comment]
I change my es version into 7.9.3, and this problem is gone. You can try it.
