### ISSUE TITLE
Issue while installing twitter zipkin

### ISSUE THREAD

**Issue by MistShi** [openzipkin/zipkin#338]
i got same issue. 

just do this :
1. git clone https://github.com/twitter/zipkin.git && cd zipkin  
2. bin/collector
3. bin/query
4. bin/web
5. http://ip.com:8080/ 

then got error:

<pre>[error] FAT [20140208-15:41:45.926] ZipkinQuery: A server service  threw an exception
[error] FAT [20140208-15:41:45.926] ZipkinQuery: org.apache.thrift.transport.TTransportException: Cannot read. Remote side has closed. Tried to read 33554433 bytes, but only got 110 bytes.
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:354)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:215)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.thrift.ThriftServerTracingFilter$$anonfun$apply$2.apply(ThriftServerFramedCodec.scala:216)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.thrift.ThriftServerTracingFilter$$anonfun$apply$2.apply(ThriftServerFramedCodec.scala:150)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.tracing.Trace$.unwind(Trace.scala:183)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.thrift.ThriftServerTracingFilter.apply(ThriftServerFramedCodec.scala:148)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.thrift.ThriftServerTracingFilter.apply(ThriftServerFramedCodec.scala:123)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.Filter$$anon$5.apply(Filter.scala:52)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:69)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.Service$$anon$1.apply(Service.scala:14)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.filter.MkJvmFilter$$anon$1.apply(JvmFilter.scala:29)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.Filter$$anon$5$$anon$1.apply(Filter.scala:53)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.tracing.TracingFilter$$anonfun$apply$1.apply(TracingFilter.scala:18)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.tracing.TracingFilter$$anonfun$apply$1.apply(TracingFilter.scala:16)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.tracing.Trace$.unwind(Trace.scala:183)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.tracing.TracingFilter.apply(TracingFilter.scala:16)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.Filter$$anon$5$$anon$1.apply(Filter.scala:53)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.filter.MonitorFilter$$anonfun$apply$1.apply(MonitorFilter.scala:16)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.finagle.filter.MonitorFilter$$anonfun$apply$1.apply(MonitorFilter.scala:16)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.util.Future$$anonfun$monitored$1.apply$mcV$sp(Future.scala:104)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.util.Monitor$$anonfun$apply$1.apply$mcV$sp(Monitor.scala:38)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.util.Monitor$$anonfun$apply$1.apply(Monitor.scala:38)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.util.Monitor$$anonfun$apply$1.apply(Monitor.scala:38)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.util.Monitor$$anonfun$using$1.apply(Monitor.scala:103)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.util.Monitor$.restoring(Monitor.scala:110)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.util.Monitor$.using(Monitor.scala:101)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.util.Monitor$class.apply(Monitor.scala:37)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.util.Monitor$$anon$1.apply(Monitor.scala:141)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     at com.twitter.util.Future$.monitored(Future.scala:103)
[error] FAT [20140208-15:41:45.926] ZipkinQuery:     (...more...) </pre>

**Comment by MistShi** [comment]
#339  is ok.
