### ISSUE TITLE
`docker-compose-elasticsearch` crashes upon startup: max virtual memory too low

### ISSUE THREAD

**Issue by Aaronontheweb** [openzipkin/zipkin#3380]
## Describe the Bug
When attempting to use https://github.com/openzipkin/zipkin/tree/master/docker/examples, running 

```
$ docker-compose -f docker-compose-elasticsearch.yml up
```

Results in an immediate Docker crash on my machine:

```
ERROR: [1] bootstrap checks failed

[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

ERROR: Elasticsearch did not exit normally - check the logs at /elasticsearch/logs/docker-cluster.log


[2021-10-05T00:14:24,332][INFO ][o.e.n.Node ] [zipkin-elasticsearch] stopping ...


uncaught exception in thread [Thread-2]

java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")

at java.base/java.security.AccessControlContext.checkPermission(Unknown Source)

at java.base/java.security.AccessController.checkPermission(Unknown Source)

at java.base/java.lang.SecurityManager.checkPermission(Unknown Source)

at java.base/java.lang.ClassLoader.checkClassLoaderPermission(Unknown Source)

at java.base/java.lang.ClassLoader.getParent(Unknown Source)

at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:114)

at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:74)

at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:228)

at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)

at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)

at org.elasticsearch.bootstrap.Bootstrap$4.run(Bootstrap.java:193)
```

## Steps to Reproduce
Attempt to run `docker-compose` with ElasticSearch using the `latest` Zipkin tag

## Expected Behaviour
A successful startup of Zipkin and ElasticSearch.

Note: I'm running on Windows 10 Pro, 19041.1237 with WSL2 and Ubuntu 20.04 as my distribution.

**Comment by Aaronontheweb** [comment]
Looks like on WSL2 you need to use `sysctl` to increase the number of virtual memory areas: https://stackoverflow.com/a/66547784/377476 - this worked for me.
