### ISSUE TITLE
  java.lang.NoClassDefFoundError: com/google/gson/stream/JsonReader  error  when start up zipkin 2.23.16 server

### ISSUE THREAD

**Issue by Layfolk-zcy** [openzipkin/zipkin#3454]
java.lang.NoClassDefFoundError: com/google/gson/stream/JsonReader
	at zipkin2.internal.JsonCodec$JsonReader.<init>(JsonCodec.java:51) ~[classes/:?]
	at zipkin2.internal.JsonCodec.readList(JsonCodec.java:143) ~[classes/:?]
	at zipkin2.codec.SpanBytesDecoder$3.decodeList(SpanBytesDecoder.java:123) ~[classes/:?]
	at zipkin2.collector.Collector.decodeList(Collector.java:196) ~[classes/:?]
	at zipkin2.collector.Collector.acceptSpans(Collector.java:186) ~[classes/:?]
	at zipkin2.collector.Collector.acceptSpans(Collector.java:172) ~[classes/:?]
	at zipkin2.collector.kafka.KafkaCollectorWorker.run(KafkaCollectorWorker.java:111) ~[classes/:?]
	at zipkin2.collector.kafka.KafkaCollector$LazyKafkaWorkers.lambda$guardFailures$0(KafkaCollector.java:265) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: com.google.gson.stream.JsonReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	... 11 more

**Comment by FocusProgram** [comment]
I also encountered the same problem. Did you solve it?

**Comment by FocusProgram** [comment]
I just solved this problem，change the scope from test to compile

![image](https://user-images.githubusercontent.com/44283663/182279208-d1c80cbf-04fb-483b-bc50-bbc0cde8e20c.png)

**Comment by saff22** [comment]
Hi the error java.lang.NoClassDefFoundError: com/google/gson/stream/JsonReader indicates that the class JsonReader from the package com.google.gson.stream is not found during runtime. #3454

Please add this dependency in the dependencies section as it is missing
<dependency>
        <groupId>com.google.code.gson</groupId>
        <artifactId>gson</artifactId>
        <version>2.8.9</version>
    </dependency>
</dependencies>

**Comment by codefromthecrypt** [comment]
Due to the error, my guess is you are running a custom zipkin server, which is not supported. Since it isn't supported, we can't open issues about problems with custom servers.

If you are getting this error with the builds we provide, docker or executable jar, please re-open!
