### ISSUE TITLE
starting time ```java -jar zipkin-server-2.23.18-exec.jar ```

### ISSUE THREAD

**Issue by uzbekdev1** [openzipkin/zipkin#3476]
java -jar zipkin-server-2.23.18-exec.jar

              oo
             oooo
            oooooo
           oooooooo
          oooooooooo
         oooooooooooo
       ooooooo  ooooooo
      oooooo     ooooooo
     oooooo       ooooooo
    oooooo   o  o   oooooo
   oooooo   oo  oo   oooooo
 ooooooo  oooo  oooo  ooooooo
oooooo   ooooo  ooooo  ooooooo
oooooo oooooo oooooo ooooooo
oooooooo oo oo oooooooo
ooooooooooooo oo oo ooooooooooooo
oooooooooooo oooooooooooo
oooooooo oooooooo
oooo oooo

 ________ ____  _  _____ _   _
|__  /_ _|  _ \| |/ /_ _| \ | |
  / / | || |_) | ' / | ||  \| |
 / /_ | ||  __/| . \ | || |\  |
|____|___|_|   |_|\_\___|_| \_|
:: version 2.23.18 :: commit 4b71677 ::

2022-09-23 04:15:55.359 WARN [/] 5252 --- [ main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'armeriaServerGracefulShutdownLifecycle'; nested exception is java.util.concurrent.CompletionException: java.lang.IllegalStateException: Armeria server failed to start
2022-09-23 04:15:55.372 INFO [/] 5252 --- [ main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-09-23 04:15:55.401 ERROR [/] 5252 --- [ main] o.s.b.SpringApplication : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'armeriaServerGracefulShutdownLifecycle'; nested exception is java.util.concurrent.CompletionException: java.lang.IllegalStateException: Armeria server failed to start
at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.20.jar!/:5.3.20]
at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.20.jar!/:5.3.20]
at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.20.jar!/:5.3.20]
at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_333]
at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.20.jar!/:5.3.20]
at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.20.jar!/:5.3.20]
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.20.jar!/:5.3.20]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.20.jar!/:5.3.20]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780) [spring-boot-2.5.14.jar!/:2.5.14]
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:453) [spring-boot-2.5.14.jar!/:2.5.14]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:343) [spring-boot-2.5.14.jar!/:2.5.14]
at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:143) [spring-boot-2.5.14.jar!/:2.5.14]
at zipkin.server.ZipkinServer.main(ZipkinServer.java:56) [classes!/:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_333]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_333]
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [zipkin-server-2.23.18-exec.jar:?]
a

**Comment by codefromthecrypt** [comment]
please re-open if you have an issue with a current version of zipkin
