### ISSUE TITLE
ArrayIndexOutOfBoundsException from MutableSpan

### ISSUE THREAD

**Issue by karkum** [openzipkin/zipkin#3533]
## Describe the Bug
When adding tags to an ongoing span, we occasionally see the following exception:

```
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
  at brave.handler.MutableSpan.tag(MutableSpan.java:883)
  at brave.RealSpan.tag(RealSpan.java:112)
  at brave.SpanCustomizerShield.tag(SpanCustomizerShield.java:35)
  at brave.CurrentSpanCustomizer.tag(CurrentSpanCustomizer.java:41)
```

I believe this occurs in rare race-conditions in which some tags are removed while others are being added. I will attempt to reproduce this with a test, but I'm not having any luck so far. Wanted to create this issue and see if others are seeing anything similar.

**Comment by Saravana-PS** [comment]
Hey, I would like to work on this issue. Can you assign it on me?
