### ISSUE TITLE
Benchmark throws exception "always scope with ActuateCollectorMetrics.forTransport"

### ISSUE THREAD

**Issue by Holmistr** [openzipkin/zipkin#3588]
## Describe the Bug
I was trying to run the JMH benchmarks in `benchmarks` directory. When I execute it, I get:

```
java.lang.IllegalStateException: always scope with ActuateCollectorMetrics.forTransport
	at zipkin2.server.internal.MicrometerCollectorMetrics.checkScoped(MicrometerCollectorMetrics.java:141)
	at zipkin2.server.internal.MicrometerCollectorMetrics.incrementBytes(MicrometerCollectorMetrics.java:128)
	at zipkin2.collector.MetricsBenchmarks.incrementBytes(MetricsBenchmarks.java:82)
	at zipkin2.collector.MetricsBenchmarks.incrementBytes_longSpans_Actuate(MetricsBenchmarks.java:58)
	at zipkin2.collector.jmh_generated.MetricsBenchmarks_incrementBytes_longSpans_Actuate_jmhTest.incrementBytes_longSpans_Actuate_avgt_jmhStub(MetricsBenchmarks_incrementBytes_longSpans_Actuate_jmhTest.java:186)
	at zipkin2.collector.jmh_generated.MetricsBenchmarks_incrementBytes_longSpans_Actuate_jmhTest.incrementBytes_longSpans_Actuate_AverageTime(MetricsBenchmarks_incrementBytes_longSpans_Actuate_jmhTest.java:150)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

## Steps to Reproduce
Steps to reproduce the behavior - simply run `java -jar target/benchmarks.jar` inside the `benchmarks` directory.

## Expected Behaviour
No exception, running benchmark.

I'm happy to work on a fix, but at this point I would appreciate a pointer whether this is a configuration issue or is the test just broken.

**Comment by codefromthecrypt** [comment]
I will pick at this over the next couple days, as it takes over an hour to run through the benchmarks ;) https://github.com/openzipkin/zipkin/pull/3619
