### ISSUE TITLE
flakey test: ITZipkinEureka

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#3703]
I'm not sure if the test is a flake or if the registration that said it succeeded in eureka (by logs anyway) actually failed. The read-back via API fails, but on the other hand, it says `Time elapsed: 0.153 s`. I wonder if for some reason awaitility is only trying this long?

```
 [INFO] Running zipkin2.server.internal.eureka.ITZipkinEureka
11:40:38,796 WARN  [main] support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker (PostProcessorRegistrationDelegate.java:429) - Bean 'com.linecorp.armeria.spring.ArmeriaBeanPostProcessorConfiguration' of type [com.linecorp.armeria.spring.ArmeriaBeanPostProcessorConfiguration$$SpringCGLIB$$0] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). The currently created BeanPostProcessor [armeriaBeanPostProcessor] is declared through a non-static factory method on that class; consider declaring it as static instead.
11:40:38,842 WARN  [main] server.RejectedRouteHandler (RejectedRouteHandler.java:54) - Virtual host '*' has a duplicate route: /health
11:40:38,912 INFO  [armeria-boss-http-*:38837] server.Server$ServerPortStartListener (Server.java:808) - Serving HTTP at /[0:0:0:0:0:0:0:0%0]:38837 - http://127.0.0.1:38837/
11:40:39,086 INFO  [armeria-common-worker-epoll-2-3] eureka.EurekaUpdatingListener (EurekaUpdatingListener.java:175) - Registered fv-az1487-52 to Eureka: http://localhost:32770/eureka/v2
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.02 s <<< FAILURE! -- in zipkin2.server.internal.eureka.ITZipkinEureka
Error:  zipkin2.server.internal.eureka.ITZipkinEureka.registersInEureka -- Time elapsed: 0.153 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Response{protocol=http/1.1, code=404, message=, url=http://localhost:32770/eureka/v2/apps/ZIPKIN}
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at zipkin2.server.internal.eureka.BaseITZipkinEureka.getEurekaZipkinAppAsString(BaseITZipkinEureka.java:119)
	at org.awaitility.core.AbstractHamcrestCondition.lambda$new$0(AbstractHamcrestCondition.java:48)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by codefromthecrypt** [comment]
hopefully #3702 fixed this, but we'll see

**Comment by codefromthecrypt** [comment]
I'll close this as seems gone
