### ISSUE TITLE
run zipkin with zookeeper throws exception

### ISSUE THREAD

**Issue by liujd** [openzipkin/zipkin#400]
```
[error] INF [20140717-21:01:54.095] zookeeper: Set group member ID to adaptiveleader_0000000008
[error] java.lang.NoSuchMethodError: com.twitter.common.zookeeper.Group.watch(Lcom/twitter/common/zookeeper/Group$GroupChangeListener;)V
[error]         at com.twitter.common.zookeeper.CandidateImpl.offerLeadership(CandidateImpl.java:136)
[error]         at com.twitter.zipkin.collector.sampler.adaptive.ZooKeeperAdaptiveLeader$class.start(ZooKeeperAdaptiveLeader.scala:78)
[error]         at com.twitter.zipkin.collector.sampler.adaptive.ZooKeeperAdaptiveLeader$$anon$1.start(ZooKeeperAdaptiveLeader.scala:152)
[error]         at com.twitter.zipkin.collector.sampler.adaptive.ZooKeeperAdaptiveSampler$class.start(ZooKeeperAdaptiveSampler.scala:42)
[error]         at com.twitter.zipkin.collector.sampler.adaptive.ZooKeeperAdaptiveSampler$$anon$1.start(ZooKeeperAdaptiveSampler.scala:60)
[error]         at com.twitter.zipkin.collector.builder.CollectorServiceBuilder$$anonfun$apply$1$$anonfun$apply$5.apply(CollectorServiceBuilder.scala:155)
[error]         at com.twitter.zipkin.collector.builder.CollectorServiceBuilder$$anonfun$apply$1$$anonfun$apply$5.apply(CollectorServiceBuilder.scala:152)
[error]         at scala.Option.foreach(Option.scala:197)
[error]         at com.twitter.zipkin.collector.builder.CollectorServiceBuilder$$anonfun$apply$1.apply(CollectorServiceBuilder.scala:152)
[error]         at com.twitter.zipkin.collector.builder.CollectorServiceBuilder$$anonfun$apply$1.apply(CollectorServiceBuilder.scala:104)
[error]         at com.twitter.zipkin.collector.Main$.main(Main.scala:34)
[error]         at com.twitter.zipkin.collector.Main.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:601)
[error]         at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:78)
[error]         at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:24)
[error]         at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:88)
[error]         at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:78)
[error]         at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
[error]         at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:33)
[error]         at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:40)
[error]         at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:56)
[error]         at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:80)
[error]         at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:89)
[error]         at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last zipkin-collector-service/compile:run for the full output.
[error] (zipkin-collector-service/compile:run) Nonzero exit code returned from runner: 1
```

Why? And how to solve it?

**Comment by lycplus** [comment]
I encounter this error too.

**Comment by sprsquish** [comment]
Just to check this off the list, have you done a clean compile?

**Comment by lycplus** [comment]
I reclone the project and build with
./bin/collector zk-adaptive
the problem remains. Do you mean deleting all files in ~/.ivy2

**Comment by yancl** [comment]
because the project depends on two different version com.twitter.common.zookeeper.group(0.0.44&0.0.67).

but they have different signature:
0.0.44:
public final void watch(final GroupChangeListener groupChangeListener)
      throws WatchException, InterruptedException {

0.0.67:
public final Command watch(final GroupChangeListener groupChangeListener)
      throws WatchException, InterruptedException {

and your compile error shows that it need 0.0.44(void return value),so failed.
[error] java.lang.NoSuchMethodError: com.twitter.common.zookeeper.Group.watch(Lcom/twitter/common/zookeeper/Group$GroupChangeListener;)V

look at the (V) of end of the line, it needs void return version watch method.

so when you remove dependency of 0.0.67, it works.
as a way to test the problem,just change the followwing ivy files to group 0.0.44 from 0.0.67:
~/.ivy2/cache/com.twitter/util-zk-common_2.9.2/ivy-6.16.0.xml
~/.ivy2/cache/com.twitter.common.zookeeper/server-set/ivy-1.0.72.xml

hopes this will be useful and you admin can fix it:)

**Comment by eirslett** [comment]
Closing due to lack of activity.
