### ISSUE TITLE
"check" task fails if you don't have redis installed

### ISSUE THREAD

**Issue by rtyler** [openzipkin/zipkin#515]
Because zipkin-redis is in the core repo, this is a problem, since its tests require a system dependency of redis-server to be installed.

We can either grab that dependency via Gradle (boo) or move zipkin-redis out

```
➜  zipkin git:(master) ✗ ./gradlew zipkin-redis:check
:zipkin-common:compileJava UP-TO-DATE
:zipkin-common:compileScala UP-TO-DATE
:zipkin-common:processResources UP-TO-DATE
:zipkin-common:classes UP-TO-DATE
:zipkin-common:jar UP-TO-DATE
:zipkin-scrooge:idlJar UP-TO-DATE
:zipkin-scrooge:copyDependencyIdl UP-TO-DATE
:zipkin-scrooge:copyIncludedIdl UP-TO-DATE
:zipkin-scrooge:generateInterfaces UP-TO-DATE
:zipkin-scrooge:compileJava UP-TO-DATE
:zipkin-scrooge:compileScala UP-TO-DATE
:zipkin-scrooge:processResources UP-TO-DATE
:zipkin-scrooge:classes UP-TO-DATE
:zipkin-scrooge:jar UP-TO-DATE
:zipkin-redis:compileJava UP-TO-DATE
:zipkin-redis:compileScala UP-TO-DATE
:zipkin-redis:processResources UP-TO-DATE
:zipkin-redis:classes UP-TO-DATE
:zipkin-redis:compileTestJava UP-TO-DATE
:zipkin-redis:compileTestScala UP-TO-DATE
:zipkin-redis:processTestResources UP-TO-DATE
:zipkin-redis:testClasses UP-TO-DATE
:zipkin-redis:test
Discovery starting.
Jul 29, 2015 2:22:34 AM com.twitter.finagle.Init$$anonfun$1 apply$mcV$sp
INFO: Finagle version 6.27.0 (rev=65df1512aadc8b79871a6dcafbbd210fd088b055) built at 20150727-172410
Discovery completed in 2 seconds, 205 milliseconds.
Run starting. Expected test count is: 36
*** RUN ABORTED *** (3 seconds, 62 milliseconds)
  java.util.concurrent.ExecutionException: java.io.IOException: Cannot run program "redis-server": error=2, No such file or directory
  at java.util.concurrent.FutureTask.report(FutureTask.java:122)
  at java.util.concurrent.FutureTask.get(FutureTask.java:192)
  at org.scalatest.tools.ConcurrentDistributor.waitUntilDone(ConcurrentDistributor.scala:52)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2549)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
  at org.scalatest.tools.Runner$.main(Runner.scala:860)
  at org.scalatest.tools.Runner.main(Runner.scala)
  ...
  Cause: java.io.IOException: Cannot run program "redis-server": error=2, No such file or directory
  at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
  at com.twitter.finagle.redis.util.ExternalRedis.assertRedisBinaryPresent(TestServer.scala:58)
  at com.twitter.finagle.redis.util.ExternalRedis.<init>(TestServer.scala:109)
  at com.twitter.finagle.redis.util.RedisCluster$$anonfun$start$1.apply(TestServer.scala:30)
  at com.twitter.finagle.redis.util.RedisCluster$$anonfun$start$1.apply(TestServer.scala:29)
  at scala.collection.immutable.Range.foreach(Range.scala:141)
  at com.twitter.finagle.redis.util.RedisCluster$.start(TestServer.scala:29)
  at com.twitter.zipkin.storage.redis.RedisSpecification$class.beforeAll(RedisSpecification.scala:27)
  at com.twitter.zipkin.storage.redis.RedisSetMapSpec.beforeAll(RedisSetMapSpec.scala:21)
  at org.scala     test.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:253)
  ...
  Cause: java.io.IOException: error=2, No such file or directory
  at java.lang.UNIXProcess.forkAndExec(Native Method)
  at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
  at java.lang.ProcessImpl.start(ProcessImpl.java:134)
  at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
  at com.twitter.finagle.redis.util.ExternalRedis.assertRedisBinaryPresent(TestServer.scala:58)
  at com.twitter.finagle.redis.util.ExternalRedis.<init>(TestServer.scala:109)
  at com.twitter.finagle.redis.util.RedisCluster$$anonfun$start$1.apply(TestServer.scala:30)
  at com.twitter.finagle.redis.util.RedisCluster$$anonfun$start$1.apply(TestServer.scala:29)
  at scala.collection.immutable.Range.foreach(Range.scala:141)
  at com.twitter.finagle.redis.util.RedisCluster$.start(TestServer.scala:29)
  ...
:zipkin-redis:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':zipkin-redis:test'.
> There were failing tests. See the results at: file:///home/tyler/source/github/openzipkin/zipkin/zipkin-redis/build/test-results/

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.967 secs
```

**Comment by eirslett** [comment]
+1 for moving redis out!

**Comment by codefromthecrypt** [comment]
Is there an alternative way to test this? For example, without literally forking a process?

**Comment by dsyer** [comment]
There is an embedded redis (Java) library that works on non-windows platforms. We use it in Spring Boot and Spring Cloud to test redis components with no assumptions if the platform supports it.

**Comment by codefromthecrypt** [comment]
Either way, but still probably need to move this out. Redis is scarcely
maintained, not tested in docker etc, and the main repo is already barely
keeping up with bugs.

Unless I hear from someone that they will champion Redis (by working on
this scala code and keeping it up), I'm going to create a repo and make it
independent. Since we can now publish gradle projects (as done in
zipkin-dependencies-spark), I think this is the right call, particularly as
it allows us to focus on most used, and most owned components.

**Comment by codefromthecrypt** [comment]
@eirslett here's the change to move this out: https://github.com/openzipkin/zipkin/pull/882
