### ISSUE TITLE
collector package-dist run error

### ISSUE THREAD

**Issue by gogototo99** [openzipkin/zipkin#525]
checkout master and run below:
bin/sbt zipkin-collector-service/package-dist
scripts/collector.sh

always has error:

INF [20150730-19:37:59.153] collector: Starting WriteQueueWorker
INF [20150730-19:37:59.154] collector: Starting WriteQueueWorker
INF [20150730-19:37:59.155] collector: Starting WriteQueueWorker
Exception in thread "main" java.lang.NoClassDefFoundError: com/twitter/zipkin/thriftscala/ZipkinCollector$FutureIface
    at com.twitter.zipkin.builder.Scribe$Interface$$anon$1.apply(Scribe.scala:45)
    at com.twitter.zipkin.builder.Scribe$Interface$$anon$1.apply(Scribe.scala:42)
    at com.twitter.zipkin.collector.builder.CollectorServiceBuilder$$anonfun$apply$1.apply(CollectorServiceBuilder.scala:127)
    at com.twitter.zipkin.collector.builder.CollectorServiceBuilder$$anonfun$apply$1.apply(CollectorServiceBuilder.scala:104)
    at com.twitter.zipkin.collector.Main$.main(Main.scala:34)
    at com.twitter.zipkin.collector.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: com.twitter.zipkin.thriftscala.ZipkinCollector$FutureIface
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 6 more

**Comment by codefromthecrypt** [comment]
For now, use `bin/collector` to start the collector. We've updated the readme accordingly. SBT will be removed for gradle soon.

**Comment by codefromthecrypt** [comment]
gradle will also address the distribution packaging, too. For example, here's how it is used in docker.

https://github.com/openzipkin/docker-zipkin/blob/master/base/Dockerfile#L7
