### ISSUE TITLE
Cannot import zipkin into intellij as a gradle project

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#530]
This is blocking our switch off SBT.

I've tried many things, including completely nuking my configuration. I think there's something misconfigured in gradle itself. When you go to import as a gradle project, things start whirring and Intellij eventually spits back to the welcome screen. Here's the relevant part of the log file

`/Users/acole/Library/Logs/IdeaIC14/idea.log`

```
2015-07-30 16:04:07,380 [ 174841]   WARN - .manage.ContentRootDataService - Can't import content roots. Reason: target module (ModuleData: module 'io.zipkin:zipkin-redis:1.2.0-SNAPSHOT') is not found at the ide. Content roots: [ContentRootData: content root:test=[source_root(/Users/acole/oss/zipkin/zipkin-redis/src/test/java), source_root(/Users/acole/oss/zipkin/zipkin-redis/src/test/scala)]|excluded=[source_root(/Users/acole/oss/zipkin/zipkin-redis/.gradle), source_root(/Users/acole/oss/zipkin/zipkin-redis/build)]|resource=[source_root(/Users/acole/oss/zipkin/zipkin-redis/src/main/resources)]|source=[source_root(/Users/acole/oss/zipkin/zipkin-redis/src/main/java), source_root(/Users/acole/oss/zipkin/zipkin-redis/src/main/scala)]|test_resource=[source_root(/Users/acole/oss/zipkin/zipkin-redis/src/test/resources)]] 
2015-07-30 16:04:07,380 [ 174841]   WARN - .manage.ContentRootDataService - Can't import content roots. Reason: target module (ModuleData: module 'io.zipkin:zipkin-query-core:1.2.0-SNAPSHOT') is not found at the ide. Content roots: [ContentRootData: content root:test=[source_root(/Users/acole/oss/zipkin/zipkin-query-core/src/test/java), source_root(/Users/acole/oss/zipkin/zipkin-query-core/src/test/scala)]|excluded=[source_root(/Users/acole/oss/zipkin/zipkin-query-core/.gradle), source_root(/Users/acole/oss/zipkin/zipkin-query-core/build)]|resource=[source_root(/Users/acole/oss/zipkin/zipkin-query-core/src/main/resources)]|source=[source_root(/Users/acole/oss/zipkin/zipkin-query-core/src/main/java), source_root(/Users/acole/oss/zipkin/zipkin-query-core/src/main/scala)]|test_resource=[source_root(/Users/acole/oss/zipkin/zipkin-query-core/src/test/resources)]] 
--snip--
2015-07-30 16:04:07,389 [ 174850]   WARN - ge.ModuleDependencyDataService - Can't import module dependencies [ModuleDependencyData: dependency=module 'io.zipkin:zipkin-web:1.2.0-SNAPSHOT'|scope=Compile|exported=false|owner=module 'io.zipkin:zipkin-redis-example:1.2.0-SNAPSHOT', ModuleDependencyData: dependency=module 'io.zipkin:zipkin-common:1.2.0-SNAPSHOT'|scope=Compile|exported=false|owner=module 'io.zipkin:zipkin-redis-example:1.2.0-SNAPSHOT', ModuleDependencyData: dependency=module 'io.zipkin:zipkin-scrooge:1.2.0-SNAPSHOT'|scope=Compile|exported=false|owner=module 'io.zipkin:zipkin-redis-example:1.2.0-SNAPSHOT', ModuleDependencyData: dependency=module 'io.zipkin:zipkin-redis:1.2.0-SNAPSHOT'|scope=Compile|exported=false|owner=module 'io.zipkin:zipkin-redis-example:1.2.0-SNAPSHOT', ModuleDependencyData: dependency=module 'io.zipkin:zipkin-query:1.2.0-SNAPSHOT'|scope=Compile|exported=false|owner=module 'io.zipkin:zipkin-redis-example:1.2.0-SNAPSHOT', ModuleDependencyData: dependency=module 'io.zipkin:zipkin-receiver-scribe:1.2.0-SNAPSHOT'|scope=Compile|exported=false|owner=module 'io.zipkin:zipkin-redis-example:1.2.0-SNAPSHOT', ModuleDependencyData: dependency=module 'io.zipkin:zipkin-collector:1.2.0-SNAPSHOT'|scope=Compile|exported=false|owner=module 'io.zipkin:zipkin-redis-example:1.2.0-SNAPSHOT', ModuleDependencyData: dependency=module 'io.zipkin:zipkin-zookeeper:1.2.0-SNAPSHOT'|scope=Compile|exported=false|owner=module 'io.zipkin:zipkin-redis-example:1.2.0-SNAPSHOT']. Reason: target module (ModuleData: module 'io.zipkin:zipkin-redis-example:1.2.0-SNAPSHOT') is not found at the ide and can't be imported 
2015-07-30 16:04:07,402 [ 174863]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
    at org.jetbrains.plugins.scala.project.package$ModuleExt.compilerConfiguration(package.scala:116)
    at org.jetbrains.plugins.scala.project.package$ModuleExt.configureScalaCompilerSettingsFrom(package.scala:113)
    at org.jetbrains.plugins.scala.project.gradle.ScalaGradleDataService.org$jetbrains$plugins$scala$project$gradle$ScalaGradleDataService$$doImport(ScalaGradleDataService.scala:33)
    at org.jetbrains.plugins.scala.project.gradle.ScalaGradleDataService$$anonfun$doImportData$1.apply(ScalaGradleDataService.scala:22)
    at org.jetbrains.plugins.scala.project.gradle.ScalaGradleDataService$$anonfun$doImportData$1.apply(ScalaGradleDataService.scala:22)
```

**Comment by codefromthecrypt** [comment]
@rtyler @blaines @abesto I'm a bit stumped.. mind having a swing?

**Comment by blaines** [comment]
Sure no problem I'll have a look!

**Comment by vprithvi** [comment]
I also have the same problem. I worked around it by adding the gradle idea plugin #532 

```
2015-07-30 14:16:33,348 [94548379]   WARN - ge.ModuleDependencyDataService - Can't import module dependencies [ModuleDependencyData: dependency=module 'io.zipkin:zipkin-common:1.2.0-SNAPSHOT'|scope=Compile|exported=false|owner=module 'io.zipkin:zipkin-web:1.2.0-SNAPSHOT', ModuleDependencyData: dependency=module 'io.zipkin:zipkin-scrooge:1.2.0-SNAPSHOT'|scope=Compile|exported=false|owner=module 'io.zipkin:zipkin-web:1.2.0-SNAPSHOT']. Reason: target module (ModuleData: module 'io.zipkin:zipkin-web:1.2.0-SNAPSHOT') is not found at the ide and can't be imported
2015-07-30 14:16:33,359 [94548390]  ERROR - llij.ide.plugins.PluginManager - null
java.lang.NullPointerException
    at org.jetbrains.plugins.scala.project.package$ModuleExt.compilerConfiguration(package.scala:116)
    at org.jetbrains.plugins.scala.project.package$ModuleExt.configureScalaCompilerSettingsFrom(package.scala:113)
    at org.jetbrains.plugins.scala.project.gradle.ScalaGradleDataService.org$jetbrains$plugins$scala$project$gradle$ScalaGradleDataService$$doImport(ScalaGradleDataService.scala:33)
    at org.jetbrains.plugins.scala.project.gradle.ScalaGradleDataService$$anonfun$doImportData$1.apply(ScalaGradleDataService.scala:22)
    at org.jetbrains.plugins.scala.project.gradle.ScalaGradleDataService$$anonfun$doImportData$1.apply(ScalaGradleDataService.scala:22)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1177)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at org.jetbrains.plugins.scala.project.gradle.ScalaGradleDataService.doImportData(ScalaGradleDataService.scala:22)
    at org.jetbrains.plugins.scala.project.gradle.AbstractDataService$$anonfun$importData$1.apply$mcV$sp(AbstractDataService.scala:20)
    at org.jetbrains.plugins.scala.project.gradle.AbstractDataService$$anon$1.execute(AbstractDataService.scala:39)
    at com.intellij.openapi.externalSystem.util.DisposeAwareProjectChange.run(DisposeAwareProjectChange.java:36)
    at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil$7$1.run(ExternalSystemApiUtil.java:462)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
    at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil$7.run(ExternalSystemApiUtil.java:459)
    at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.executeOnEdt(ExternalSystemApiUtil.java:472)
    at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.executeProjectChangeAction(ExternalSystemApiUtil.java:457)
    at org.jetbrains.plugins.scala.project.gradle.AbstractDataService$.invoke(AbstractDataService.scala:37)
    at org.jetbrains.plugins.scala.project.gradle.AbstractDataService.importData(AbstractDataService.scala:19)
    at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:132)
    at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:102)
    at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:141)
    at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:102)
    at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:141)
    at com.intellij.openapi.externalSystem.service.project.wizard.AbstractExternalProjectImportBuilder$2$1.run(AbstractExternalProjectImportBuilder.java:163)
    at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.mergeRootsChangesDuring(ProjectRootManagerImpl.java:328)
    at com.intellij.openapi.externalSystem.service.project.wizard.AbstractExternalProjectImportBuilder$2.execute(AbstractExternalProjectImportBuilder.java:160)
    at com.intellij.openapi.externalSystem.util.DisposeAwareProjectChange.run(DisposeAwareProjectChange.java:36)
    at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil$7$1.run(ExternalSystemApiUtil.java:462)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
    at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil$7.run(ExternalSystemApiUtil.java:459)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2350)
    at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.executeOnEdt(ExternalSystemApiUtil.java:479)
    at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.executeProjectChangeAction(ExternalSystemApiUtil.java:457)
    at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.executeProjectChangeAction(ExternalSystemApiUtil.java:453)
    at com.intellij.openapi.externalSystem.service.project.wizard.AbstractExternalProjectImportBuilder.commit(AbstractExternalProjectImportBuilder.java:157)
    at com.intellij.projectImport.ProjectImportBuilder.commit(ProjectImportBuilder.java:60)
    at com.intellij.projectImport.ProjectOpenProcessorBase.doOpenProject(ProjectOpenProcessorBase.java:222)
    at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:124)
    at com.intellij.ide.MacOSApplicationProvider$Worker$1.handleOpenFile(MacOSApplicationProvider.java:114)
    at com.apple.eawt._AppEventLegacyHandler$5.dispatchEvent(_AppEventLegacyHandler.java:122)
    at com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:168)
    at com.apple.eawt._AppEventLegacyHandler.openFiles(_AppEventLegacyHandler.java:120)
    at com.apple.eawt._AppEventHandler$_OpenFileDispatcher.performUsing(_AppEventHandler.java:353)
    at com.apple.eawt._AppEventHandler$_OpenFileDispatcher.performUsing(_AppEventHandler.java:344)
    at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:489)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by codefromthecrypt** [comment]
Workaround from @vprithvi is..
Invoke `./gradlew idea`, and open zipkin.ipr with IntelliJ. Don't link as a gradle project.

I used this approach and was able to run a unit test, etc. 

My 2p on what's next: If we can't get intellij to import properly, file a bug with jetbrains and note it here. Update our README with the workaround.

**Comment by abesto** [comment]
I'll have a look tonight (~9 hours from now)

**Comment by abesto** [comment]
#536 fixes it for me, please have a look.

**Comment by blaines** [comment]
I wasn't able to repro this, but adding the idea plugin is a good thing.

**Comment by abesto** [comment]
Closing as fixed, feel free to reopen / open another issue if things are still borken.
