### ISSUE TITLE
Re-implement zipkin-aggregates Cassandra source

### ISSUE THREAD

**Issue by aloon** [openzipkin/zipkin#597]
when I try execute the agregate hadoop 

``` bash
hadoop jar zipkin-aggregate/build/libs/zipkin-aggregate-twitter-is-here-all.jar --source cassandra --hosts localhost --port 9160
```

return me:

``` bash
Exception in thread "main" java.io.IOException: Mkdirs failed to create /var/folders/75/b_p3cc112y52tvjdfg1bkz580000gp/T/hadoop-unjar2090021427468948969/META-INF/license
    at org.apache.hadoop.util.RunJar.ensureDirectory(RunJar.java:128)
    at org.apache.hadoop.util.RunJar.unJar(RunJar.java:104)
    at org.apache.hadoop.util.RunJar.unJar(RunJar.java:81)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:209)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
```

I have read that it's problem of macos. I try to execute from debian but:

```
root@debian0:~# /root/hadoop-2.7.1/bin/hadoop jar /root/zipkin-aggregate-twitter-is-here-all.jar --source cassandra --hosts 172.16.144.1 --port 9160
Exception in thread "main" java.lang.Throwable: If you know what exactly caused this error, please consider contributing to GitHub via following link.
https://github.com/twitter/scalding/wiki/Common-Exceptions-and-possible-reasons#comtwitterscaldingargsexception
    at com.twitter.scalding.Tool$.main(Tool.scala:130)
    at com.twitter.zipkin.aggregate.RunHadoopJob$delayedInit$body.apply(RunHadoopJob.scala:4)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at com.twitter.zipkin.aggregate.RunHadoopJob$.main(RunHadoopJob.scala:3)
    at com.twitter.zipkin.aggregate.RunHadoopJob.main(RunHadoopJob.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.twitter.scalding.Job$.apply(Job.scala:45)
    at com.twitter.scalding.Tool.getJob(Tool.scala:46)
    at com.twitter.scalding.Tool.run(Tool.scala:66)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
    at com.twitter.scalding.Tool$.main(Tool.scala:126)
    ... 16 more
Caused by: com.twitter.scalding.ArgsException: cassandra is not an implemented source.
    at com.twitter.zipkin.aggregate.SpanSourceProvider$.apply(ZipkinAggregateJob.scala:54)
    at com.twitter.zipkin.aggregate.ZipkinAggregateJob.<init>(ZipkinAggregateJob.scala:16)
    ... 25 more
```

**Comment by codefromthecrypt** [comment]
This was collateral damage from moving off cassie. You can build aggregates from commit 6c68d55e0d1b62893d49dba81aa4224fba68ddcf for now.

**Comment by codefromthecrypt** [comment]
Here's the commit to resurrect files from: https://github.com/openzipkin/zipkin/commit/6e8fdad0bfa4c1de16215841f4c04f9710e3e686#diff-9e4ef735c2cc6a6622c3f51167c24b80

Note: when re-implementing this. I think it is preferable to put the hadoop/scalding code for cassandra into the `zipkin-aggregate` tree rather than `zipkin-cassandra`. `zipkin-aggregate` is the only user of this, and it is relatively dependency heavy.

**Comment by codefromthecrypt** [comment]
moved here https://github.com/openzipkin/zipkin-aggregate/issues/2
