### ISSUE TITLE
Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.DateTieredCompactionStrategy

### ISSUE THREAD

**Issue by lycplus** [openzipkin/zipkin#706]
I set CASSANDRA_CONTACT_POINTS to nodes that are up
it connects and fails like this:

```
Sep 14, 2015 6:17:52 PM com.twitter.zipkin.collector.Main$ main
INFO: Loading configuration
log4j:WARN No appenders could be found for logger (com.datastax.driver.core.SystemProperties).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
INF [20150914-18:17:57.100] stats: Starting LatchedStatsListener
700 [20150914-18:17:57.212] net: HttpServer created http 0.0.0.0/0.0.0.0:9900
700 [20150914-18:17:57.219] net: context created: /
700 [20150914-18:17:57.220] net: context created: /report/
700 [20150914-18:17:57.221] net: context created: /favicon.ico
700 [20150914-18:17:57.221] net: context created: /static
700 [20150914-18:17:57.222] net: context created: /pprof/heap
700 [20150914-18:17:57.224] net: context created: /pprof/profile
700 [20150914-18:17:57.224] net: context created: /pprof/contention
700 [20150914-18:17:57.225] net: context created: /tracing
700 [20150914-18:17:57.226] net: context created: /admin/registry
700 [20150914-18:17:57.226] net: context created: /health
700 [20150914-18:17:57.226] net: context created: /quitquitquit
700 [20150914-18:17:57.227] net: context created: /abortabortabort
700 [20150914-18:17:57.231] net: context created: /graph/
700 [20150914-18:17:57.232] net: context created: /graph_data
INF [20150914-18:17:57.233] admin: Starting TimeSeriesCollector
INF [20150914-18:17:57.234] admin: Admin HTTP interface started on port 9900.
INF [20150914-18:17:57.235] builder: Building store: <function0>
FAT [20150914-18:17:57.991] concurrent: input future failed.
FAT [20150914-18:17:57.991] concurrent: com.datastax.driver.core.TransportException: [/bad_cassandra_ip:9042] Cannot connect
FAT [20150914-18:17:57.991] concurrent:     at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:156)
FAT [20150914-18:17:57.991] concurrent:     at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:139)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:268)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:284)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
FAT [20150914-18:17:57.991] concurrent:     at java.lang.Thread.run(Thread.java:745)
FAT [20150914-18:17:57.991] concurrent: Caused by java.net.ConnectException: Connection refused: //bad_cassandra_ip:9042
FAT [20150914-18:17:57.991] concurrent:     at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
FAT [20150914-18:17:57.991] concurrent:     at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:281)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
FAT [20150914-18:17:57.991] concurrent:     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
FAT [20150914-18:17:57.991] concurrent:     at java.lang.Thread.run(Thread.java:745)
com.datastax.driver.core.exceptions.InvalidQueryException: Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.DateTieredCompactionStrategy'
    at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:35)
    at com.datastax.driver.core.DefaultResultSetFuture.extractCauseFromExecutionException(DefaultResultSetFuture.java:269)
    at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:183)
    at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:52)
    at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:36)
    at org.twitter.zipkin.storage.cassandra.Repository$Schema.ensureExists(Repository.java:644)
    at org.twitter.zipkin.storage.cassandra.Repository.<init>(Repository.java:90)
    at com.twitter.zipkin.cassandra.SpanStoreBuilder.apply(SpanStoreBuilder.scala:15)
    at com.twitter.zipkin.cassandra.SpanStoreBuilder.apply(SpanStoreBuilder.scala:10)
    at com.twitter.zipkin.storage.Store$Builder.apply(Store.scala:30)
    at com.twitter.zipkin.storage.Store$Builder.apply(Store.scala:26)
    at com.twitter.zipkin.collector.builder.CollectorServiceBuilder$$anonfun$apply$1.apply(CollectorServiceBuilder.scala:80)
    at com.twitter.zipkin.collector.builder.CollectorServiceBuilder$$anonfun$apply$1.apply(CollectorServiceBuilder.scala:76)
    at com.twitter.zipkin.collector.Main$.main(Main.scala:40)
    at com.twitter.zipkin.collector.Main.main(Main.scala)
Caused by: com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException: Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.DateTieredCompactionStrategy'
    at com.datastax.driver.core.Responses$Error.asException(Responses.java:103)
    at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:118)
    at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:183)
    at com.datastax.driver.core.RequestHandler.access$2300(RequestHandler.java:45)
    at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:748)
    at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:573)
    at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:991)
    at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:913)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at java.lang.Thread.run(Thread.java:745)
ERR [20150914-18:17:58.128] collector: Unexpected exception: Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.DateTieredCompactionStrategy'
ERR [20150914-18:17:58.128] collector: com.datastax.driver.core.exceptions.InvalidQueryException: Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.DateTieredCompactionStrategy'
ERR [20150914-18:17:58.128] collector:     at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:35)
ERR [20150914-18:17:58.128] collector:     at com.datastax.driver.core.DefaultResultSetFuture.extractCauseFromExecutionException(DefaultResultSetFuture.java:269)
ERR [20150914-18:17:58.128] collector:     at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:183)
ERR [20150914-18:17:58.128] collector:     at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:52)
ERR [20150914-18:17:58.128] collector:     at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:36)
ERR [20150914-18:17:58.128] collector:     at org.twitter.zipkin.storage.cassandra.Repository$Schema.ensureExists(Repository.java:644)
ERR [20150914-18:17:58.128] collector:     at org.twitter.zipkin.storage.cassandra.Repository.<init>(Repository.java:90)
ERR [20150914-18:17:58.128] collector:     at com.twitter.zipkin.cassandra.SpanStoreBuilder.apply(SpanStoreBuilder.scala:15)
ERR [20150914-18:17:58.128] collector:     at com.twitter.zipkin.cassandra.SpanStoreBuilder.apply(SpanStoreBuilder.scala:10)
ERR [20150914-18:17:58.128] collector:     at com.twitter.zipkin.storage.Store$Builder.apply(Store.scala:30)
ERR [20150914-18:17:58.128] collector:     at com.twitter.zipkin.storage.Store$Builder.apply(Store.scala:26)
ERR [20150914-18:17:58.128] collector:     at com.twitter.zipkin.collector.builder.CollectorServiceBuilder$$anonfun$apply$1.apply(CollectorServiceBuilder.scala:80)
ERR [20150914-18:17:58.128] collector:     at com.twitter.zipkin.collector.builder.CollectorServiceBuilder$$anonfun$apply$1.apply(CollectorServiceBuilder.scala:76)
ERR [20150914-18:17:58.128] collector:     at com.twitter.zipkin.collector.Main$.main(Main.scala:40)
ERR [20150914-18:17:58.128] collector:     at com.twitter.zipkin.collector.Main.main(Main.scala)
ERR [20150914-18:17:58.128] collector: Caused by com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException: Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.DateTieredCompactionStrategy'
ERR [20150914-18:17:58.128] collector:     at com.datastax.driver.core.Responses$Error.asException(Responses.java:103)
ERR [20150914-18:17:58.128] collector:     at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:118)
ERR [20150914-18:17:58.128] collector:     at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:183)
ERR [20150914-18:17:58.128] collector:     at com.datastax.driver.core.RequestHandler.access$2300(RequestHandler.java:45)
ERR [20150914-18:17:58.128] collector:     at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:748)
ERR [20150914-18:17:58.128] collector:     at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:573)
ERR [20150914-18:17:58.128] collector:     at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:991)
ERR [20150914-18:17:58.128] collector:     at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:913)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
ERR [20150914-18:17:58.128] collector:     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
ERR [20150914-18:17:58.128] collector:     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
ERR [20150914-18:17:58.128] collector:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
ERR [20150914-18:17:58.128] collector:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
ERR [20150914-18:17:58.128] collector:     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
ERR [20150914-18:17:58.128] collector:     at java.lang.Thread.run(Thread.java:745)
```

note that the host it fails on was not in the initial list

**Comment by lycplus** [comment]
May related to this issue: https://datastax-oss.atlassian.net/browse/JAVA-852?jql=text%20~%20%22tokens%20null%22 .

I notice that zipkin has used the official client instead of twitter/cassie when moved to zipkin.

**Comment by eirslett** [comment]
Yup; Zipkin moved to the official client since Cassie is abandoned/deprecated/gone.

**Comment by codefromthecrypt** [comment]
I think the point on host being down might be a red herring?

I get this error working against travis' cassandra after it says it is added.

```
[ScalaTest-1] INFO com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added
CassandraDependencyStoreSpec:
- getDependencies_insideTheInterval *** FAILED ***
  com.datastax.driver.core.exceptions.InvalidQueryException: Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.DateTieredCompactionStrategy'
```

**Comment by lycplus** [comment]
Yeah, recently, we mark the dead cassandra node as seed. The host down error  dissappear, but the `Unable to find compaction strategy...` error remains.

**Comment by codefromthecrypt** [comment]
I had to use the version of cassandra from our docker files. That said, I'm not knowledgeable enough to know if you can just this compaction class in a different distro.

``` bash
curl -SL http://downloads.datastax.com/community/dsc-cassandra-2.2.1-bin.tar.gz | tar xz && dsc-cassandra-2.2.1/bin/cassandra
```

**Comment by danchia** [comment]
@adriancole is the DTCS error flaky, or does it always happen?

**Comment by codefromthecrypt** [comment]
@danchia it always happens if you use the default travis cassandra service

**Comment by danchia** [comment]
Ah, do we not use `cassandra-unit` which brings in it's own cassandra?

**Comment by danchia** [comment]
If we're using travis, it seems like the latest version is `2.0.9` which doesn't have DTCS, which was introduced in `2.0.11`.

It seems like there's two options here:

1) In test, don't create the tables with DTCS. Compaction strategies shouldn't affect test behavior. However, it would require maintaining two separate cql files (one for test and one for end-users)..

2) Self-install a newer version of Cassandra manually in the travis script.

**Comment by codefromthecrypt** [comment]
option 3.. ask travis to update?

**Comment by danchia** [comment]
That's possible too =)

We need at least 2.0.11

**Comment by michaelsembwever** [comment]
:+1:

**Comment by codefromthecrypt** [comment]
most relevant travis issue: https://github.com/travis-ci/travis-ci/issues/3952

**Comment by codefromthecrypt** [comment]
Here's the latest workaround:

``` yaml
# Trusty Beta requires sudo per https://docs.travis-ci.com/user/ci-environment/
sudo: required
dist: trusty

# Manually install cassandra until https://github.com/travis-ci/travis-ci/issues/3952
before_install:
  - curl -SL http://downloads.datastax.com/community/dsc-cassandra-2.2.3-bin.tar.gz | tar xz
  - dsc-cassandra-*/bin/cassandra > /dev/null
```

**Comment by eirslett** [comment]
Closing due to lack of activity. We have a workaround that does the job for now. Looks like Travis won't upgrade their Cassandra for a while...
