### ISSUE TITLE
"scribe: Exception in process(): null" from collector when using anormdb backend

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#713]
Increasing verbosity, here's the whole exception that you get when finagle-zipkin sends traces to it. Note, it doesn't matter if you use default or mysql

```
diff --git a/zipkin-receiver-scribe/src/main/scala/com/twitter/zipkin/receiver/scribe/ScribeSpanReceiver.scala b/zipkin-receiver-scribe/src/main/scala/com/twitter/zipkin/receiver/scribe/ScribeSpanReceiver.scala
index 7d13fea..4582a84 100644
--- a/zipkin-receiver-scribe/src/main/scala/com/twitter/zipkin/receiver/scribe/ScribeSpanReceiver.scala
+++ b/zipkin-receiver-scribe/src/main/scala/com/twitter/zipkin/receiver/scribe/ScribeSpanReceiver.scala
@@ -112,7 +112,7 @@ class ScribeReceiver(
           ok
         case Throw(NonFatal(e)) =>
           if (!e.isInstanceOf[QueueFullException])
-            log.warning("Exception in process(): %s".format(e.getMessage))
+            log.warning(e, "Exception in process(): %s".format(e.getMessage))
           errorStats.counter(e.getClass.getName).incr()
           pushbackCounter.incr()
           tryLater
```

```
WAR [20150915-21:54:38.156] scribe: Exception in process(): null
WAR [20150915-21:54:38.156] scribe: java.util.concurrent.CancellationException
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.ExecutorServiceFuturePool$$anonfun$apply$1.applyOrElse(FuturePool.scala:142)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.ExecutorServiceFuturePool$$anonfun$apply$1.applyOrElse(FuturePool.scala:139)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise.raise(Promise.scala:509)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise$$anonfun$1$$anonfun$applyOrElse$1.apply(Promise.scala:232)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise$$anonfun$1$$anonfun$applyOrElse$1.apply(Promise.scala:232)
WAR [20150915-21:54:38.156] scribe:     at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
WAR [20150915-21:54:38.156] scribe:     at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise$$anonfun$1.applyOrElse(Promise.scala:232)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise$$anonfun$1.applyOrElse(Promise.scala:231)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise.raise(Promise.scala:509)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise.raise(Promise.scala:514)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise.raise(Promise.scala:514)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise.raise(Promise.scala:514)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise.raise(Promise.scala:514)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise$Chained.raise(Promise.scala:208)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise.raise(Promise.scala:514)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise.raise(Promise.scala:514)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise.raise(Promise.scala:514)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise$Chained.raise(Promise.scala:208)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise.raise(Promise.scala:514)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.finagle.mux.ServerDispatcher$$anonfun$3$$anonfun$apply$1$$anonfun$apply$mcVI$sp$1.apply(Server.scala:284)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.finagle.mux.ServerDispatcher$$anonfun$3$$anonfun$apply$1$$anonfun$apply$mcVI$sp$1.apply(Server.scala:283)
WAR [20150915-21:54:38.156] scribe:     at scala.Option.foreach(Option.scala:257)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.finagle.mux.ServerDispatcher$$anonfun$3$$anonfun$apply$1.apply$mcVI$sp(Server.scala:283)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.finagle.mux.ServerDispatcher$$anonfun$3$$anonfun$apply$1.apply(Server.scala:283)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.finagle.mux.ServerDispatcher$$anonfun$3$$anonfun$apply$1.apply(Server.scala:283)
WAR [20150915-21:54:38.156] scribe:     at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.finagle.mux.ServerDispatcher$$anonfun$3.apply(Server.scala:283)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.finagle.mux.ServerDispatcher$$anonfun$3.apply(Server.scala:277)
WAR [20150915-21:54:38.156] scribe:     at com.twitter.util.Promise$Monitored.apply(Promise.scala:73)
WAR [20150915-21:54:38.156] scribe:     (...more...)
WAR [20150915-21:54:38.156] scribe: Caused by com.twitter.finagle.CancelledRequestException: request cancelled due to com.twitter.finagle.ChannelClosedException: ChannelException at remote address: /127.0.0.1:58812
```

**Comment by codefromthecrypt** [comment]
cc @dsyer @jamescway @spencergibb @jfeltesse-mdsol I'm not sure this is actually causing problems in real life, but will look into it later.
