### ISSUE TITLE
run  zipkin from source but fails

### ISSUE THREAD

**Issue by rjbhewei** [openzipkin/zipkin#738]
> I am a new to zipkin , when i run it from source

```
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)

Scala code runner version 2.9.3 -- Copyright 2002-2011, LAMP/EPFL
```

> I use this  operation

`git clone https://github.com/openzipkin/zipkin.git`

`git checkout 1.10.0`

`bin/collector`

> but failed  , like this 

```
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
[buildinfo] Not using buildInfo properties file for this build.
:zipkin-common:compileJava UP-TO-DATE
:zipkin-common:compileScala
[ant:scalac] /usr/app/zipkin/zipkin-common/src/main/scala/com/twitter/zipkin/storage/SpanStore.scala:87: warning: implicit conversion method toScalaFunc should be enabled
[ant:scalac] by making the implicit value scala.language.implicitConversions visible.
[ant:scalac] This can be achieved by adding the import clause 'import scala.language.implicitConversions'
[ant:scalac] or by setting the compiler option -language:implicitConversions.
[ant:scalac] See the Scala docs for value scala.language.implicitConversions for a discussion
[ant:scalac] why the feature should be explicitly enabled.
[ant:scalac]   implicit def toScalaFunc(s: SpanStore): (Seq[Span] => Future[Unit]) = {
[ant:scalac]                ^
[ant:scalac] /usr/app/zipkin/zipkin-common/src/main/scala/com/twitter/zipkin/storage/SpanStore.scala:91: warning: implicit conversion method toTwitterCloseable should be enabled
[ant:scalac] by making the implicit value scala.language.implicitConversions visible.
[ant:scalac]   implicit def toTwitterCloseable(c: java.io.Closeable): Closable = {
[ant:scalac]                ^
[ant:scalac] two warnings found
:zipkin-common:processResources UP-TO-DATE
:zipkin-common:classes
:zipkin-common:jar
:zipkin-scrooge:idlJar
:zipkin-scrooge:copyDependencyIdl
:zipkin-scrooge:copyIncludedIdl
:zipkin-scrooge:generateInterfaces
:zipkin-scrooge:compileJava UP-TO-DATE
:zipkin-scrooge:compileScala
:zipkin-scrooge:processResources UP-TO-DATE
:zipkin-scrooge:classes
:zipkin-scrooge:jar
:zipkin-anormdb:compileJava
:zipkin-anormdb:compileScala
/usr/app/zipkin/zipkin-anormdb/src/main/scala/com/twitter/zipkin/storage/anormdb/AnormDependencyStore.scala:63: warning: postfix operator * should be enabled

```

```
:zipkin-anormdb:compileScala
/usr/app/zipkin/zipkin-anormdb/src/main/scala/com/twitter/zipkin/storage/anormdb/AnormDependencyStore.scala:63: warning: postfix operator * should be enabled
by making the implicit value scala.language.postfixOps visible.
This can be achieved by adding the import clause 'import scala.language.postfixOps'
or by setting the compiler option -language:postfixOps.
See the Scala docs for value scala.language.postfixOps for a discussion
why the feature should be explicitly enabled.
    }) *)
       ^
/usr/app/zipkin/zipkin-anormdb/src/main/scala/com/twitter/zipkin/storage/anormdb/AnormSpanStore.scala:121: warning: postfix operator * should be enabled
by making the implicit value scala.language.postfixOps visible.
        }) *)
           ^
/usr/app/zipkin/zipkin-anormdb/src/main/scala/com/twitter/zipkin/storage/anormdb/AnormSpanStore.scala:132: warning: postfix operator * should be enabled
by making the implicit value scala.language.postfixOps visible.
        }) *)
           ^
/usr/app/zipkin/zipkin-anormdb/src/main/scala/com/twitter/zipkin/storage/anormdb/AnormSpanStore.scala:145: warning: postfix operator * should be enabled
by making the implicit value scala.language.postfixOps visible.
        }) *)
           ^
/usr/app/zipkin/zipkin-anormdb/src/main/scala/com/twitter/zipkin/storage/anormdb/AnormSpanStore.scala:209: warning: postfix operator * should be enabled
by making the implicit value scala.language.postfixOps visible.
          .as((long("trace_id") ~ long("MAX(a_timestamp)") map flatten) *)
                                                                        ^
/usr/app/zipkin/zipkin-anormdb/src/main/scala/com/twitter/zipkin/storage/anormdb/AnormSpanStore.scala:253: warning: postfix operator * should be enabled
by making the implicit value scala.language.postfixOps visible.
              .as((long("trace_id") ~ long("created_ts") map flatten) *)
                                                                      ^
/usr/app/zipkin/zipkin-anormdb/src/main/scala/com/twitter/zipkin/storage/anormdb/AnormSpanStore.scala:271: warning: postfix operator * should be enabled
by making the implicit value scala.language.postfixOps visible.
              .as((long("trace_id") ~ long("MAX(a_timestamp)") map flatten) *)
                                                                            ^
/usr/app/zipkin/zipkin-anormdb/src/main/scala/com/twitter/zipkin/storage/anormdb/AnormSpanStore.scala:294: warning: postfix operator * should be enabled
by making the implicit value scala.language.postfixOps visible.
        .as(str("service_name") *).toSet
                                ^
/usr/app/zipkin/zipkin-anormdb/src/main/scala/com/twitter/zipkin/storage/anormdb/AnormSpanStore.scala:313: warning: postfix operator * should be enabled
by making the implicit value scala.language.postfixOps visible.
        .as(str("span_name") *)
                             ^
9 warnings found
:zipkin-anormdb:processResources
:zipkin-anormdb:classes
:zipkin-anormdb:jar
:zipkin-cassandra-core:compileJava
:zipkin-cassandra-core:compileScala UP-TO-DATE
:zipkin-cassandra-core:processResources
:zipkin-cassandra-core:classes
:zipkin-cassandra-core:jar
:zipkin-cassandra:compileJava UP-TO-DATE
:zipkin-cassandra:compileScala
:zipkin-cassandra:processResources UP-TO-DATE
:zipkin-cassandra:classes
:zipkin-cassandra:jar
:zipkin-collector:compileJava UP-TO-DATE
:zipkin-collector:compileScala
:zipkin-collector:processResources UP-TO-DATE

```

```
:zipkin-cassandra:jar
:zipkin-collector:compileJava UP-TO-DATE
:zipkin-collector:compileScala
:zipkin-collector:processResources UP-TO-DATE
:zipkin-collector:classes
:zipkin-collector:jar
:zipkin-receiver-kafka:compileJava UP-TO-DATE
:zipkin-receiver-kafka:compileScala
/usr/app/zipkin/zipkin-receiver-kafka/src/main/scala/com/twitter/zipkin/receiver/kafka/KafkaSpanReceiver.scala:22: warning: KafkaFactory$2 has a main method with parameter type Array[String], but com.twitter.zipkin.receiver.kafka.KafkaSp
anReceiverFactory.KafkaFactory$2 will not be a runnable program.
  Reason: companion contains its own main method, which means no static forwarder can be generated.

    object KafkaFactory extends App with KafkaSpanReceiverFactory
           ^
one warning found
:zipkin-receiver-kafka:processResources UP-TO-DATE
:zipkin-receiver-kafka:classes
:zipkin-receiver-kafka:jar
:zipkin-receiver-scribe:compileJava UP-TO-DATE
:zipkin-receiver-scribe:compileScala

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':zipkin-receiver-scribe:compile'.
> Could not resolve com.twitter.common:stats-util:0.0.58.
  Required by:
      io.zipkin:zipkin-receiver-scribe:1.10.0-SNAPSHOT > com.twitter:finagle-thriftmux_2.11:6.28.0 > com.twitter:finagle-mux_2.11:6.28.0
   > Could not resolve com.twitter.common:stats-util:0.0.58.
      > Could not get resource 'https://maven.twttr.com/com/twitter/common/stats-util/0.0.58/stats-util-0.0.58.pom'.
         > Could not HEAD 'https://maven.twttr.com/com/twitter/common/stats-util/0.0.58/stats-util-0.0.58.pom'.
            > Connection to https://maven.twttr.com refused

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':zipkin-receiver-scribe:compile'.
        at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.rethrowFailure(DefaultLenientConfiguration.java:62)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.rethrowFailure(DefaultResolvedConfiguration.java:36)
        at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyConfigurationResolver$FilesAggregatingResolvedConfiguration.rethrowFailure(SelfResolvingDependencyConfigurationResolver.java:112)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolvedConfiguration.rethrowFailure(ErrorHandlingConfigurationResolver.java:189)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:644)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:280)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileTreeConverter.convertInto(DefaultFileCollectionResolveContext.java:194)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:106)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileTrees(DefaultFileCollectionResolveContext.java:78)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileTreeConverter.convertInto(DefaultFileCollectionResolveContext.java:185)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:101)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileTrees(DefaultFileCollectionResolveContext.java:78)
        at org.gradle.api.internal.file.CompositeFileCollection$1.resolve(CompositeFileCollection.java:88)
        at org.gradle.api.internal.file.CompositeFileCollection.getSourceCollections(CompositeFileCollection.java:143)
        at org.gradle.api.internal.file.CompositeFileTree.getSourceCollections(CompositeFileTree.java:31)
        at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:38)
        at org.gradle.api.internal.changedetection.state.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:47)
        at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:55)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:126)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:69)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:52)

```

**Comment by codefromthecrypt** [comment]
Do you have a proxy that prevents access to maven.twttr com?

**Comment by rjbhewei** [comment]
i use proxy solved this problem
