### ISSUE TITLE
Can't launch zipkin-collector-service anymore

### ISSUE THREAD

**Issue by fedj** [openzipkin/zipkin#752]
Hi,

Collector service is failing to initialize since release 1.13.2 with stack trace at the end of this message.
The service is launched using an uber/distribution jar with KAFKA_ZOOKEEPER and CASSANDRA_CONTACT_POINTS set and args -f "/collector-cassandra.scala"

oct. 01, 2015 10:00:28 AM com.twitter.zipkin.collector.Main$ main
INFO: Loading configuration
Exception in thread "main" java.lang.ClassCastException: org.slf4j.impl.Log4jLoggerAdapter cannot be cast to ch.qos.logback.classic.Logger
    at com.twitter.zipkin.collector.builder.CollectorServiceBuilder.<init>(CollectorServiceBuilder.scala:58)
    at Evaluator__e159cbfa19ffabdfd403893042d8259dc9d60b49_1432356100.apply((inline):56)
    at Evaluator__e159cbfa19ffabdfd403893042d8259dc9d60b49_1432356100.apply((inline):1)
    at com.twitter.util.Eval.applyProcessed(Eval.scala:204)
    at com.twitter.util.Eval.applyProcessed(Eval.scala:196)
    at com.twitter.util.Eval.apply(Eval.scala:142)
    at com.twitter.zipkin.collector.Main$.main(Main.scala:41)
    at com.twitter.zipkin.collector.Main.main(Main.scala)

**Comment by codefromthecrypt** [comment]
Can you verify with 1.14.0 and also that there's nothing in the classpath
except the uber jar?

**Comment by codefromthecrypt** [comment]
I noticed this along the way: https://github.com/openzipkin/zipkin/pull/753

**Comment by codefromthecrypt** [comment]
I can't reproduce this with 1.13.2 or 1.14.0. However we should merge #753 to squash the error.

Could your classpath has something besides the collector jar in it?

```
curl -SL https://repo1.maven.org/maven2/io/zipkin/zipkin-collector-service/1.14.0/zipkin-collector-service-1.14.0-all.jar > collector.jar
KAFKA_ZOOKEEPER=127.0.0.1 CASSANDRA_CONTACT_POINTS=127.0.0.1 java -jar collector.jar -f /collector-cassandra.scala
```

**Comment by fedj** [comment]
Hey Adrian,

I finally found my error. We are trying to make an uber jar with maven and it seems that zk has a dependency on slf4j-log4j12 which has to be excluded. Now excluded, it works perfectly.

Thanks for your help

**Comment by codefromthecrypt** [comment]
I feel your pain. Glad you found it.
