### ISSUE TITLE
zipkin-collect  TProtocolException

### ISSUE THREAD

**Issue by rjbhewei** [openzipkin/zipkin#785]
```

org.apache.thrift.protocol.TProtocolException: unrecognized type code 83
        at com.twitter.scrooge.ThriftUtil$.transfer(ThriftUtil.scala:103)
        at com.twitter.scrooge.ThriftUtil$.transfer(ThriftUtil.scala:11)
        at com.twitter.scrooge.TFieldBlob$$anonfun$read$1.apply(TFieldBlob.scala:9)
        at com.twitter.scrooge.TFieldBlob$$anonfun$read$1.apply(TFieldBlob.scala:9)
        at com.twitter.scrooge.TFieldBlob$.capture(TFieldBlob.scala:15)
        at com.twitter.scrooge.TFieldBlob$.read(TFieldBlob.scala:9)
        at com.twitter.zipkin.thriftscala.Span$.eagerDecode(Span.scala:443)
        at com.twitter.zipkin.thriftscala.Span$.decode(Span.scala:328)
        at com.twitter.zipkin.thriftscala.Span$.decode(Span.scala:25)
        at com.twitter.scrooge.BinaryThriftStructSerializer$class.fromBytes(ThriftStructSerializer.scala:84)
        at com.twitter.zipkin.receiver.kafka.SpanCodec$$anon$1.fromBytes(SpanCodec.scala:10)
        at com.twitter.zipkin.receiver.kafka.SpanCodec.fromBytes(SpanCodec.scala:21)
        at com.twitter.zipkin.receiver.kafka.SpanCodec.fromBytes(SpanCodec.scala:9)
        at kafka.message.MessageAndMetadata.message(MessageAndMetadata.scala:32)
        at com.twitter.zipkin.receiver.kafka.KafkaStreamProcessor$$anonfun$run$1.apply(KafkaStreamProcessor.scala:19)
        at com.twitter.zipkin.receiver.kafka.KafkaStreamProcessor$$anonfun$run$1.apply(KafkaStreamProcessor.scala:18)
        at scala.collection.Iterator$class.foreach(Iterator.scala:742)
        at kafka.utils.IteratorTemplate.foreach(IteratorTemplate.scala:32)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at kafka.consumer.KafkaStream.foreach(KafkaStream.scala:25)
        at com.twitter.zipkin.receiver.kafka.KafkaStreamProcessor.run(KafkaStreamProcessor.scala:18)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Oct 21, 2015 2:36:33 PM com.twitter.zipkin.receiver.kafka.KafkaStreamProcessor run
ERROR: null

```

and the span  in kafka message is 

```
Span(trace_id:4922283572953088225, name:search, id:4922283572953088225, annotations:[Annotation(timestamp:1445408742421000, value:cs, host:Endpoint(ipv4:-1408105947, port:0, service_name:es)), Annotation(timestamp:1445408742518000, value:cr, host:Endpoint(ipv4:-1408105947, port:0, service_name:es))], binary_annotations:[BinaryAnnotation(key:es request, value:7B 0A 20 20 22 66 72 6F 6D 22 20 3A 20 30 2C 0A 20 20 22 73 69 7A 65 22 20 3A 20 32 30 2C 0A 20 20 22 71 75 65 72 79 22 3A 7B 22 62 6F 6F 6C 22 3A 7B 22 6D 75 73 74 22 3A 7B 22 72 61 6E 67 65 22 3A 7B 22 73 74 6F 72 65 4C 6F 67 54 69 6D 65 22 3A 7B 22 66 72 6F 6D 22 3A 22 32 30 31 35 2D 30 37 2D 31 34 54 30 30 3A 30 30 3A 30 30 2E 30 30 30 2B 30 38 30 30 22 2C 22 74 6F 22 3A 22 32..., annotation_type:STRING, host:Endpoint(ipv4:-1408105947, port:0, service_name:es)), BinaryAnnotation(key:es response, value:7B 0A 20 20 22 74 6F 6F 6B 22 20 3A 20 38 32 2C 0A 20 20 22 74 69 6D 65 64 5F 6F 75 74 22 20 3A 20 66 61 6C 73 65 2C 0A 20 20 22 5F 73 68 61 72 64 73 22 20 3A 20 7B 0A 20 20 20 20 22 74 6F 74 61 6C 22 20 3A 20 34 32 2C 0A 20 20 20 20 22 73 75 63 63 65 73 73 66 75 6C 22 20 3A 20 34 32 2C 0A 20 20 20 20 22 66 61 69 6C 65 64 22 20 3A 20 30 0A 20 20 7D 2C 0A 20 20 22 68 69 74 73 22 20..., annotation_type:STRING, host:Endpoint(ipv4:-1408105947, port:0, service_name:es))])

```

I print the span message before insert into kafka

my way is  log the span message and collected to kafka  
and then I use zipkin collector to receive kafka message  
this way will give me  the exception above 

but when i use ZipkinSpanCollector direct send to zipkin collector is correct

**Comment by rjbhewei** [comment]
I print  the span message before insert into kafka

**Comment by codefromthecrypt** [comment]
can you describe how you are sending this? Ex. similar to this?
https://github.com/openzipkin/brave/issues/102

**Comment by eirslett** [comment]
Closing due to lack of activity. Is this still a problem? If so, feel free to reopen!
