### ISSUE TITLE
Configurable cassandra driver's read timeout 

### ISSUE THREAD

**Issue by drax68** [openzipkin/zipkin#832]
On large datasets I've noticed frequent com.datastax.driver.core.OperationTimedOutException
Default timeout is 12 seconds, which is quite small.
Please add configuration flag for this parameter (for query service), so it can be overriden.
Or provide a way to override it in config.

**Comment by drax68** [comment]
Anyone can help with this? @adriancole?

**Comment by codefromthecrypt** [comment]
Do you know what command results in a response of >12s? Ex. can you post a
stack trace? That sounds like a long time.. I suspect we could update it or
punch a hole, but it would be nice to know what is taking so long..

**Comment by drax68** [comment]
Here is a stacktrace, it times out strictly after 12 seconds:

`06:53:38.952 [cluster1-nio-worker-0] ERROR c.t.f.h.i.e.FinatraDefaultExceptionMapper - internal server error
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: cassandra.example.com/1.2.3.4:9042 (com.datastax.driver.core.OperationTimedOutException: [cassandra.example.
com/1.2.3.4:9042] Operation timed out))
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:84) ~[zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37) ~[zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.ArrayBackedResultSet$MultiPage.prepareNextRow(ArrayBackedResultSet.java:285) ~[zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.ArrayBackedResultSet$MultiPage.isExhausted(ArrayBackedResultSet.java:245) ~[zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.ArrayBackedResultSet$1.hasNext(ArrayBackedResultSet.java:126) ~[zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at org.twitter.zipkin.storage.cassandra.Repository$6.apply(Repository.java:439) ~[zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at org.twitter.zipkin.storage.cassandra.Repository$6.apply(Repository.java:435) ~[zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.Futures$1.apply(Futures.java:713) ~[zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861) ~[zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:144) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:183) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler.access$2300(RequestHandler.java:44) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:748) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:429) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1013) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:936) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: cassandra.example.com/1.2.3.4:9042 (com.datastax.driver.core.OperationTimedOutException: [cassandra.example.com/1.2.3.4:9042] Operation timed out))
        at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:217) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler.access$1000(RequestHandler.java:44) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.sendRequest(RequestHandler.java:276) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution$1.run(RequestHandler.java:374) ~[zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
        ... 1 common frames omitted
06:53:38.953 [cluster1-nio-worker-0] INFO  c.t.f.h.filters.AccessLoggingFilter - 127.0.0.1 - - [14/Nov/2015:06:53:38 +0000] "GET /api/v1/spans?serviceName=servicename HTTP/1.1" 500 36 12085 "-"
06:53:40.351 [cluster1-worker-18] ERROR c.t.f.h.i.e.FinatraDefaultExceptionMapper - internal server error
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: cassandra.example.com/1.2.3.4:9042 (com.datastax.driver.core.OperationTimedOutException: [cassandra.example.com/1.2.3.4:9042] Operation timed out))
        at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:217) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler.access$1000(RequestHandler.java:44) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.sendRequest(RequestHandler.java:276) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution$1.run(RequestHandler.java:374) [zipkin-query-service-1.23.2-SNAPSHOT-all.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
06:53:40.351 [cluster1-worker-18] INFO  c.t.f.h.filters.AccessLoggingFilter - 127.0.0.1 - - [14/Nov/2015:06:53:40 +0000] "GET /api/v1/traces?limit=10&serviceName=servicename&minDuration=&spanName=all&annotationQuery=&endTs=1447483984514000 HTTP/1.1" 500 36 12043 "-"`

**Comment by drax68** [comment]
Hi, any update on this?

**Comment by codefromthecrypt** [comment]
so 12 seconds is a very long time. do you have some network problem where
it is normal for 12 seconds is normal? How do you know 13 seconds or 30
seconds would improve things? Or are you just interested in experimenting
why you are having severe connectivity problems.

Maybe we should fallback to a non-error state, like empty result, when this
occurs?

I want to avoid opening new flags for every one of the boundless scenarios
one could encounter. Reason is that our configuration story is quite bad
(unlike zipkin-java where it is quite easy to do this). Ex we have a lot of
work and if you find that 12 seconds or 30 seconds you still have a connect
timeout, then that work stays in the codebase..

I do think we need to consider how to do "pass-through" config to a driver.
This sort of pass-through was attempted in HTrace, for example in kafka
transport
https://github.com/apache/incubator-htrace/blob/master/htrace-zipkin/README.md

@michaelsembwever @yurishkuro do you have any ideas on this topic? Do you
think 12s timeout is unreasonably short? Should we add a fallback to empty
on this?

**Comment by yurishkuro** [comment]
We had an issue once that was manifesting in very long query latencies. It turned out to be due to the driver directing some queries to nodes in another data center. Solved by `DCAwareRoundRobinPolicy`:

```
  // on Mac the default data center name in Cassandra is 'datacenter1'
  val dataCenter  = flag[String] ("datacenter", "data center name used by DC-aware load balancing policy, required.")

  override def createClusterBuilder(): Cluster.Builder = {
    val dc = dataCenter.apply()
    val lbPolicy = new TokenAwarePolicy(new LatencyAwarePolicy.Builder(new DCAwareRoundRobinPolicy(dc)).build())
    super.createClusterBuilder()
      .withLoadBalancingPolicy(lbPolicy)
      .withQueryOptions(new QueryOptions().setConsistencyLevel(ConsistencyLevel.LOCAL_ONE))
  }
```

I think it would make sense to make this a default setting in zipkin.

Specifically on this issue, I don't think 12s is a reasonable timeout if Cassandra is operating normally, it either indicates misconfigured cluster, or bad query pattern (too much data requested?)

**Comment by drax68** [comment]
It's actually not connectivity issue, all servers hosted inside vpc and networking is not a problem. 
This error arises only if there is large amount of data to fetch from cassandra (large traces with thousands of spans), and cassandra requires more than 12 seconds to provide it. It matter of cassandra performance (though, it hosted on r3.xlarge with ssd disks).
Now we have ~15Gb of data daily, and zipkin becomes unusable after 1-2 days.
I guess more people will require that timeout to be configurable in future.

DCAwareRoundRobinPolicy shouldn't be the issue, since there is single cassandra instance.

**Comment by codefromthecrypt** [comment]
Sorry, I got distracted by the NoHostAvailableException in the log eventhough you mentioned the OperationTimedOutException underneath it. What parameter are you looking for specifically (just in case)?

It shouldn't take 12s to retrieve 10 traces (based on your log), especially in recent implementations. Ex. we have a default lookback parameter now, which you can use to reduce how far queries look back. In other words, if it is scanning days of data to get 10 traces, that sounds like a bug. What version are you running?

IIRC, twitter kept 3 days of trace data (at some point it was high as 7). Uber is 2d? There are certainly going to be limits. ~15Gb/day is an interesting figure. Do you know how many traces/day that turns into?

**Comment by drax68** [comment]
Currently running 1.25.1-SNAPSHOT with cassandra 2.0.17.
We are trying to keep 7d of data (afair, same default for lookback).
Roughly, it's 16 000 000 traces per day.

**Comment by codefromthecrypt** [comment]
@drax68 thanks for bearing with us.. do you mind turning debug logging on for org.twitter.zipkin.storage.cassandra.Repository ? It will emit which queries passed before blowing up. Ex. it would be nice to know if the blowup happened fetching ids or something else. A more recent stack trace will probably say most of that (the one in your log says 1.23.2-SNAPSHOT)

**Comment by codefromthecrypt** [comment]
ps feel free to join gitter to discuss https://gitter.im/openzipkin/zipkin I really think there's a solvable problem here.

**Comment by codefromthecrypt** [comment]
ps looks like this is the setting in question: http://docs.datastax.com/en/drivers/java/2.0/com/datastax/driver/core/SocketOptions.html#setReadTimeoutMillis-int-

**Comment by codefromthecrypt** [comment]
@drax68 not sure how you are deploying, but can you control your environment? If so, I'd love if you can experiment with the following.

query-cassandra.scala is the file used (implicitly with the `-f /query-cassandra.scala` argument to java -jar)

Make a copy of that, and replace the line `object Factory extends App with CassandraSpanStoreFactory` with this:

``` scala
object Factory extends App with CassandraSpanStoreFactory {
  override def createClusterBuilder(): Cluster.Builder = {
    val result = super.createClusterBuilder()
    result.getConfiguration.getSocketOptions.setReadTimeoutMillis(15000)
    result
  }
}
```

Start your server with a path to the alternate file. ex: `-f /query-patched-cassandra.scala`

See if you can find a timeout that works and report back?

**Comment by drax68** [comment]
Had to add "import com.datastax.driver.core.Cluster"
Here is a fresh stacktrace with suggested changes in, timeout override not works (let's move to gitter):

`22:15:19.425 [cluster1-nio-worker-3] INFO  c.t.f.h.filters.AccessLoggingFilter - 127.0.0.1 - - [18/Nov/2015:22:15:19 +0000] "GET /api/v1/traces?limit=10&serviceName=serviceName&minDuration=&endTs=1447871160169&spanName=all&annotationQuery= HTTP/1.1" 200 101450 1461 "-"
22:15:31.058 [cluster1-nio-worker-2] ERROR c.t.f.h.i.e.FinatraDefaultExceptionMapper - internal server error
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: cassandra.example.com/1.2.3.4:9042 (com.datastax.driver.core.OperationTimedOutException: [cassandra.example.com/1.2.3.4:9042] Operation timed out))
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:84) ~[zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37) ~[zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.ArrayBackedResultSet$MultiPage.prepareNextRow(ArrayBackedResultSet.java:285) ~[zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.ArrayBackedResultSet$MultiPage.isExhausted(ArrayBackedResultSet.java:245) ~[zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.ArrayBackedResultSet$1.hasNext(ArrayBackedResultSet.java:126) ~[zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at org.twitter.zipkin.storage.cassandra.Repository.lambda$getSpanNames$3(Repository.java:463) ~[zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.Futures$1.apply(Futures.java:713) ~[zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861) ~[zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:144) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:183) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler.access$2300(RequestHandler.java:44) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:748) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:429) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1013) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:936) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: cassandra.example.com/1.2.3.4:9042 (com.datastax.driver.core.OperationTimedOutException: [cassandra.example.com/1.2.3.4:9042] Operation timed out))
        at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:217) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler.access$1000(RequestHandler.java:44) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.sendRequest(RequestHandler.java:276) [zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution$1.run(RequestHandler.java:374) ~[zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
        ... 1 common frames omitted
22:15:31.069 [cluster1-nio-worker-2] INFO  c.t.f.h.filters.AccessLoggingFilter - 127.0.0.1 - - [18/Nov/2015:22:15:31 +0000] "GET /api/v1/spans?serviceName=serviceName HTTP/1.1" 500 36 13109 "-"`

**Comment by michaelsembwever** [comment]
+1 for LOCALE_ONE and DCAwareRoundRobinPolicy. absolutely.

>  Now we have ~15Gb of data daily, and zipkin becomes unusable after 1-2 days.

Something else is the problem here. Increasing the timeout isn't a real solution, even though I can understand a user's sentiment of a quick fix.

@drax68 can you provide output from `nodetool cfhistograms zipkin xxx` for each xxx=table in the zipkin keyspace. The output of `nodetool cfstats …` and `nodetool compactionstats;`and `nodetool tpstats;` will also be useful.

**Comment by drax68** [comment]
Sure, attaching report here [832.report.txt](https://github.com/openzipkin/zipkin/files/38424/832.report.txt)

**Comment by michaelsembwever** [comment]
The writes look healthy, and compactions are obviously keeping up.

But there basically no reads happening against this cluster?
How long has it been running for?

If it's recently been restarted, could you use the Zipkin UI for some time and then update that information again. (`nodetool cfstats zipkin` is only needed once).

**Comment by drax68** [comment]
Yes, no reads. Uptime should be near 40 hours.

**Comment by codefromthecrypt** [comment]
Will join gitter in a bit. By didn't work, you mean the value didn't take?
Or that 15s didn't help?

**Comment by drax68** [comment]
I mean that value didn't applied. You can see that from stacktrace I posted earlier.

**Comment by codefromthecrypt** [comment]
I must be completely blind as I still can't find the timeout value logged
in the error message. Anyway, thanks for clarifying!

**Comment by codefromthecrypt** [comment]
Oh never mind. The log timestamps indicate 12s duration. Don't mind me..

**Comment by michaelsembwever** [comment]
any updates on getting that info with reads included @drax68 ?

**Comment by drax68** [comment]
Here is a trace 
[zipkin-cassie.trace.txt](https://github.com/openzipkin/zipkin/files/42071/zipkin-cassie.trace.txt)

**Comment by michaelsembwever** [comment]
@drax68 the stacktrace in the log indicates it's on the call to `repository.getSpanNames(serviceName)` 

ie

```
....
org.twitter.zipkin.storage.cassandra.Repository.lambda$getSpanNames$3(Repository.java:463) ~[zipkin-query-service-1.25.1-SNAPSHOT-all.jar:na]
....
```

Quick question… 
What's your replication factor for the zipkin keyspace?

**RF=1 is not recommended**, even though it's the default it's wise that you raise it once in production to RF=2 minimum or best RF=3.

**Comment by drax68** [comment]
Replication factor is default and unchanged due to single-node cassandra setup.
Issue repeatable with cassandra 2.2.3, after few hours of running. There is also very low read io rate (kilobytes), I assume that all data cached in-memory by cassandra.

From traces "Response received on stream 0 but no handler set anymore" ~50ms after zipkin closed connection.

Anything else to test?

**Comment by michaelsembwever** [comment]
ok. i was under the impression you were running multiple nodes in this cluster. my bad.

@drax68, if you could…

1) check a few different stack traces to confirm if the exception is always happening within `repository.getSpanNames(serviceName)`

2) post the same info you had in 832.report.txt but after the timeout exception happens

If we can confirm (1) then i'll re-implement using buckets on the span_names table. Using buckets 0-9 was removed in commit 7f339b5  because the duplication of writes was removed. It might be here evident that single partitions (ie serviceName) simply have too many spanNames stored in them, and by using buckets 0-9 again we help break up the pagination of reads.

**Comment by michaelsembwever** [comment]
@drax68 another thing you could experiment with here is 

3) turn on row caching for the span_names table. you can do this quickly in cqlsh with

```
ALTER TABLE zipkin.span_names WITH caching = {'keys': 'ALL', 'rows_per_partition': "ALL"};
```

**Comment by yurishkuro** [comment]
@drax68 do you know how many span names per service name you have on average?  It could be the case that the cardinality of your span names is too high. For example, if you have a REST end point `/user/{used_id}`, then the span name should be just `get_user`. If you include user_id in the span name, you will get an explosion of span names that neither UI nor Cassandra would be happy with.

**Comment by codefromthecrypt** [comment]
You guys are awesome. I'm really thankful we have a team earnestly trying
to solve this. Keep up the good work! :clap:

**Comment by drax68** [comment]
@michaelsembwever 
1. Confirmed, exception always contains org.twitter.zipkin.storage.cassandra.Repository.lambda$getSpanNames
1. New version, just after fresh exception 
   [832.report2.txt](https://github.com/openzipkin/zipkin/files/44236/832.report2.txt)
2. When caching enabled got same exception.
3. 300000 span_names for single service. Need to sync up with service developers.

Guys, you are extremly helpfull, thank you.

**Comment by yurishkuro** [comment]
> 300000 span_names for single service.

lol... there you go. A typical observability misuse problem: "Why don't I include UUID in my metric name..."

There is already a write cache `writtenNames` in the Repository for both service and span names. It's currently flat, but if we convert it to be a map by service name, than you can cap the number of span names per service, at least within the TTL interval of that cache (1hr by default, we're using 12hrs).  When span names exceed the cap, you can replace them with some fixed name like "too-many-names". Maybe add the original name as b-annotation. This will protect the service from misbehaving span senders.

**Comment by michaelsembwever** [comment]
> This will protect the service from misbehaving span senders.

I'm more in favour of simply logging WARN or ERROR statements over complicating the code. 

eg i'm for putting a limit on the select cql in getSpanNames(serviceName) (that's super simple).

Otherwise until the user goes and addresses the fault the system won't work, so why pretend to make it work…?

**Comment by yurishkuro** [comment]
No objection to logging errors and/or emitting metrics that bad things are happening, but the system should not let garbage data into the storage. We had to fight quite a few fires when bad players were bringing the system to its knees, affecting good citizens just the same as bad ones. It's a basic quota system. 

Besides, the way I suggest handling it does not make the system "not work", it just collapses garbage span names into one. The data is still there and can be searched.

**Comment by michaelsembwever** [comment]
>  …affecting good citizens just the same as bad ones.

Yes that's a good point, and does argues for changing the flat cache to map->map.

But what i'm thinking though is looking into what really are the problems here…

The number of writes isn't a problem. 

The size of the `writtenNames` cache isn't necessarily a problem. Is a map with 300000 strings a memory issue? (and if so the existing fix is to reduce the ttl interval).

The reads of the wide rows we know is a problem.

>  but the system should not let garbage data into the storage

How are we to know what is garbage? 
It's easy to say 300000 is obviously wrong, but where do we draw the line? Especially when a variable ttl interval in brought into the picture.
1000 could be wrong for one installation and 100000 could be correct for another.
And at the end of the day supporting wide rows is something Cassandra can do.

That's why i'm more in favour, because it's less presumptuous, in providing the "cap" on the select statement. 

>  We had to fight quite a few fires when bad players were bringing the system to its knees, … 

What were the fires you were experiencing? Was it that the data was actually in the system (data that will ttl away eventually anyway), or that the reads were bringing it down?

**Comment by yurishkuro** [comment]
> 1000 could be wrong for one installation and 100000 could be correct for another.

I am not sure I see a realistic scenario where 100k span names per service is correct. The only reason we collect span names is to show them in the second dropdown in the UI. I'd argue any number over 100 is an overkill, who's gonna want to scroll through that? If a service has over 100 legitimately unique operations, yeah perhaps this 100 const can be made tunable, but perhaps it's time to consider refactoring the service, as something is probably wrong with its abstractions, maybe a certain portion of the span name should really be in the service name.

Besides these semantic considerations, however, there's a separate need to protect Zipkin storage from runaway emitters, by implementing a simple circuit-breaker.

> What were the fires you were experiencing? 

The fires weren't with the tracing systems, but with metrics. We use Cassandra as tsdb, and Elasticsearch for indexing metric names, e.g. to serve Graphite queries like `stats.counts.service.*.xxx.*.yyy.*.zzz.*.*`. From time to time some service would come up that emits metrics with UUID or timestamp or some other high cardinality value as part of the metric name, which explodes the writes to ES, and it's very difficult to build a pattern match that would separate good names from bad. But by capping the number of metrics per service we were able to get a handle on it and build alerts & circuit-breakers.

**Comment by michaelsembwever** [comment]
> The only reason we collect span names is to show them in the second dropdown in the UI. I'd argue any number over 100 is an overkill, who's gonna want to scroll through that?

Indeed this is the angle I'm seeing it from. That is there's really no point in returning so many from `getSpanNames(..)` when no one is going to scroll through such a large list.Therefore limiting the select statement  is what involves the smallest change in the code.

But thinking more about what you suggest makes sense. The only purpose to span_names is for that UI component, and if we can avoid writing "hot" partitions in C\* we should do that.

@yurishkuro interested in writing up a patch for what you're suggesting?

**Comment by michaelsembwever** [comment]
Are you on top of this @yurishkuro ?

**Comment by yurishkuro** [comment]
no, sorry, I am not, unlikely to get to it in the next couple of weeks, have a marathon project at work.

**Comment by michaelsembwever** [comment]
closing issue. minimal required patch is provided in pull request.
further work on avoiding hot partitions can be raised in a subsequent ticket.
