### ISSUE TITLE
Zipkin-query duration-related error in 1.24.1-SNAPHOT

### ISSUE THREAD

**Issue by drax68** [openzipkin/zipkin#855]
Mentioned build not able to work with cassandra db created by previous versions of zipkin. Stacktrace:
`Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured columnfamily span_duration_index
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:102) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:207) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:184) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1183) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1177) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:183) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler.access$2300(RequestHandler.java:44) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:748) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:573) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1013) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:936) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) ~[zipkin-query-service-1.24.1-SNAPSHOT-all.jar:na]
        ... 1 common frames omitted`

**Comment by codefromthecrypt** [comment]
how about adding the table before you upgrade?

https://github.com/openzipkin/zipkin/blob/master/zipkin-cassandra-core/src/main/resources/cassandra-schema-cql3.txt#L58

**Comment by drax68** [comment]
Expected that new tables addition automated, since zipkin can initially create tables.

**Comment by codefromthecrypt** [comment]
good point. are you running a flag that prevents auto-addition perhaps?

**Comment by drax68** [comment]
No, auto-addition not disabled in any way.

**Comment by codefromthecrypt** [comment]
ex. if you are using docker-containers, or the -service packages as an entrypoint (ex. `query-cassandra.scala`), then `CASSANDRA_ENSURE_SCHEMA` env is used, which defaults to true.

If you have a custom build, then the flag `zipkin.store.cassandra.ensureSchema` defaults to false. How are you running?

**Comment by drax68** [comment]
I'm running custom-built jars using https://github.com/openzipkin/zipkin/blob/master/zipkin-query-service/config/query-cassandra.scala 
In that case what value will be assigned to zipkin.store.cassandra.ensureSchema?

**Comment by codefromthecrypt** [comment]
it should default to true.. what's weird is that this implies `CREATE
TABLE IF NOT EXISTS zipkin.span_duration_index...` didn't work? which
doesn't make immediate sense to me.

**Comment by codefromthecrypt** [comment]
ex. ensureExists in Repository.java isn't conditional on anything
except for the flag, so the DDL should execute top-to-bottom.

**Comment by codefromthecrypt** [comment]
by should I mean it does default to true, due to this line:
https://github.com/openzipkin/zipkin/blob/master/zipkin-query-service/config/query-cassandra.scala#L27

**Comment by codefromthecrypt** [comment]
ps hold on this one if you can :) there's a schema adjustment for that
table coming!

**Comment by drax68** [comment]
After checking scala config, noticed that it lacks line you pointed. That's the case, thank you.

**Comment by codefromthecrypt** [comment]
whew! Thanks for reporting back.. was a bit worried!

**Comment by codefromthecrypt** [comment]
ps 1.25.0 adjusts the aforementioned table. hot off the press
