### ISSUE TITLE
[bug] NullPointerException when running collector 1.32.2

### ISSUE THREAD

**Issue by prat0318** [openzipkin/zipkin#944]
Looks related to #909 PR. NPE starts occuring after a minute or two the collector starts. It halts processing further. It got introduced between `1.30.1...1.32.2`.

cc @adriancole 

below is the trace:

``` java
Feb 04, 2016 9:39:13 PM com.twitter.zipkin.receiver.kafka.KafkaStreamProcessor run
ERROR: null
java.lang.NullPointerException
    at com.twitter.zipkin.util.Util$.getArrayFromBuffer(Util.scala:28)
    at com.twitter.zipkin.storage.cassandra.CassandraSpanStore$$anonfun$com$twitter$zipkin$storage$cassandra$CassandraSpanStore$$annotationKey$1.apply(CassandraSpanStore.scala:64)
    at com.twitter.zipkin.storage.cassandra.CassandraSpanStore$$anonfun$com$twitter$zipkin$storage$cassandra$CassandraSpanStore$$annotationKey$1.apply(CassandraSpanStore.scala:64)
    at scala.Option.map(Option.scala:146)
    at com.twitter.zipkin.storage.cassandra.CassandraSpanStore.com$twitter$zipkin$storage$cassandra$CassandraSpanStore$$annotationKey(CassandraSpanStore.scala:64)
    at com.twitter.zipkin.storage.cassandra.CassandraSpanStore$$anonfun$com$twitter$zipkin$storage$cassandra$CassandraSpanStore$$indexByAnnotations$1$$anonfun$3$$anonfun$apply$4.apply(CassandraSpanStore.scala:174)
    at com.twitter.zipkin.storage.cassandra.CassandraSpanStore$$anonfun$com$twitter$zipkin$storage$cassandra$CassandraSpanStore$$indexByAnnotations$1$$anonfun$3$$anonfun$apply$4.apply(CassandraSpanStore.scala:168)
    at scala.Option.map(Option.scala:146)
    at com.twitter.zipkin.storage.cassandra.CassandraSpanStore$$anonfun$com$twitter$zipkin$storage$cassandra$CassandraSpanStore$$indexByAnnotations$1$$anonfun$3.apply(CassandraSpanStore.scala:168)
    at com.twitter.zipkin.storage.cassandra.CassandraSpanStore$$anonfun$com$twitter$zipkin$storage$cassandra$CassandraSpanStore$$indexByAnnotations$1$$anonfun$3.apply(CassandraSpanStore.scala:167)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
    at scala.collection.Iterator$class.foreach(Iterator.scala:742)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
    at com.twitter.zipkin.storage.cassandra.CassandraSpanStore$$anonfun$com$twitter$zipkin$storage$cassandra$CassandraSpanStore$$indexByAnnotations$1.apply(CassandraSpanStore.scala:167)
    at com.twitter.zipkin.storage.cassandra.CassandraSpanStore$$anonfun$com$twitter$zipkin$storage$cassandra$CassandraSpanStore$$indexByAnnotations$1.apply(CassandraSpanStore.scala:151)
    at scala.Option.map(Option.scala:146)
    at com.twitter.zipkin.storage.cassandra.CassandraSpanStore.com$twitter$zipkin$storage$cassandra$CassandraSpanStore$$indexByAnnotations(CassandraSpanStore.scala:151)
    at com.twitter.zipkin.storage.cassandra.CassandraSpanStore$$anonfun$apply$11.apply(CassandraSpanStore.scala:244)
    at com.twitter.zipkin.storage.cassandra.CassandraSpanStore$$anonfun$apply$11.apply(CassandraSpanStore.scala:230)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.immutable.List.map(List.scala:285)
    at com.twitter.zipkin.storage.cassandra.CassandraSpanStore.apply(CassandraSpanStore.scala:230)
    at com.twitter.zipkin.collector.builder.CollectorServiceBuilder$$anonfun$apply$1$$anonfun$1.apply(CollectorServiceBuilder.scala:67)
    at com.twitter.zipkin.collector.builder.CollectorServiceBuilder$$anonfun$apply$1$$anonfun$1.apply(CollectorServiceBuilder.scala:66)
    at com.twitter.zipkin.receiver.kafka.KafkaStreamProcessor$$anonfun$run$1.apply(KafkaStreamProcessor.scala:21)
    at com.twitter.zipkin.receiver.kafka.KafkaStreamProcessor$$anonfun$run$1.apply(KafkaStreamProcessor.scala:19)
    at scala.collection.Iterator$class.foreach(Iterator.scala:742)
    at kafka.utils.IteratorTemplate.foreach(IteratorTemplate.scala:32)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at kafka.consumer.KafkaStream.foreach(KafkaStream.scala:25)
    at com.twitter.zipkin.receiver.kafka.KafkaStreamProcessor.run(KafkaStreamProcessor.scala:19)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by codefromthecrypt** [comment]
not sure if that PR is the smoking gun or not.

The NPE suggests that the call to
`annotationKey(serviceName: String, annotation: String, value: Option[ByteBuffer])` had an option of null at the end.

would need to track calls to this to figure out what's passing null.

**Comment by prat0318** [comment]
You were right. It was actually happening from before. This happens when a value for binary annotation is `None` instead of `str` if type expected is str. It was a error from our end. Although zipkin can return some better error than NPE. I am ok to close the issue though. Thanks!

**Comment by codefromthecrypt** [comment]
NPEs are bugs! I'll fix it
